import prisma from "./prisma"

type AuditAction =
  | "LOGIN"
  | "LOGOUT"
  | "CREATE_CLIENT"
  | "UPDATE_CLIENT"
  | "DELETE_CLIENT"
  | "CREATE_CLIENT_PORTAL_ACCESS"
  | "REVOKE_CLIENT_PORTAL_ACCESS"
  | "SEND_CLIENT_PORTAL_MESSAGE"
  | "UPDATE_CLIENT_PORTAL_APPOINTMENT"
  | "SEND_CRM_EMAIL"
  | "UPDATE_EMAIL_THREAD"
  | "UPDATE_COMMUNICATION_CHANNEL"
  | "CREATE_EMAIL_TEMPLATE"
  | "UPDATE_EMAIL_TEMPLATE"
  | "ARCHIVE_EMAIL_TEMPLATE"
  | "CREATE_EMAIL_SEQUENCE"
  | "UPDATE_EMAIL_SEQUENCE"
  | "DUPLICATE_EMAIL_SEQUENCE"
  | "CREATE_EMAIL_SEQUENCE_STEP"
  | "DELETE_EMAIL_SEQUENCE_STEP"
  | "MOVE_EMAIL_SEQUENCE_STEP"
  | "UPDATE_EMAIL_SEQUENCE_STATUS"
  | "UPDATE_EMAIL_SEQUENCE_SETTINGS"
  | "ENROLL_EMAIL_SEQUENCE"
  | "CREATE_AUTOMATION_WORKFLOW"
  | "UPDATE_AUTOMATION_WORKFLOW"
  | "DUPLICATE_AUTOMATION_WORKFLOW"
  | "UPDATE_AUTOMATION_WORKFLOW_STATUS"
  | "PROCESS_EMAIL_SEQUENCES"
  | "CREATE_MARKETING_CAMPAIGN"
  | "UPDATE_MARKETING_CAMPAIGN"
  | "UPDATE_MARKETING_CAMPAIGN_ASSET"
  | "CREATE_OPPORTUNITY"
  | "CREATE_OPPORTUNITY_ACTIVITY"
  | "UPDATE_OPPORTUNITY"
  | "DELETE_OPPORTUNITY"
  | "CREATE_PROJECT"
  | "CREATE_PROJECT_TEMPLATE"
  | "UPDATE_PROJECT_MILESTONE_PLAN"
  | "UPDATE_PROJECT"
  | "DELETE_PROJECT"
  | "CREATE_QUOTE"
  | "UPDATE_QUOTE"
  | "UPDATE_QUOTE_STATUS"
  | "DELETE_QUOTE"
  | "CREATE_INVOICE"
  | "CREATE_INVOICE_FROM_TIME"
  | "CREATE_INVOICE_FROM_ORDER"
  | "UPDATE_INVOICE"
  | "UPDATE_INVOICE_STATUS"
  | "DELETE_INVOICE"
  | "RECORD_PAYMENT"
  | "CREATE_CONTRACT"
  | "CREATE_CONTRACT_AMENDMENT"
  | "CREATE_MAINTENANCE_RENEWAL_PROPOSAL"
  | "CREATE_AGENCY"
  | "UPDATE_AGENCY"
  | "UPDATE_AGENCY_ASSIGNMENTS"
  | "UPDATE_CONTRACT"
  | "SIGN_CONTRACT"
  | "DELETE_CONTRACT"
  | "CREATE_EXPENSE"
  | "UPDATE_EXPENSE"
  | "DELETE_EXPENSE"
  | "GENERATE_PDF"
  | "OCR_EXPENSE"
  | "UPDATE_SETTINGS"
  | "REQUEST_PASSWORD_RESET"
  | "RESET_PASSWORD"
  | "ENABLE_MFA"
  | "DISABLE_MFA"
  | "ROTATE_MFA_RECOVERY_CODES"
  | "CHANGE_PASSWORD"
  | "REVOKE_SESSIONS"
  | "CREATE_CUSTOMER_ORDER"
  | "CONSUME_STOCK_RESERVATION"
  | "TRANSFER_STOCK"
  | "UPDATE_PROJECT_TECHNICAL_PROFILE"
  | "COMPLETE_FIELD_INTERVENTION"
  | "UPDATE_FIELD_INTERVENTION_PLAN"
  | "CREATE_SERVICE_TICKET"
  | "UPDATE_SERVICE_TICKET"
  | "ROUTE_SERVICE_TICKET"
  | "MERGE_SERVICE_TICKET"
  | "UNMERGE_SERVICE_TICKET"
  | "ADD_SERVICE_TICKET_NOTE"
  | "LINK_SERVICE_TICKET_THREAD"
  | "CREATE_KNOWLEDGE_ARTICLE"
  | "UPDATE_KNOWLEDGE_ARTICLE"
  | "CREATE_SERVICE_MACRO"
  | "UPDATE_SERVICE_MACRO"
  | "ARCHIVE_SERVICE_MACRO"
  | "CREATE_SERVICE_DIAGNOSTIC_GUIDE"
  | "UPDATE_SERVICE_DIAGNOSTIC_GUIDE"
  | "ARCHIVE_SERVICE_DIAGNOSTIC_GUIDE"
  | "COMPLETE_SERVICE_TICKET_DIAGNOSTIC"
  | "INSTALL_CUSTOMER_HEALTH_RULES"
  | "CREATE_CUSTOMER_HEALTH_RULE"
  | "ARCHIVE_CUSTOMER_HEALTH_RULE"
  | "UPDATE_CLIENT_SUCCESS_PROFILE"
  | "RECOMPUTE_CUSTOMER_HEALTH"
  | "EXPORT_SERVICE_ANALYTICS"
  | "CREATE_SATISFACTION_SURVEY"
  | "CREATE_SATISFACTION_REQUEST"
  | "SUBMIT_SATISFACTION_RESPONSE"
  | "RESOLVE_INTERVENTION_RESERVATION"
  | "CONSUME_INTERVENTION_MATERIAL"
  | "CREATE_MAINTENANCE_CONTRACT"
  | "UPDATE_MAINTENANCE_RENEWAL"
  | "RENEW_MAINTENANCE_CONTRACT"
  | "SIGN_DELIVERY_NOTE"
  | "SCHEDULE_MAINTENANCE_VISIT"
  | "CREATE_CATALOG_PRODUCT"
  | "UPDATE_CATALOG_PRODUCT"
  | "UPDATE_PRODUCT_CONFIGURATION"
  | "CREATE_PURCHASE_ORDER"
  | "SUBMIT_PURCHASE_ORDER"
  | "APPROVE_PURCHASE_ORDER"
  | "SEND_PURCHASE_ORDER"
  | "ACKNOWLEDGE_PURCHASE_ORDER"
  | "RECEIVE_PURCHASE_ORDER"
  | "RESOLVE_PURCHASE_ISSUE"
  | "CREATE_SUPPLIER_RETURN"
  | "CREDIT_SUPPLIER_RETURN"

interface AuditParams {
  userId: string
  action: AuditAction
  resource: string
  resourceId?: string
  payload?: unknown
  ipAddress?: string
}

export async function logAction({
  userId,
  action,
  resource,
  resourceId,
  payload,
  ipAddress
}: AuditParams) {
  try {
    return await prisma.auditLog.create({
      data: {
        userId: userId as string,
        action,
        resource,
        resourceId,
        payload: payload ? JSON.parse(JSON.stringify(payload)) : undefined,
        ipAddress: ipAddress as string | undefined,
      }
    })
  } catch (error) {
    console.error("Failed to log audit action:", error)
    // We don't throw here to avoid failing the main action just because logging failed
  }
}
