import { BookOpen, CalendarDays, Headphones, Inbox, MessageSquareHeart, Repeat2, SlidersHorizontal, Tickets } from "lucide-react"
import { getWorkspaceOverview } from "@/actions/workspaces"
import { OnboardingRequired } from "@/components/shared/onboarding-required"
import { WorkspaceHub } from "@/app/dashboard/_components/workspace-hub"

export default async function ServiceWorkspacePage() {
  const data = await getWorkspaceOverview()
  if (!data) return <OnboardingRequired title="Configurez votre espace" description="Créez le profil entreprise avant de gérer le service client." />
  return <WorkspaceHub eyebrow="Espace service" title="SAV et fidélisation" description="Priorisez les demandes, interventions, garanties et échéances qui protègent la satisfaction client." primaryAction={{ name: "Ouvrir le centre de support", href: "/dashboard/service/help-desk", icon: Headphones, description: "Voir les files et délais" }} metrics={[{ label: "Tickets ouverts", value: data.openTickets, detail: "À diagnostiquer ou résoudre", alert: data.openTickets > 0 }, { label: "Interventions", value: data.scheduledInterventions, detail: "Planifiées ou en cours" }, { label: "Contrats actifs", value: data.maintenanceContracts, detail: "Entretien et maintenance" }, { label: "Messages non lus", value: data.unreadEmail, detail: "Conversations ouvertes", alert: data.unreadEmail > 0 }]} sections={[{ title: "Assistance", description: "Répondre, diagnostiquer et résoudre.", links: [{ name: "Centre de support", href: "/dashboard/service/help-desk", icon: Tickets, description: "Files, priorités, engagements de résolution et affectations." }, { name: "Boîte de réception", href: "/dashboard/communications", icon: Inbox, description: "Conversations et historique client." }, { name: "Planning des interventions", href: "/dashboard/operations?tab=planning", icon: CalendarDays, description: "Affectations, capacité et comptes rendus." }] }, { title: "Fidélisation et autonomie", description: "Capitaliser les réponses et mesurer la qualité perçue.", links: [{ name: "Base de connaissances", href: "/dashboard/service/connaissance", icon: BookOpen, description: "Procédures internes, FAQ et articles publiés dans le portail." }, { name: "Satisfaction client", href: "/dashboard/service/satisfaction", icon: MessageSquareHeart, description: "Enquêtes CSAT, NPS, invitations et verbatims." }] }, { title: "Relation après-vente", description: "Conserver le contexte du parc et des engagements.", links: [{ name: "Parc installé", href: "/dashboard/operations?tab=assets", icon: SlidersHorizontal, description: "Produits posés, séries, garanties et état." }, { name: "Contrats d'entretien", href: "/dashboard/operations?tab=maintenance", icon: Repeat2, description: "Échéances, visites et facturation." }] }]} />
}
