import { ChartNoAxesCombined, Gauge, Inbox, Megaphone, Workflow } from "lucide-react"
import { getWorkspaceOverview } from "@/actions/workspaces"
import { OnboardingRequired } from "@/components/shared/onboarding-required"
import { WorkspaceHub } from "@/app/dashboard/_components/workspace-hub"

export default async function MarketingWorkspacePage() {
  const data = await getWorkspaceOverview()
  if (!data) return <OnboardingRequired title="Configurez votre espace" description="Créez le profil entreprise avant de piloter le marketing." />
  return <WorkspaceHub eyebrow="Espace marketing" title="Acquisition et engagement" description="Structurez les audiences, messages et automatisations qui transforment les demandes en projets qualifiés." primaryAction={{ name: "Créer une séquence", href: "/dashboard/automatisations", icon: Megaphone, description: "Préparer une campagne" }} metrics={[{ label: "Prospects actifs", value: data.activeLeads, detail: "À qualifier ou nourrir" }, { label: "Segments", value: data.activeSegments, detail: "Audiences actives" }, { label: "Automatisations", value: data.activeWorkflows, detail: "Règles en production" }, { label: "Réponses non lues", value: data.unreadEmail, detail: "Conversations à traiter", alert: data.unreadEmail > 0 }]} sections={[{ title: "Audiences", description: "Comprendre qui cibler et pourquoi.", links: [{ name: "Segments et scoring", href: "/dashboard/marketing", icon: Gauge, description: "Scores explicables, listes actives et priorités." }, { name: "Prospects entrants", href: "/dashboard/leads", icon: ChartNoAxesCombined, description: "Sources, consentements et qualification." }] }, { title: "Engagement", description: "Préparer les messages et automatiser le suivi.", links: [{ name: "Modèles et séquences", href: "/dashboard/automatisations", icon: Megaphone, description: "Contenus, étapes, délais et inscriptions." }, { name: "Workflows", href: "/dashboard/automatisations", icon: Workflow, description: "Déclencheurs, conditions, actions et journal." }, { name: "Communications", href: "/dashboard/communications", icon: Inbox, description: "Réponses, événements et performance e-mail." }] }]} />
}
