import { expect, test } from "@playwright/test"
test("finds and edits a paginated campaign and its earlier asset without changing the visual layout", async ({ page }, info) => {
  const name = `UIQA Campaign management ${info.project.name}`
  await page.goto("/dashboard/campagnes")
  await page.getByLabel("Rechercher une campagne", { exact: true }).fill("UIQA Campaign management")
  await page.getByRole("button", { name: "Rechercher", exact: true }).click()
  await expect(page.getByText("29 campagne(s) · Page 1 sur 2", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Page suivante", exact: true }).click()
  const card = page.locator('[data-slot="card"]').filter({ has: page.getByText(name, { exact: true }) })
  await expect(card).toBeVisible()
  await card.getByRole("button", { name: "Modifier", exact: true }).first().click()
  const campaignForm = card.locator("form").filter({ has: page.getByLabel("Objectif", { exact: true }) })
  await campaignForm.getByLabel("Objectif", { exact: true }).fill(`Fictional edited objective ${info.project.name}`)
  await campaignForm.getByLabel("Budget (€)", { exact: true }).fill("123.45")
  await campaignForm.getByRole("button", { name: "Enregistrer", exact: true }).click()
  await expect(page.getByText("Campagne mise à jour.", { exact: true })).toBeVisible()
  await expect(card).toContainText(`Fictional edited objective ${info.project.name}`)
  await card.getByRole("button", { name: `Page suivante : livrables ${name}`, exact: true }).click()
  const assetName = `UIQA editable asset ${info.project.name} 0`
  const asset = card.locator("div.space-y-3.p-3").filter({ has: page.getByText(assetName, { exact: true }) })
  await expect(asset).toBeVisible()
  await asset.getByRole("button", { name: "Modifier", exact: true }).click()
  await asset.getByLabel("Nom", { exact: true }).fill(`UIQA edited asset ${info.project.name}`)
  await asset.getByLabel("URL", { exact: true }).fill("https://example.test/fictional-resource")
  await asset.getByRole("button", { name: "Enregistrer", exact: true }).click()
  await expect(page.getByText("Livrable mis à jour.", { exact: true })).toBeVisible()
  await expect(card).toContainText(`UIQA edited asset ${info.project.name}`)
  await page.reload()
  await expect(card).toContainText(`Fictional edited objective ${info.project.name}`)
  await card.getByLabel(`Rechercher un livrable pour ${name}`).fill(`UIQA edited asset ${info.project.name}`)
  await expect(card).toContainText(`UIQA edited asset ${info.project.name}`)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => innerWidth))
})
