import { execFile } from "node:child_process"
import { promisify } from "node:util"
import { expect, test } from "@playwright/test"
const execute = promisify(execFile)

test("persists a verified audience, pauses and resumes its atomic enrollment without sending mail", async ({ page }, info) => {
  const name = `UIQA Activation ${info.project.name}`
  await page.goto("/dashboard/campagnes")
  await page.getByLabel("Rechercher une campagne", { exact: true }).fill(name)
  await page.getByRole("button", { name: "Rechercher", exact: true }).click()
  const card = page.locator('[data-slot="card"]').filter({ has: page.getByText(name, { exact: true }) })
  await expect(card).toBeVisible()
  await card.getByRole("button", { name: "Vérifier l’audience", exact: true }).click()
  await expect(page.getByText("Audience vérifiée sans inscription.", { exact: true })).toBeVisible()
  const report = card.getByLabel(`Rapport d’audience pour ${name}`, { exact: true })
  await expect(report).toContainText("26 prospect(s) · 24 éligible(s) · 2 exclu(s)")
  await expect(report).toContainText("0/26 traité(s) · 0 inscrit(s)")
  await report.getByRole("button", { name: `Page suivante : audience ${name}`, exact: true }).click()
  await expect(report).toContainText("Page 2 sur 2")
  await expect(report).toContainText("Preuve liée à l’adresse invalide ou retirée")
  await report.getByRole("button", { name: "Inscrire l’audience vérifiée", exact: true }).click()
  const confirmation = page.getByRole("dialog", { name: /Inscrire l’audience vérifiée/ })
  await confirmation.getByRole("button", { name: "Inscrire l’audience vérifiée", exact: true }).click()
  await expect(report).toContainText("Inscription en cours")
  await report.getByRole("button", { name: "Mettre l’inscription en pause", exact: true }).click()
  await expect(report).toContainText("Inscription en pause")
  await page.reload()
  await expect(report).toContainText("Inscription en pause")
  await report.getByRole("button", { name: "Reprendre l’inscription", exact: true }).click()
  await expect(report).toContainText("Inscription en cours")
  await execute(process.execPath, ["--conditions=react-server", "--import", "tsx", "scripts/verify-e2e-campaign-activation.mjs", name], { timeout: 30_000 })
  await page.reload()
  await expect(report).toContainText("Inscription terminée")
  await expect(report).toContainText("26/26 traité(s) · 24 inscrit(s) · 0 déjà inscrit(s) · 0 refusé(s)")
  await card.getByRole("button", { name: "Vérifier l’audience", exact: true }).click()
  await expect(report).toContainText("26 prospect(s) · 0 éligible(s) · 26 exclu(s)")
  const close = report.getByRole("button", { name: "Clore l’inscription restante", exact: true })
  await expect(close).toBeDisabled()
  await report.getByLabel(`Motif de clôture pour ${name}`, { exact: true }).fill("Capture fictive remplacée")
  await close.click()
  const closure = page.getByRole("dialog", { name: "Clore l’inscription restante ?", exact: true })
  await closure.getByRole("button", { name: "Annuler", exact: true }).click()
  await expect(report).toContainText("Audience vérifiée")
  await close.click()
  await closure.getByRole("button", { name: "Clore l’inscription restante", exact: true }).click()
  await expect(report).toContainText("Inscription restante close")
  await page.reload()
  await expect(report).toContainText("Capture fictive remplacée")
  await card.getByRole("button", { name: "Captures antérieures", exact: true }).click()
  const history = card.getByLabel(`Capture antérieure pour ${name}`, { exact: true })
  const completed = history.locator("option").filter({ hasText: "Inscription terminée" })
  await expect(completed).toHaveCount(1)
  await history.selectOption((await completed.getAttribute("value"))!)
  await expect(report).toContainText("26/26 traité(s) · 24 inscrit(s)")
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => innerWidth))
})
