import { expect, test } from "@playwright/test"

test("paginates signed contract archives and preserves a private copy in a draft without sending", async ({ page }, testInfo) => {
  const subject = `UIQA signed contract attachment ${testInfo.project.name} ${Date.now()}`
  await page.goto("/dashboard/communications?tab=compose")
  await page.getByLabel("Rechercher un destinataire").fill("recipient550@example.test")
  await expect(page.getByLabel("Destinataire", { exact: true }).locator("option")).toHaveCount(2)
  await page.getByLabel("Destinataire", { exact: true }).selectOption("cuiqarecipient000000000550")
  await page.getByLabel("Objet", { exact: true }).fill(subject)
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Fictional signed contract attachment</p>")
  await page.getByRole("button", { name: "Joindre un document CRM", exact: true }).click()
  const picker = page.getByRole("dialog", { name: "Joindre un document CRM", exact: true })
  await expect(picker.getByLabel("Source du document").locator('option[value="SIGNED_CONTRACT"]')).toBeEnabled()
  await picker.getByLabel("Source du document").selectOption("SIGNED_CONTRACT")
  await picker.getByLabel("Rechercher un document").fill("UIQA-CRM-CONTRACT")
  await expect(picker.getByLabel("Document CRM", { exact: true }).locator("option")).toHaveCount(26)
  await picker.getByRole("button", { name: "Page suivante", exact: true }).click()
  await expect(picker.getByText("31 document(s) · Page 2 sur 2", { exact: true })).toBeVisible()
  await picker.getByLabel("Rechercher un document").fill("UIQA-CRM-CONTRACT-030")
  await expect(picker.getByLabel("Document CRM", { exact: true }).locator("option")).toHaveCount(2)
  await expect(picker.getByLabel("Document CRM", { exact: true }).locator("option").last()).toContainText("signé le")
  await picker.getByLabel("Document CRM", { exact: true }).selectOption("cuiqacrmcontract000000030")
  await picker.getByRole("button", { name: "Ajouter au brouillon", exact: true }).click()
  await expect(page.getByRole("button", { name: "Retirer UIQA-CRM-CONTRACT-030.pdf", exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  const row = page.locator("div.border-b").filter({ has: page.getByText(subject, { exact: true }) })
  await row.getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(page.getByRole("button", { name: "Retirer UIQA-CRM-CONTRACT-030.pdf", exact: true })).toBeVisible()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Fictional signed contract attachment</p>")
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await expect(page.getByText("E-mail envoyé et ajouté à l’historique.", { exact: true })).toHaveCount(0)
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row.getByRole("button", { name: "Supprimer", exact: true }).click()
  await page.getByRole("dialog", { name: "Supprimer ce brouillon ?" }).getByRole("button", { name: "Supprimer", exact: true }).click()
})
