import { expect, test } from "@playwright/test"

test("forwards the selected older message into a new draft, resets copies and files, and leaves recipient and send manual", async ({ page }, testInfo) => {
  const previousSubject = `UIQA Forward predecessor ${testInfo.project.name} ${Date.now()}`
  const saves: string[] = []
  page.on("request", request => {
    const body = request.postData() || ""
    if (request.method() === "POST" && request.headers()["next-action"] && body.includes('"createKey"') && body.includes("Tr: UIQA Reply all paginated")) saves.push(body)
  })
  await page.goto("/dashboard/communications?tab=inbox")
  await page.getByLabel("Recherche", { exact: true }).fill("UIQA Native reply")
  await page.getByRole("button", { name: "Rechercher", exact: true }).click()
  await page.locator("button[data-selected]").filter({ hasText: "UIQA Native reply" }).click()
  await page.getByRole("button", { name: "Répondre", exact: true }).click()
  await expect(page.getByLabel("Destinataire", { exact: true })).toHaveValue("cuiqarecipient000000000550")
  await page.getByLabel("Objet", { exact: true }).fill(previousSubject)
  await page.getByLabel("CC", { exact: true }).fill("previous-copy@example.test")
  await page.getByLabel("CCI", { exact: true }).fill("previous-hidden@example.test")
  const chooser = page.waitForEvent("filechooser")
  await page.getByRole("button", { name: "Joindre un fichier", exact: true }).click()
  await (await chooser).setFiles({ name: "previous-fiction.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-fictional predecessor only") })
  await expect(page.getByRole("button", { name: "Retirer previous-fiction.pdf", exact: true })).toBeVisible()
  await page.getByRole("tab", { name: "Boîte de réception" }).click()
  if (testInfo.project.name === "mobile") await page.getByRole("button", { name: "Retour aux conversations", exact: true }).click()
  await page.getByLabel("Recherche", { exact: true }).fill("UIQA Reply all paginated")
  await page.getByRole("button", { name: "Rechercher", exact: true }).click()
  await page.locator("button[data-selected]").filter({ hasText: "UIQA Reply all paginated" }).click()
  await page.getByRole("button", { name: "Messages précédents", exact: true }).click()
  const original = page.locator("article").filter({ has: page.getByText("Incoming copies outside the displayed page", { exact: true }) })
  await expect(original).toBeVisible()
  await original.getByRole("button", { name: "Transférer", exact: true }).click()
  await expect(page.getByLabel("Objet", { exact: true })).toHaveValue("Tr: UIQA Reply all paginated")
  await expect(page.getByLabel("Destinataire", { exact: true })).toHaveValue("")
  await expect(page.getByLabel("CC", { exact: true })).toHaveValue("")
  await expect(page.getByLabel("CCI", { exact: true })).toHaveValue("")
  await expect(page.getByLabel("Expéditeur", { exact: true })).not.toHaveValue("cuiqareplysecondmailbox00")
  await expect(page.getByRole("button", { name: "Retirer previous-fiction.pdf", exact: true })).toHaveCount(0)
  const body = page.getByLabel("Contenu HTML", { exact: true })
  await expect(body).toHaveValue(/De : recipient550@example.test/)
  await expect(body).toHaveValue(/Date : 2020-01-01T00:00:00.000Z/)
  await expect(body).toHaveValue(/Incoming copies outside the displayed page/)
  await expect(body).not.toHaveValue(/Fictional outgoing|hidden@example.test|outgoing-only@example.test/)
  const quotedText = await body.inputValue()
  await expect(page.getByRole("status").filter({ hasText: "Brouillon enregistré" })).toBeVisible()
  expect(saves.length).toBeGreaterThan(0)
  expect(saves[0]).toContain('"threadId":""')
  expect(saves[0]).toContain('"contactId":""')
  expect(saves[0]).toContain('"attachmentIds":[]')
  await page.reload()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  const row = page.locator("div.border-b").filter({ has: page.getByText("Tr: UIQA Reply all paginated", { exact: true }) })
  await row.getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(body).toHaveValue(quotedText)
  await expect(page.getByLabel("Destinataire", { exact: true })).toHaveValue("")
  await expect(page.getByLabel("CC", { exact: true })).toHaveValue("")
  await expect(page.getByLabel("CCI", { exact: true })).toHaveValue("")
  await page.getByLabel("Rechercher un destinataire").fill("recipient550@example.test")
  await expect(page.getByLabel("Destinataire", { exact: true }).locator("option")).toHaveCount(2)
  await page.getByLabel("Destinataire", { exact: true }).selectOption("cuiqarecipient000000000550")
  await expect(page.getByRole("button", { name: "Envoyer maintenant", exact: true })).toBeEnabled()
  await expect(page.getByText("E-mail envoyé et ajouté à l’historique.", { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await page.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  for (const subject of ["Tr: UIQA Reply all paginated", previousSubject]) {
    const draft = page.locator("div.border-b").filter({ has: page.getByText(subject, { exact: true }) })
    await draft.getByRole("button", { name: "Supprimer", exact: true }).click()
    await page.getByRole("dialog", { name: "Supprimer ce brouillon ?" }).getByRole("button", { name: "Supprimer", exact: true }).click()
    await expect(page.getByText(subject, { exact: true })).toHaveCount(0)
  }
})
