import { expect, test } from "@playwright/test"

test("finds all recipients and preserves the choice across search and pages", async ({ page }) => {
  await page.goto("/dashboard/communications?tab=compose")
  const search = page.getByLabel("Rechercher un destinataire")
  const recipient = page.getByLabel("Destinataire", { exact: true })
  const picker = search.locator("xpath=..")
  await search.fill("UIQA Recipient")
  await expect(picker.getByRole("status")).toHaveText("551 résultats")
  await expect(recipient.locator("option")).toHaveCount(26)
  await picker.getByRole("button", { name: "Page suivante", exact: true }).click()
  await expect(picker.getByText("Page 2 sur 23", { exact: true })).toBeVisible()
  await search.fill("recipient550@example.test")
  await expect(picker.getByRole("status")).toHaveText("1 résultat")
  await recipient.selectOption((await recipient.locator("option").filter({ hasText: "UIQA Recipient 550" }).getAttribute("value"))!)
  const selectedId = await recipient.inputValue()
  await search.fill("UIQA Recipient")
  await expect(picker.getByRole("status")).toHaveText("551 résultats")
  await expect(recipient).toHaveValue(selectedId)
  await picker.getByRole("button", { name: "Page suivante", exact: true }).click()
  await expect(picker.getByText("Page 2 sur 23", { exact: true })).toBeVisible()
  await expect(recipient).toHaveValue(selectedId)
  let failOnce = true
  await page.route("**/dashboard/communications**", async route => {
    if (failOnce && route.request().method() === "POST" && route.request().postData()?.includes("recipient549@")) {
      failOnce = false
      await route.fulfill({ status: 500, body: "Isolated recipient lookup failure" })
    } else await route.continue()
  })
  await search.fill("recipient549@")
  await expect(picker.getByRole("alert")).toContainText("Impossible d’actualiser la liste.")
  await expect(recipient).toHaveValue(selectedId)
  await picker.getByRole("button", { name: "Réessayer", exact: true }).click()
  await expect(picker.getByRole("status")).toHaveText("1 résultat")
  await expect(picker.getByRole("alert")).toHaveCount(0)
  await expect(recipient).toHaveValue(selectedId)
  await page.unroute("**/dashboard/communications**")
  await search.fill("absent-fixture-recipient")
  await expect(picker.getByRole("status")).toHaveText("0 résultats")
  await expect(recipient).toHaveValue(selectedId)
  await expect(recipient.locator("option")).toHaveCount(2)
  await search.press("Enter")
  await expect(page.getByLabel("Objet", { exact: true })).toBeVisible()
  await expect(recipient).toHaveValue(selectedId)
  const main = page.locator("#dashboard-main")
  expect(await main.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
})
