import { expect, test } from "@playwright/test"

test("replies using the conversation mailbox and refuses a disconnected mailbox", async ({ page }, testInfo) => {
  await page.goto("/dashboard/communications?tab=compose")
  const sender = page.getByLabel("Expéditeur", { exact: true })
  await sender.selectOption("cuiqareplysecondmailbox00")
  await page.getByRole("tab", { name: "Boîte de réception" }).click()
  const search = page.getByLabel("Recherche", { exact: true })
  await search.fill("UIQA Native reply")
  await page.getByRole("button", { name: "Rechercher", exact: true }).click()
  await page.locator("button[data-selected]").filter({ hasText: "UIQA Native reply" }).click()
  await page.getByRole("button", { name: "Répondre", exact: true }).click()
  await expect(sender).not.toHaveValue("cuiqareplysecondmailbox00")
  await expect(page.getByLabel("Objet", { exact: true })).toHaveValue("Re: UIQA Native reply")
  await expect(page.getByLabel("Destinataire", { exact: true })).toHaveValue("cuiqarecipient000000000550")
  await page.getByRole("tab", { name: "Boîte de réception" }).click()
  if (testInfo.project.name === "mobile") await page.getByRole("button", { name: "Retour aux conversations", exact: true }).click()
  await search.fill("UIQA Disconnected reply")
  await page.getByRole("button", { name: "Rechercher", exact: true }).click()
  await page.locator("button[data-selected]").filter({ hasText: "UIQA Disconnected reply" }).click()
  await page.getByRole("button", { name: "Répondre", exact: true }).click()
  await expect(page.getByText("La boîte de cette conversation est déconnectée ou ne permet plus l’envoi ; reconnectez-la avant de répondre.", { exact: true })).toBeVisible()
  await expect(page.getByRole("tab", { name: "Boîte de réception" })).toHaveAttribute("aria-selected", "true")
})
