import { expect, test } from "@playwright/test"

test("selects a current quote revision, refuses an edit at the same version and retains its generated private copy", async ({ page, context }, testInfo) => {
  const subject = `UIQA quote copy ${testInfo.project.name} ${Date.now()}`
  const quoteId = "cuiqacrmquote000000000030"
  await page.goto("/dashboard/communications?tab=compose")
  await page.getByLabel("Rechercher un destinataire").fill("recipient550@example.test")
  await expect(page.getByLabel("Destinataire", { exact: true }).locator("option")).toHaveCount(2)
  await page.getByLabel("Destinataire", { exact: true }).selectOption("cuiqarecipient000000000550")
  await page.getByLabel("Objet", { exact: true }).fill(subject)
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Preserved fictional current quote mail</p>")
  await page.getByRole("button", { name: "Joindre un document CRM", exact: true }).click()
  const picker = page.getByRole("dialog", { name: "Joindre un document CRM", exact: true })
  await expect(picker.getByLabel("Source du document").locator('option[value="QUOTE_COPY"]')).toBeEnabled()
  await picker.getByLabel("Source du document").selectOption("QUOTE_COPY")
  await expect(picker.getByText("PDF généré depuis la version et les coordonnées actuelles ; ce n’est pas une archive de l’envoi d’origine.", { exact: true })).toBeVisible()
  await picker.getByLabel("Rechercher un document").fill("UIQA-CRM-QUOTE")
  await expect(picker.getByText("31 document(s) · Page 1 sur 2", { exact: true })).toBeVisible()
  await picker.getByRole("button", { name: "Page suivante", exact: true }).click()
  await expect(picker.getByText("31 document(s) · Page 2 sur 2", { exact: true })).toBeVisible()
  await picker.getByLabel("Rechercher un document").fill("UIQA-CRM-QUOTE-030")
  await expect(picker.getByLabel("Document CRM", { exact: true }).locator("option")).toHaveCount(2)
  await expect(picker.getByLabel("Document CRM", { exact: true }).locator(`option[value="${quoteId}"]`)).toContainText("version 1 · modifié le")
  await picker.getByLabel("Document CRM", { exact: true }).selectOption(quoteId)
  const editor = await context.newPage()
  try {
    await editor.goto(`/dashboard/devis/${quoteId}/edit`)
    await editor.getByLabel("Objet *", { exact: true }).fill(`Revised current quote ${subject}`)
    await editor.getByRole("button", { name: "Enregistrer", exact: true }).click()
    await expect(editor).toHaveURL(new RegExp(`/dashboard/devis/${quoteId}$`))
  } finally { await editor.close() }
  await picker.getByRole("button", { name: "Ajouter au brouillon", exact: true }).click()
  await expect(picker.getByRole("status")).toContainText("modifiés")
  await picker.getByRole("button", { name: "Annuler", exact: true }).click()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Preserved fictional current quote mail</p>")
  await page.getByRole("button", { name: "Joindre un document CRM", exact: true }).click()
  await expect(picker.getByLabel("Source du document").locator('option[value="QUOTE_COPY"]')).toBeEnabled()
  await picker.getByLabel("Source du document").selectOption("QUOTE_COPY")
  await picker.getByLabel("Rechercher un document").fill("UIQA-CRM-QUOTE-030")
  await expect(picker.getByLabel("Document CRM", { exact: true }).locator("option")).toHaveCount(2)
  await picker.getByLabel("Document CRM", { exact: true }).selectOption(quoteId)
  await picker.getByRole("button", { name: "Ajouter au brouillon", exact: true }).click()
  await expect(picker).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Retirer UIQA-CRM-QUOTE-030-v1-copie.pdf", exact: true })).toBeVisible()
  await page.reload(); await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  const row = page.locator("div.border-b").filter({ has: page.getByText(subject, { exact: true }) })
  await row.getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(page.getByRole("button", { name: "Retirer UIQA-CRM-QUOTE-030-v1-copie.pdf", exact: true })).toBeVisible()
  await expect(page.getByText("E-mail envoyé et ajouté à l’historique.", { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await page.getByRole("button", { name: "Retirer UIQA-CRM-QUOTE-030-v1-copie.pdf", exact: true }).click()
  await expect(page.getByRole("button", { name: "Retirer UIQA-CRM-QUOTE-030-v1-copie.pdf", exact: true })).toHaveCount(0)
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row.getByRole("button", { name: "Supprimer", exact: true }).click()
  await page.getByRole("dialog", { name: "Supprimer ce brouillon ?" }).getByRole("button", { name: "Supprimer", exact: true }).click()
})
