import { expect, test } from "@playwright/test"

test("saves incomplete private drafts, reopens copies and preserves text after a version conflict", async ({ page, context }, testInfo) => {
  const subject = `UIQA Private draft ${testInfo.project.name} ${Date.now()}`
  await page.goto("/dashboard/communications?tab=compose")
  await page.getByLabel("Objet", { exact: true }).fill(subject)
  await page.getByLabel("CC", { exact: true }).fill("copy@example.test")
  await page.getByLabel("CCI", { exact: true }).fill("hidden@example.test")
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Fictional private draft</p>")
  await page.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Brouillon enregistré" })).toContainText("version 1")
  await page.reload()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  const row = page.locator("div.border-b").filter({ has: page.getByText(subject, { exact: true }) })
  await row.getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(page.getByLabel("CCI", { exact: true })).toHaveValue("hidden@example.test")
  await expect(page.getByLabel("CC", { exact: true })).toHaveValue("copy@example.test")
  const other = await context.newPage()
  await other.goto("/dashboard/communications?tab=drafts")
  await other.locator("div.border-b").filter({ has: other.getByText(subject, { exact: true }) }).getByRole("button", { name: "Rouvrir", exact: true }).click()
  await other.getByLabel("Contenu HTML", { exact: true }).fill("<p>Newer saved version</p>")
  await other.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await expect(other.getByRole("status").filter({ hasText: "Brouillon enregistré" })).toContainText("version 2")
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Keep this unsaved text</p>")
  await page.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Conflit" })).toBeVisible()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Keep this unsaved text</p>")
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row.getByRole("button", { name: "Rouvrir", exact: true }).click()
  const replacement = page.getByRole("dialog", { name: "Remplacer les modifications non enregistrées ?" })
  await expect(replacement).toBeVisible()
  await replacement.getByRole("button", { name: "Annuler", exact: true }).click()
  await page.getByRole("tab", { name: "Nouvel e-mail", exact: true }).click()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Keep this unsaved text</p>")
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row.getByRole("button", { name: "Rouvrir", exact: true }).click()
  await replacement.getByRole("button", { name: "Remplacer", exact: true }).click()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Newer saved version</p>")
  await other.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await other.locator("div.border-b").filter({ has: other.getByText(subject, { exact: true }) }).getByRole("button", { name: "Supprimer", exact: true }).click()
  await other.getByRole("dialog", { name: "Supprimer ce brouillon ?" }).getByRole("button", { name: "Supprimer", exact: true }).click()
  await expect(other.getByText(subject, { exact: true })).toHaveCount(0)
  await other.close()
})
