import { expect, test, type Page } from "@playwright/test"

function row(page: Page, subject: string) { return page.locator("div.border-b").filter({ has: page.getByText(subject, { exact: true }) }) }
async function recipient(page: Page, index: number) {
  await page.getByLabel("Rechercher un destinataire").fill(`recipient${index}@example.test`)
  await expect(page.getByLabel("Destinataire", { exact: true }).locator("option")).toHaveCount(2)
  await page.getByLabel("Destinataire", { exact: true }).selectOption(`cuiqarecipient${String(index).padStart(12, "0")}`)
}
async function remove(page: Page, subject: string) {
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row(page, subject).getByRole("button", { name: "Supprimer", exact: true }).click()
  await page.getByRole("dialog", { name: "Supprimer ce brouillon ?" }).getByRole("button", { name: "Supprimer", exact: true }).click()
  await expect(page.getByText(subject, { exact: true })).toHaveCount(0)
}

test("preserves explicit marketing purpose through autosave, personal preview, scheduling and cancellation", async ({ page }, info) => {
  const subject = `UIQA Purpose ${info.project.name} ${Date.now()}`
  await page.goto("/dashboard/communications?tab=compose")
  await recipient(page, 549)
  await page.getByLabel("Objet", { exact: true }).fill(subject)
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Fictional marketing purpose content</p>")
  await page.getByLabel("CC", { exact: true }).fill("copy@example.test")
  await page.getByLabel("Finalité", { exact: true }).selectOption("MARKETING")
  await expect(page.getByLabel("Finalité", { exact: true })).toHaveValue("SERVICE")
  await expect(page.getByLabel("CC", { exact: true })).toHaveValue("copy@example.test")
  await page.getByLabel("CC", { exact: true }).fill("")
  const savedMarketing = page.waitForResponse(response => response.request().method() === "POST" && Boolean(response.request().postData()?.includes(subject) && response.request().postData()?.includes('"purpose":"MARKETING"')))
  await page.getByLabel("Finalité", { exact: true }).selectOption("MARKETING")
  await expect(page.getByLabel("CC", { exact: true })).toBeDisabled()
  await expect(page.getByLabel("CCI", { exact: true })).toBeDisabled()
  expect((await savedMarketing).status()).toBe(200)
  await expect(page.getByRole("status").filter({ hasText: "Brouillon enregistré" })).toBeVisible()
  await page.reload()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await expect(row(page, subject)).toContainText("Prospection")
  await row(page, subject).getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(page.getByLabel("Finalité", { exact: true })).toHaveValue("MARKETING")
  await page.getByRole("button", { name: "Vérifier l’aperçu", exact: true }).click()
  const preview = page.getByRole("dialog", { name: "Aperçu avant envoi" })
  await expect(preview).toContainText("Prospection")
  await expect(page.frameLocator('iframe[title="Aperçu final"]').getByRole("link", { name: "Se désinscrire" })).toHaveAttribute("href", /\/consent\/withdraw\//)
  await preview.getByRole("button", { name: "Version texte", exact: true }).click()
  await expect(preview.getByRole("region", { name: "Version texte de l’e-mail" })).toContainText("Se désinscrire")
  await page.keyboard.press("Escape")
  await page.getByLabel("Date et heure d’envoi", { exact: true }).fill(new Date(Date.now() + 86_400_000).toISOString().slice(0, 16))
  await page.getByLabel("Fuseau horaire", { exact: true }).fill("UTC")
  await page.getByRole("button", { name: "Programmer", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Envoi programmé" })).toBeVisible()
  await expect(page.getByLabel("Finalité", { exact: true })).toBeDisabled()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row(page, subject).getByRole("button", { name: "Annuler la programmation", exact: true }).click()
  await row(page, subject).getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(page.getByLabel("Finalité", { exact: true })).toHaveValue("MARKETING")
  await expect(page.getByLabel("Finalité", { exact: true })).toBeEnabled()
  await page.getByLabel("Finalité", { exact: true }).selectOption("SERVICE")
  await expect(page.getByLabel("CC", { exact: true })).toBeEnabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await page.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Brouillon enregistré" })).toBeVisible()
  await remove(page, subject)
})

test("explains missing proof while preserving typing and requires a decision on historical drafts", async ({ page }, info) => {
  const subject = `UIQA Refused purpose ${info.project.name} ${Date.now()}`
  await page.goto("/dashboard/communications?tab=compose")
  await recipient(page, 550)
  await page.getByLabel("Objet", { exact: true }).fill(subject)
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Keep this refused fictional composition</p>")
  await page.getByLabel("Finalité", { exact: true }).selectOption("MARKETING")
  await page.getByRole("button", { name: "Vérifier l’aperçu", exact: true }).click()
  await expect(page.getByText(/Prospection refusée : aucune preuve de consentement/)).toBeVisible()
  await expect(page.getByRole("dialog", { name: "Aperçu avant envoi" })).toHaveCount(0)
  await page.getByRole("button", { name: "Envoyer maintenant", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "preuve de consentement" })).toBeVisible()
  // A complete debounce period must not replace a refused send with saved success.
  await page.waitForTimeout(1200)
  await expect(page.getByRole("status").filter({ hasText: "preuve de consentement" })).toBeVisible()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Keep this refused fictional composition</p>")
  await expect(page.getByText("E-mail envoyé et ajouté à l’historique.", { exact: true })).toHaveCount(0)
  await remove(page, subject)
  await row(page, `UIQA Historical purpose ${info.project.name}`).getByRole("button", { name: "Rouvrir", exact: true }).click()
  const confirmation = page.getByRole("dialog", { name: "Remplacer ce texte non enregistré ?" })
  await expect(confirmation).toBeVisible()
  await confirmation.getByRole("button", { name: "Remplacer", exact: true }).click()
  await expect(page.getByLabel("Finalité", { exact: true })).toHaveValue("")
  await expect(page.getByRole("button", { name: "Envoyer maintenant", exact: true })).toBeDisabled()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Historical fictional purpose remains unknown</p>")
})
