import { expect, test, type Page } from "@playwright/test"

function row(page: Page, subject: string) { return page.locator("div.border-b").filter({ has: page.getByText(subject, { exact: true }) }) }
async function chooseRecipient(page: Page) {
  await page.getByLabel("Rechercher un destinataire").fill("recipient550@example.test")
  await expect(page.getByLabel("Destinataire", { exact: true }).locator("option")).toHaveCount(2)
  await page.getByLabel("Destinataire", { exact: true }).selectOption("cuiqarecipient000000000550")
}
async function deleteDraft(page: Page, subject: string) {
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row(page, subject).getByRole("button", { name: "Supprimer", exact: true }).click()
  await page.getByRole("dialog", { name: "Supprimer ce brouillon ?" }).getByRole("button", { name: "Supprimer", exact: true }).click()
  await expect(page.getByText(subject, { exact: true })).toHaveCount(0)
}

test("schedules the latest private draft with files, freezes it across reload and makes it editable after cancellation", async ({ page }, testInfo) => {
  const subject = `UIQA Scheduled ${testInfo.project.name} ${Date.now()}`
  const localTime = new Date(Date.now() + 86_400_000).toISOString().slice(0, 16)
  await page.goto("/dashboard/communications?tab=compose")
  await chooseRecipient(page)
  await page.getByLabel("Objet", { exact: true }).fill(subject)
  await page.getByLabel("CC", { exact: true }).fill("copy@example.test")
  await page.getByLabel("CCI", { exact: true }).fill("hidden@example.test")
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Fictional latest scheduled content</p>")
  await page.getByLabel("Date et heure d’envoi", { exact: true }).fill(localTime)
  await page.getByLabel("Fuseau horaire", { exact: true }).fill("UTC")
  const chooser = page.waitForEvent("filechooser")
  await page.getByRole("button", { name: "Joindre un fichier", exact: true }).click()
  await (await chooser).setFiles({ name: "scheduled-fiction.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-fictional scheduled attachment") })
  await expect(page.getByRole("button", { name: "Retirer scheduled-fiction.pdf", exact: true })).toBeVisible()
  await expect(page.getByLabel("Date et heure d’envoi", { exact: true })).toHaveValue(localTime)
  await page.getByRole("button", { name: "Programmer", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Envoi programmé" })).toBeVisible()
  await expect(page.getByLabel("Objet", { exact: true })).toBeDisabled()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toBeDisabled()
  await expect(page.getByRole("button", { name: "Envoyer maintenant", exact: true })).toBeDisabled()
  await expect(page.getByRole("button", { name: "Enregistrer le brouillon", exact: true })).toBeDisabled()
  await expect(page.getByRole("button", { name: "Retirer scheduled-fiction.pdf", exact: true })).toBeDisabled()
  await expect(page.getByRole("button", { name: "Vérifier l’aperçu", exact: true })).toBeEnabled()
  await page.reload()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await expect(row(page, subject)).toContainText("Programmé")
  await expect(row(page, subject)).toContainText("UTC")
  await row(page, subject).getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Fictional latest scheduled content</p>")
  await expect(page.getByLabel("CC", { exact: true })).toHaveValue("copy@example.test")
  await expect(page.getByLabel("CCI", { exact: true })).toHaveValue("hidden@example.test")
  await expect(page.getByLabel("Date et heure d’envoi", { exact: true })).toHaveValue(localTime)
  await expect(page.getByLabel("Fuseau horaire", { exact: true })).toHaveValue("UTC")
  await expect(page.getByLabel("Objet", { exact: true })).toBeDisabled()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await row(page, subject).getByRole("button", { name: "Annuler la programmation", exact: true }).click()
  await expect(row(page, subject).getByRole("button", { name: "Annuler la programmation", exact: true })).toHaveCount(0)
  await row(page, subject).getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(page.getByLabel("Date et heure d’envoi", { exact: true })).toHaveValue("")
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toBeEnabled()
  await expect(page.getByRole("button", { name: "Retirer scheduled-fiction.pdf", exact: true })).toBeEnabled()
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Editable after cancellation</p>")
  await page.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Brouillon enregistré" })).toBeVisible()
  await expect(page.getByText("E-mail envoyé et ajouté à l’historique.", { exact: true })).toHaveCount(0)
  await deleteDraft(page, subject)
})

test("preserves stale-tab typing when another tab schedules, then reopens the frozen server revision", async ({ page, context }, testInfo) => {
  const subject = `UIQA Schedule conflict ${testInfo.project.name} ${Date.now()}`
  const localTime = new Date(Date.now() + 86_400_000).toISOString().slice(0, 16)
  await page.goto("/dashboard/communications?tab=compose")
  await chooseRecipient(page)
  await page.getByLabel("Objet", { exact: true }).fill(subject)
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Frozen scheduling revision</p>")
  await page.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Brouillon enregistré" })).toBeVisible()
  const other = await context.newPage()
  await other.goto("/dashboard/communications?tab=drafts")
  await row(other, subject).getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(other.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Frozen scheduling revision</p>")
  await page.getByLabel("Date et heure d’envoi", { exact: true }).fill(localTime)
  await page.getByLabel("Fuseau horaire", { exact: true }).fill("UTC")
  await page.getByRole("button", { name: "Programmer", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Envoi programmé" })).toBeVisible()
  await other.getByLabel("Contenu HTML", { exact: true }).fill("<p>Keep my stale-tab typing</p>")
  await other.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await expect(other.getByRole("status").filter({ hasText: "Conflit" })).toBeVisible()
  await expect(other.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Keep my stale-tab typing</p>")
  await other.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row(other, subject).getByRole("button", { name: "Rouvrir", exact: true }).click()
  await other.getByRole("dialog", { name: "Remplacer les modifications non enregistrées ?" }).getByRole("button", { name: "Remplacer", exact: true }).click()
  await expect(other.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Frozen scheduling revision</p>")
  await expect(other.getByLabel("Contenu HTML", { exact: true })).toBeDisabled()
  await other.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row(other, subject).getByRole("button", { name: "Annuler la programmation", exact: true }).click()
  await expect(row(other, subject).getByRole("button", { name: "Annuler la programmation", exact: true })).toHaveCount(0)
  await deleteDraft(other, subject)
  await other.close()
})
