import { expect, test } from "@playwright/test"

test("inserts a saved personal signature on request, preserves old drafts and previews the plain alternative", async ({ page, context }, testInfo) => {
  const subject = `UIQA Signature ${testInfo.project.name} ${Date.now()}`
  const body = '<p>Bonjour &eacute;quipe.</p><a href="https://example.test/?a=1&amp;b=2" rel="noopener noreferrer">Dossier</a>'
  const signature = 'Équipe <img src=x onerror=alert(1)> & "Fiction"\nLigne privée'
  await page.goto("/dashboard/communications?tab=compose")
  await page.getByLabel("Objet", { exact: true }).fill(subject)
  await page.getByLabel("Contenu HTML", { exact: true }).fill(body)
  await page.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Brouillon enregistré" })).toContainText("version 1")
  await page.getByLabel("Signature personnelle", { exact: true }).fill(signature)
  await page.getByRole("button", { name: "Enregistrer ma signature", exact: true }).click()
  await expect(page.getByText("Signature personnelle enregistrée.").last()).toBeVisible()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue(body)
  await page.getByRole("button", { name: "Vérifier l’aperçu", exact: true }).click()
  const preview = page.getByRole("dialog", { name: "Aperçu avant envoi", exact: true })
  await preview.getByRole("button", { name: "Version texte", exact: true }).click()
  await expect(preview.getByRole("region", { name: "Version texte de l’e-mail" })).toContainText("Bonjour équipe.")
  await expect(preview.getByRole("region", { name: "Version texte de l’e-mail" })).not.toContainText("Ligne privée")
  await page.keyboard.press("Escape")
  await page.getByRole("button", { name: "Insérer ma signature", exact: true }).click()
  const inserted = await page.getByLabel("Contenu HTML", { exact: true }).inputValue()
  expect(inserted.startsWith(body)).toBe(true)
  expect(inserted).toContain("&lt;img"); expect(inserted).not.toContain("<img")
  await page.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "Brouillon enregistré" })).toContainText("version 2")
  const other = await context.newPage()
  await other.goto("/dashboard/communications?tab=compose")
  await expect(other.getByLabel("Signature personnelle", { exact: true })).toHaveValue(signature)
  await page.getByLabel("Signature personnelle", { exact: true }).fill("Nouvelle signature fictive")
  await page.getByRole("button", { name: "Enregistrer ma signature", exact: true }).click()
  await expect(page.getByText("Signature personnelle enregistrée.").last()).toBeVisible()
  await other.getByLabel("Signature personnelle", { exact: true }).fill("Conserver cette saisie concurrente")
  await other.getByRole("button", { name: "Enregistrer ma signature", exact: true }).click()
  await expect(other.getByText(/Cette signature a changé dans un autre onglet/)).toBeVisible()
  await expect(other.getByLabel("Signature personnelle", { exact: true })).toHaveValue("Conserver cette saisie concurrente")
  await other.reload()
  await expect(other.getByLabel("Signature personnelle", { exact: true })).toHaveValue("Nouvelle signature fictive")
  await other.close()
  await page.reload()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  const row = page.locator("div.border-b").filter({ has: page.getByText(subject, { exact: true }) })
  await row.getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue(inserted)
  await page.getByRole("button", { name: "Vérifier l’aperçu", exact: true }).click()
  await expect(preview.getByRole("button", { name: "Version texte", exact: true })).toHaveAttribute("aria-pressed", "false")
  await expect(page.frameLocator('iframe[title="Aperçu final"]').locator("img")).toHaveCount(0)
  await preview.getByRole("button", { name: "Version texte", exact: true }).click()
  const text = preview.getByRole("region", { name: "Version texte de l’e-mail" })
  await expect(text).toContainText(signature)
  await expect(text).toContainText("Dossier [https://example.test/?a=1&b=2]")
  await expect(text).not.toContainText("Nouvelle signature fictive")
  await page.keyboard.press("Escape")
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row.getByRole("button", { name: "Supprimer", exact: true }).click()
  await page.getByRole("dialog", { name: "Supprimer ce brouillon ?" }).getByRole("button", { name: "Supprimer", exact: true }).click()
  await expect(page.getByText(subject, { exact: true })).toHaveCount(0)
})
