import { expect, test } from "@playwright/test"

test("prepares all visible incoming recipients beyond the message page, keeps copies editable and leaves send manual", async ({ page }) => {
  await page.goto("/dashboard/communications?tab=inbox")
  await page.getByLabel("Recherche", { exact: true }).fill("UIQA Reply all paginated")
  await page.getByRole("button", { name: "Rechercher", exact: true }).click()
  await page.locator("button[data-selected]").filter({ hasText: "UIQA Reply all paginated" }).click()
  await expect(page.getByText("Incoming copies outside the displayed page", { exact: true })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Messages précédents", exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await page.getByRole("button", { name: "Répondre à tous", exact: true }).click()
  await expect(page.getByLabel("Objet", { exact: true })).toHaveValue("Re: UIQA Reply all paginated")
  await expect(page.getByLabel("Destinataire", { exact: true })).toHaveValue("cuiqarecipient000000000550")
  await expect(page.getByLabel("Expéditeur", { exact: true })).not.toHaveValue("cuiqareplysecondmailbox00")
  await expect(page.getByLabel("CC", { exact: true })).toHaveValue("copy@example.test, other@example.test")
  await expect(page.getByLabel("CCI", { exact: true })).toHaveValue("")
  await expect(page.getByRole("tab", { name: "Nouvel e-mail", exact: true })).toHaveAttribute("aria-selected", "true")
  await page.getByLabel("CC", { exact: true }).fill("chosen@example.test")
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Fictional editable reply-all draft</p>")
  await expect(page.getByRole("status").filter({ hasText: "Brouillon enregistré" })).toContainText("version 1")
  await expect(page.getByRole("button", { name: "Envoyer maintenant", exact: true })).toBeEnabled()
  await expect(page.getByText("E-mail envoyé et ajouté à l’historique.", { exact: true })).toHaveCount(0)
  await page.reload()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  const row = page.locator("div.border-b").filter({ has: page.getByText("Re: UIQA Reply all paginated", { exact: true }) })
  await row.getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(page.getByLabel("CC", { exact: true })).toHaveValue("chosen@example.test")
  await expect(page.getByLabel("CCI", { exact: true })).toHaveValue("")
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row.getByRole("button", { name: "Supprimer", exact: true }).click()
  await page.getByRole("dialog", { name: "Supprimer ce brouillon ?" }).getByRole("button", { name: "Supprimer", exact: true }).click()
  await expect(page.getByText("Re: UIQA Reply all paginated", { exact: true })).toHaveCount(0)
})
