import { expect, test } from "@playwright/test"

test("paginates and searches recipient CRM files, privately retains a file and archived invoice after reload, and leaves send manual", async ({ page }, testInfo) => {
  const subject = `UIQA CRM attachments ${testInfo.project.name} ${Date.now()}`
  await page.goto("/dashboard/communications?tab=compose")
  await expect(page.getByRole("button", { name: "Joindre un document CRM", exact: true })).toBeDisabled()
  await page.getByLabel("Rechercher un destinataire").fill("recipient550@example.test")
  await expect(page.getByLabel("Destinataire", { exact: true }).locator("option")).toHaveCount(2)
  await page.getByLabel("Destinataire", { exact: true }).selectOption("cuiqarecipient000000000550")
  await page.getByLabel("Objet", { exact: true }).fill(subject)
  await page.getByLabel("Contenu HTML", { exact: true }).fill("<p>Fictional CRM document composition</p>")
  await page.getByRole("button", { name: "Joindre un document CRM", exact: true }).click()
  const picker = page.getByRole("dialog", { name: "Joindre un document CRM", exact: true })
  await expect(picker.getByLabel("Document CRM", { exact: true }).locator("option")).toHaveCount(26)
  await picker.getByRole("button", { name: "Page suivante", exact: true }).click()
  await expect(picker.getByText("31 document(s) · Page 2 sur 2", { exact: true })).toBeVisible()
  await picker.getByLabel("Rechercher un document", { exact: true }).fill("document 030")
  await expect(picker.getByLabel("Document CRM", { exact: true }).locator("option")).toHaveCount(2)
  await picker.getByLabel("Document CRM", { exact: true }).selectOption("cuiqacrmfile00000000000030")
  await picker.getByRole("button", { name: "Ajouter au brouillon", exact: true }).click()
  await expect(picker).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Retirer UIQA CRM Document 030.pdf", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Joindre un document CRM", exact: true }).click()
  await expect(picker.getByLabel("Source du document", { exact: true }).locator('option[value="ISSUED_INVOICE"]')).toBeEnabled()
  await picker.getByLabel("Source du document", { exact: true }).selectOption("ISSUED_INVOICE")
  await expect(picker.getByLabel("Document CRM", { exact: true }).locator("option")).toHaveCount(2)
  await picker.getByLabel("Document CRM", { exact: true }).selectOption("cuiqacrminvoicearchive000")
  await picker.getByRole("button", { name: "Ajouter au brouillon", exact: true }).click()
  await expect(page.getByRole("button", { name: "Retirer UIQA-CRM-ARCHIVE.pdf", exact: true })).toBeVisible()
  await expect(page.getByLabel("Contenu HTML", { exact: true })).toHaveValue("<p>Fictional CRM document composition</p>")
  await page.reload()
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  const row = page.locator("div.border-b").filter({ has: page.getByText(subject, { exact: true }) })
  await row.getByRole("button", { name: "Rouvrir", exact: true }).click()
  await expect(page.getByRole("button", { name: "Retirer UIQA CRM Document 030.pdf", exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: "Retirer UIQA-CRM-ARCHIVE.pdf", exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await page.getByRole("button", { name: "Retirer UIQA CRM Document 030.pdf", exact: true }).click()
  await expect(page.getByRole("button", { name: "Retirer UIQA CRM Document 030.pdf", exact: true })).toHaveCount(0)
  await expect(page.getByText("E-mail envoyé et ajouté à l’historique.", { exact: true })).toHaveCount(0)
  await page.getByRole("tab", { name: "Brouillons", exact: true }).click()
  await row.getByRole("button", { name: "Supprimer", exact: true }).click()
  await page.getByRole("dialog", { name: "Supprimer ce brouillon ?" }).getByRole("button", { name: "Supprimer", exact: true }).click()
})
