import { createHash } from "node:crypto"
import { expect, test, type Page } from "@playwright/test"

async function prepareSignature(page: Page) {
  await page.getByLabel("Nom complet du signataire").fill("Fictional archive signer")
  await page.getByLabel("Adresse email de validation").fill("recette0@example.test")
  const canvas = page.locator("canvas")
  await canvas.scrollIntoViewIfNeeded()
  const box = await canvas.boundingBox()
  expect(box).not.toBeNull()
  await page.mouse.move(box!.x + 20, box!.y + 40)
  await page.mouse.down()
  await page.mouse.move(box!.x + 80, box!.y + 80, { steps: 8 })
  await page.mouse.move(box!.x + 140, box!.y + 30, { steps: 8 })
  await page.mouse.up()
  await page.getByLabel(/Je déclare avoir lu/).check()
  await page.getByLabel(/J'accepte d'apposer ma signature électronique/).check()
}

test("rejects a stale signing page, renews its capture and durably archives the signed PDF", async ({ page, context }, testInfo) => {
  const secret = process.env.SCHEDULER_CRON_SECRET
  expect(secret, "The isolated recipe must configure its fictitious scheduler secret").toBeTruthy()
  const id = `cuiqacontractfreeze${testInfo.project.name}`
  const title = `Fictional revised agreement ${testInfo.project.name}`
  await page.goto(`/dashboard/contrats/${id}`)
  await page.getByRole("button", { name: "Actions", exact: true }).click()
  await page.getByRole("menuitem", { name: "Envoyer pour signature" }).click()
  const dialog = page.getByRole("dialog", { name: "Invitation de signature prête" })
  const oldUrl = await dialog.getByLabel("Lien de signature à partager").inputValue()
  await dialog.getByRole("button", { name: "Fermer", exact: true }).click()
  const signing = await context.newPage()
  await signing.goto(oldUrl)
  await expect(signing.getByText("Fictional signing capture", { exact: true })).toBeVisible()
  await prepareSignature(signing)
  await page.goto(`/dashboard/contrats/${id}/edit`)
  await page.getByLabel("Titre juridique du contrat").fill(title)
  await page.getByRole("button", { name: "Enregistrer", exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/dashboard/contrats/${id}$`))
  await signing.getByRole("button", { name: "Signer électroniquement" }).click()
  await expect(signing.getByText(/demandez un nouveau lien de signature/)).toBeVisible()
  await expect(signing.getByLabel("Nom complet du signataire")).toHaveValue("Fictional archive signer")
  await expect(signing.getByText("Contrat Signé avec Succès !", { exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "Actions", exact: true }).click()
  await page.getByRole("menuitem", { name: "Régénérer le lien" }).click()
  const newUrl = await dialog.getByLabel("Lien de signature à partager").inputValue()
  expect(newUrl).not.toBe(oldUrl)
  await dialog.getByRole("button", { name: "Fermer", exact: true }).click()
  expect((await page.request.get(oldUrl)).status()).toBe(404)
  await signing.goto(newUrl)
  await expect(signing.getByText(title, { exact: true })).toBeVisible()
  await prepareSignature(signing)
  await signing.getByRole("button", { name: "Signer électroniquement" }).click()
  await expect(signing.getByText("Contrat Signé avec Succès !", { exact: true })).toBeVisible()
  await expect(signing.getByText(/Son PDF archivé est en préparation/)).toBeVisible()
  const processed = await page.request.post("/api/scheduling/process", { headers: { authorization: `Bearer ${secret}` } })
  expect(processed.ok()).toBe(true)
  const archives = (await processed.json()).contractArchives
  expect(archives.failed).toBe(0)
  // The global cron also archives agreements signed by preceding critical flows.
  expect(archives.generated).toBeGreaterThanOrEqual(1)
  const pdf = await page.request.get(`/api/pdf/contrat/${id}`)
  expect(pdf.ok()).toBe(true)
  expect(pdf.headers()["content-type"]).toBe("application/pdf")
  const bytes = await pdf.body()
  expect(bytes.subarray(0, 5).toString()).toBe("%PDF-")
  const hash = createHash("sha256").update(bytes).digest("hex")
  const replay = await page.request.post("/api/scheduling/process", { headers: { authorization: `Bearer ${secret}` } })
  expect(replay.ok()).toBe(true)
  expect((await replay.json()).contractArchives).toMatchObject({ generated: 0, failed: 0 })
  expect(createHash("sha256").update(await (await page.request.get(`/api/pdf/contrat/${id}`)).body()).digest("hex")).toBe(hash)
  await page.goto("/dashboard/contrats/cuiqacontractsigned000000")
  await expect(page.getByText("Archive historique indisponible", { exact: true })).toBeVisible()
  const historical = await page.request.get("/api/pdf/contrat/cuiqacontractsigned000000")
  expect(historical.status()).toBe(409)
  expect(await historical.json()).toEqual({ error: "Archive historique indisponible" })
  await signing.close()
})
