import { expect, test, type Page } from "@playwright/test"
import { mkdir } from "node:fs/promises"
import os from "node:os"
import path from "node:path"

const QA_EMAIL = process.env.E2E_USER_EMAIL || "qa-crm@example.com"
const evidenceDir = path.join(os.tmpdir(), "crm-e2e-evidence")

async function login(page: Page) {
  await page.goto("/auth/login")
  await page.getByLabel("Adresse e-mail professionnelle").fill(QA_EMAIL)
  await page.getByRole("button", { name: "Se connecter" }).click()
  await page.waitForURL(/\/(dashboard|onboarding)/)
  if (page.url().includes("/onboarding")) await page.goto("/dashboard")
  await expect(page.getByRole("heading", { name: "Vue d’ensemble" })).toBeVisible()
}

async function assertHealthy(page: Page, pathName: string, heading: string) {
  await page.goto(pathName)
  await expect(page.getByRole("heading", { name: heading })).toBeVisible()
  await expect(page.locator("html[data-app-hydrated='true']")).toHaveCount(1)
  await expect(page.getByText("Erreur de chargement")).toHaveCount(0)
  await expect(page.getByText("Runtime Error")).toHaveCount(0)
  await expect(page.getByText("Console Error")).toHaveCount(0)
}

test.beforeEach(async ({ page }) => {
  const consoleErrors: string[] = []
  page.on("console", (message) => {
    if (message.type() === "error") consoleErrors.push(message.text())
  })
  await login(page)
  await expect(page.locator("html[data-app-hydrated='true']")).toHaveCount(1)
  ;(page as Page & { consoleErrors?: string[] }).consoleErrors = consoleErrors
})

test.afterEach(async ({ page }) => {
  const errors = (page as Page & { consoleErrors?: string[] }).consoleErrors ?? []
  expect(errors.filter((message) => !message.includes("favicon"))).toEqual([])
})

test("new local-first surfaces load and their primary controls respond", async ({ page }, testInfo) => {
  await mkdir(evidenceDir, { recursive: true })

  if (testInfo.project.name === "mobile") await page.getByRole("button", { name: "Ouvrir la navigation" }).click()
  await page.getByRole("button", { name: "Marketing", exact: true }).click()
  await expect(page.getByRole("link", { name: "Campagnes", exact: true })).toBeVisible()
  if (testInfo.project.name === "mobile") await page.locator("#mobile-dashboard-navigation").getByRole("button", { name: "Fermer la navigation" }).click()

  await page.goto("/")
  await expect(page.getByRole("heading", { name: "Freelio. Tout votre business freelance, enfin relié." })).toBeVisible()
  await expect(page.locator("#workflow")).toHaveCount(1)
  await expect(page.getByRole("link", { name: "Essayer gratuitement" }).first()).toBeVisible()
  await page.goto("/fonctionnalites")
  await expect(page.getByRole("heading", { name: "Un seul produit pour faire avancer toute la mission." })).toBeVisible()

  await assertHealthy(page, "/dashboard/factures/recurrentes", "Facturation récurrente")
  await page.getByRole("button", { name: "Nouvelle récurrence" }).click()
  await expect(page.getByRole("heading", { name: "Nouvelle récurrence" })).toBeVisible()
  await page.getByRole("button", { name: "Annuler" }).click()

  await assertHealthy(page, "/dashboard/comptabilite/banque", "Rapprochement bancaire")
  await page.locator('input[type="file"]').setInputFiles({
    name: "releve-test.csv",
    mimeType: "text/csv",
    buffer: Buffer.from("Date,Libellé,Montant,Reference\n06/07/2026,QA lecture CSV,42.50,QA-001\n"),
  })
  await expect(page.getByText("1 ligne(s) valide(s) sur 1")).toBeVisible()

  await assertHealthy(page, "/dashboard/organisation", "Organisation")
  await page.getByRole("button", { name: "Nouvelle tâche" }).click()
  await expect(page.getByRole("heading", { name: "Nouvelle tâche" })).toBeVisible()
  await page.getByLabel("Récurrence", { exact: true }).selectOption("WEEKLY")
  await expect(page.getByLabel("Tous les")).toBeEnabled()
  await page.getByRole("button", { name: "Annuler" }).click()

  await assertHealthy(page, "/dashboard/migrations", "Migration des données")
  await expect(page.getByText("Connecter une source")).toBeVisible()
  await expect(page.getByText("Déposer des exports")).toBeVisible()

  await assertHealthy(page, "/dashboard/terrain", "Terrain hors ligne")
  await expect(page.getByText("Interventions à exécuter")).toBeVisible()

  await assertHealthy(page, "/dashboard/clients", "Clients")
  if (testInfo.project.name === "desktop") {
    await page.getByPlaceholder("Rechercher un client…").fill("Client QA")
    await page.getByLabel("Enregistrer la vue actuelle").fill("Clients QA")
    await page.getByRole("button", { name: "Enregistrer la vue" }).click()
    await expect(page.getByText("Vue enregistrée.")).toBeVisible()
    await page.reload()
    await page.getByLabel("Vue enregistrée").selectOption({ label: "Clients QA" })
    await expect(page.getByPlaceholder("Rechercher un client…")).toHaveValue("Client QA")
  }
  const clientLink = page.locator('a[href^="/dashboard/clients/"]')
  expect(await clientLink.count()).toBeGreaterThan(0)
  await clientLink.first().click()
  await page.waitForURL(/\/dashboard\/clients\/[^/]+$/)
  await expect(page.getByText("Prochaine action")).toBeVisible()
  await page.getByRole("button", { name: "Ajouter", exact: true }).first().click()
  await expect(page.getByRole("heading", { name: "Nouveau contact" })).toBeVisible()
  await page.getByRole("button", { name: "Annuler" }).click()

  await assertHealthy(page, "/dashboard/crm", "Clients et relations")
  await assertHealthy(page, "/dashboard/contacts", "Contacts")
  await page.getByRole("link", { name: "Camille Piscine", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Camille Piscine" })).toBeVisible()
  await expect(page.getByText("Coordonnées et client")).toBeVisible()
  await assertHealthy(page, "/dashboard/sales", "Transformer les projets en commandes")
  await assertHealthy(page, "/dashboard/marketing/overview", "Acquisition et engagement")
  await assertHealthy(page, "/dashboard/service", "SAV et fidélisation")
  await assertHealthy(page, "/dashboard/service/help-desk", "Centre de support")
  await expect(page.getByText("Filtres de la file")).toBeVisible()
  await assertHealthy(page, "/dashboard/revenue", "Facturation et trésorerie")
  await assertHealthy(page, "/dashboard/data", "Qualité et gouvernance")
  await assertHealthy(page, "/dashboard/reports", "Piloter l’entreprise")

  await assertHealthy(page, "/dashboard/projets", "Projets")
  const projectLink = page.locator('a[href^="/dashboard/projets/"]')
  expect(await projectLink.count()).toBeGreaterThan(0)
  await projectLink.first().click()
  await page.waitForURL(/\/dashboard\/projets\/[^/]+$/)
  await expect(page.getByText("Relevé technique bassin & pose")).toBeVisible()
  await page.getByRole("button", { name: "Modifier" }).click()
  await expect(page.getByRole("heading", { name: "Relevé technique bassin & pose" })).toBeVisible()
  await page.getByLabel("État du relevé").selectOption("SURVEYED")
  await page.getByLabel("Date du relevé").fill("2026-08-23")
  await page.getByLabel("Technicien").fill("Technicien QA")
  await page.getByLabel("Forme").fill("Rectangle")
  await page.getByLabel("Longueur").fill("8000")
  await page.getByLabel("Largeur", { exact: true }).fill("4000")
  await page.getByRole("button", { name: "Enregistrer le relevé" }).click()
  await expect(page.getByText("Relevé technique enregistré.")).toBeVisible()
  await expect(page.getByText("8000 mm")).toBeVisible()

  await assertHealthy(page, "/dashboard/devis", "Devis")
  const quoteLinks = page.locator('a[href^="/dashboard/devis/"]:not([href$="/edit"]):not([href$="/new"])')
  expect(await quoteLinks.count()).toBeGreaterThan(0)
  const quoteHref = await quoteLinks.first().getAttribute("href")
  expect(quoteHref).toBeTruthy()
  await quoteLinks.first().click()
  await expect(page.getByText("Studio documentaire")).toBeVisible()
  await expect(page.getByText("Qualité", { exact: true })).toBeVisible()
  const quotePreview = await page.request.get(`${quoteHref?.replace("/dashboard", "/api/pdf")}?screen=1`)
  expect(quotePreview.ok()).toBeTruthy()
  expect(await quotePreview.text()).toContain("DOCTYPE html")

  await assertHealthy(page, "/dashboard/contrats", "Contrats")
  const contractLinks = page.locator('a[href^="/dashboard/contrats/"]:not([href$="/edit"]):not([href$="/new"]):not([href$="/sign"])')
  if ((await contractLinks.count()) > 0) {
    const contractHref = await contractLinks.first().getAttribute("href")
    expect(contractHref).toBeTruthy()
    await contractLinks.first().click()
    await expect(page.getByText("Qualité contractuelle")).toBeVisible()
    const contractPreview = await page.request.get(`${contractHref?.replace("/dashboard/contrats", "/api/pdf/contrat")}?screen=1`)
    expect(contractPreview.ok()).toBeTruthy()
    expect(await contractPreview.text()).toContain("Contrat")
  } else {
    testInfo.annotations.push({
      type: "note",
      description: "Aucun contrat local disponible pour tester le PDF contrat via E2E.",
    })
  }

  const ics = await page.request.get("/api/organisation/calendar.ics")
  expect(ics.ok()).toBeTruthy()
  expect(ics.headers()["content-type"]).toContain("text/calendar")

  const accountingExport = await page.request.get("/api/accounting/export")
  expect(accountingExport.ok()).toBeTruthy()
  expect(accountingExport.headers()["content-type"]).toContain("application/zip")
  expect((await accountingExport.body()).subarray(0, 2).toString("ascii")).toBe("PK")

  const reversibilityExport = await page.request.get("/api/backup/export")
  expect(reversibilityExport.ok()).toBeTruthy()
  const reversibility = await reversibilityExport.json()
  expect(reversibility.schema).toBe("crm.reversibility-export.v4")
  expect(reversibility.manifest.payloadSha256).toMatch(/^[a-f0-9]{64}$/)
  expect(JSON.stringify(reversibility)).not.toContain("credentialsEncrypted")
  expect(JSON.stringify(reversibility)).not.toContain('"secret"')

  const removedLanding = await page.request.get("/v2")
  expect(removedLanding.status()).toBe(404)

  await page.goto("/dashboard")
  await page.screenshot({ path: path.join(evidenceDir, `${testInfo.project.name}-dashboard.png`), fullPage: false })
})

test("pipeline scroll navigation replaces the horizontal scrollbar", async ({ page }, testInfo) => {
  await assertHealthy(page, "/dashboard/pipeline", "Pipeline")

  if (testInfo.project.name === "desktop") {
    await page.getByRole("button", { name: "Nouvelle Opportunité" }).click()
    await page.getByLabel("Titre").fill("Prévision commerciale QA")
    await page.getByLabel("Client").click()
    await page.getByRole("option", { name: "Client QA Piscine" }).click()
    await page.getByLabel("Valeur (€)").fill("10000")
    await page.getByLabel("Probabilité (%)").fill("40")
    await page.getByLabel("Responsable commercial").click()
    await page.getByRole("option", { name: "Utilisateur QA" }).click()
    const forecastDate = `${new Date().toISOString().slice(0, 7)}-28`
    await page.getByLabel("Clôture prévue").fill(forecastDate)
    await page.getByRole("button", { name: "Créer", exact: true }).click()
    await expect(page.getByText("Opportunité créée.")).toBeVisible()
    const forecastCard = page.locator("[data-slot=card]").filter({ hasText: "Prévision commerciale QA" })
    await expect(forecastCard).toContainText("Utilisateur QA")
    await expect(page.getByText("Prévu ce mois").locator("..")).toContainText("4 000 €")

    await forecastCard.getByRole("button", { name: "Ouvrir les actions de l’opportunité" }).click()
    await page.getByRole("menuitem", { name: "Marquer perdu avec un motif" }).click()
    await page.getByLabel("Motif de perte").fill("Budget reporté après arbitrage")
    await page.getByRole("button", { name: "Enregistrer" }).click()
    await expect(page.getByText("Opportunité mise à jour.")).toBeVisible()
    const lostCard = page.locator("[data-slot=card]").filter({ hasText: "Prévision commerciale QA" })
    await expect(lostCard).toContainText("Budget reporté après arbitrage")
    await lostCard.getByRole("button", { name: "Ouvrir les actions de l’opportunité" }).click()
    await page.getByRole("menuitem", { name: "Déplacer → Besoin qualifié" }).click()
    await expect(page.getByText("Étape mise à jour.")).toBeVisible()
    const reopenedCard = page.locator("[data-slot=card]").filter({ hasText: "Prévision commerciale QA" })
    await expect(reopenedCard).toContainText("Utilisateur QA")
    await expect(reopenedCard).not.toContainText("Budget reporté après arbitrage")
    await reopenedCard.getByRole("link", { name: "Prévision commerciale QA" }).click()
    await expect(page.getByRole("heading", { name: "Prévision commerciale QA" })).toBeVisible()
    await expect(page.getByText("Chronologie commerciale")).toBeVisible()
    await page.getByLabel("Compte rendu").fill("Relance QA consignée depuis la fiche opportunité")
    await page.getByRole("button", { name: "Ajouter à l’historique" }).click()
    await expect(page.getByText("Activité ajoutée à la chronologie.")).toBeVisible()
    await expect(page.getByText("Relance QA consignée depuis la fiche opportunité")).toBeVisible()
    await page.goto("/dashboard/pipeline")
  }

  const viewport = page.locator("[data-pipeline-scroll-viewport]")
  await expect(viewport).toHaveCount(1)
  await viewport.evaluate((element) => {
    element.scrollLeft = 0
    element.dispatchEvent(new Event("scroll"))
  })
  await expect.poll(() => viewport.evaluate((element) => element.scrollLeft)).toBe(0)

  const initialState = await viewport.evaluate((element) => ({
    clientWidth: element.clientWidth,
    scrollLeft: element.scrollLeft,
    scrollWidth: element.scrollWidth,
    scrollbarWidth: getComputedStyle(element).scrollbarWidth,
  }))
  expect(initialState.scrollWidth).toBeGreaterThan(initialState.clientWidth)
  expect(initialState.scrollbarWidth).toBe("none")

  const nextControl = page.getByRole("button", { name: "Afficher les étapes suivantes" })
  await expect(nextControl).toBeEnabled()
  await nextControl.click()

  await expect.poll(() => viewport.evaluate((element) => element.scrollLeft)).toBeGreaterThan(0)
  const afterWheel = await viewport.evaluate((element) => element.scrollLeft)

  await page.getByRole("button", { name: "Afficher les étapes précédentes" }).click()
  await expect.poll(() => viewport.evaluate((element) => element.scrollLeft)).toBeLessThan(afterWheel)
})

test("service records connect the help desk, ticket, intervention and installed equipment", async ({ page }) => {
  // The desktop field workflow can resolve this seeded ticket before the mobile project starts.
  // Use the complete queue so the record-chain test is deterministic across both projects.
  await assertHealthy(page, "/dashboard/service/help-desk?status=ALL", "Centre de support")
  await page.getByRole("link", { name: /SAV-2026-900/ }).click()
  await expect(page.getByRole("heading", { name: /SAV-2026-900 · Contrôle couverture QA/ })).toBeVisible()
  await expect(page.getByText("Traitement du ticket")).toBeVisible()
  await page.getByRole("link", { name: "Couverture QA installée" }).click()
  await expect(page.getByRole("heading", { name: "Couverture QA installée" })).toBeVisible()
  await expect(page.getByText("Historique SAV")).toBeVisible()
  await page.getByRole("link", { name: /SAV-2026-900 · Contrôle couverture QA/ }).click()
  await page.getByRole("link", { name: "Intervention QA terrain" }).click()
  await expect(page.getByRole("heading", { name: "Intervention QA terrain" })).toBeVisible()
  await expect(page.getByText("Coûts réels")).toBeVisible()
  await expect(page.getByText("Compte rendu et accord client")).toBeVisible()
})

test("publishes service knowledge and records a secure satisfaction response", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "La mutation de l’invitation est exécutée une seule fois ; les pages Service restent couvertes sur mobile par les tests de chargement.")
  await assertHealthy(page, "/dashboard/service/connaissance", "Base de connaissances")
  await expect(page.getByText("Entretenir la couverture QA")).toBeVisible()
  await page.getByRole("button", { name: "Prévisualiser l’article" }).click()
  await expect(page.getByRole("heading", { name: "Contrôle mensuel" })).toBeVisible()
  await assertHealthy(page, "/dashboard/service/satisfaction", "Satisfaction client")
  await expect(page.locator("[data-slot=card]").filter({ hasText: "Enquêtes disponibles" }).getByText("CSAT QA après résolution")).toBeVisible()
  await page.goto("/feedback/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
  await expect(page.getByRole("heading", { name: "Êtes-vous satisfait de la prise en charge ?" })).toBeVisible()
  await page.getByRole("button", { name: "5", exact: true }).click()
  await page.getByLabel("Que pourrions-nous améliorer ?").fill("Parcours QA simple et réponse très claire")
  await page.getByRole("button", { name: "Envoyer ma réponse" }).click()
  await expect(page.getByRole("heading", { name: /Merci pour votre retour|Réponse enregistrée/ })).toBeVisible()
  await page.goto("/dashboard/service/satisfaction")
  await expect(page.getByText("Parcours QA simple et réponse très claire")).toBeVisible()
  await expect(page.getByText("100%", { exact: true }).first()).toBeVisible()
})

test("configures a product, its options and its bill of materials into a quote", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Le catalogue est configuré une fois ; sa surface responsive reste couverte par les tests de chargement mobile.")
  test.setTimeout(180_000)
  await assertHealthy(page, "/dashboard/catalogue", "Catalogue")
  await page.getByRole("button", { name: "Nouveau produit" }).click()
  await page.getByLabel("Référence / SKU").fill("QA-CONFIG")
  await page.getByLabel("Libellé *", { exact: true }).fill("Gamme configurable QA")
  await page.getByLabel("Famille / gamme").fill("Couverture sur mesure")
  await page.getByLabel("Fabricant").fill("Fabricant QA")
  await page.getByLabel("Coût HT (€)").fill("5000")
  await page.getByLabel("Prix de vente HT (€)").fill("10000")
  await page.getByRole("button", { name: "Créer et configurer" }).click()
  await page.waitForURL(/\/dashboard\/catalogue\/produits\//)
  await expect(page.getByRole("heading", { name: "Gamme configurable QA" })).toBeVisible()

  const groupDetails = page.locator("details").filter({ hasText: "Créer un groupe d’options" })
  await groupDetails.locator("summary").click()
  await groupDetails.locator('input[name="name"]').fill("Coloris")
  await groupDetails.getByText("Choix obligatoire").click()
  await groupDetails.getByRole("button", { name: "Créer le groupe" }).click()
  await expect(page.getByText("Groupe d’options créé.")).toBeVisible()

  const valueDetails = page.locator("details").filter({ hasText: "Ajouter une valeur d’option" })
  await valueDetails.locator("summary").click()
  await valueDetails.locator('select[name="groupId"]').selectOption({ label: "Coloris" })
  await valueDetails.locator('input[name="code"]').fill("ANTH")
  await valueDetails.locator('input[name="label"]').fill("Anthracite")
  await valueDetails.locator('input[name="priceDelta"]').fill("500")
  await valueDetails.locator('input[name="costDelta"]').fill("200")
  await valueDetails.getByRole("button", { name: "Ajouter la valeur" }).click()
  await expect(page.getByText("Valeur d’option ajoutée.")).toBeVisible()

  const componentDetails = page.locator("details").filter({ hasText: "Ajouter ou mettre à jour un composant" })
  await componentDetails.locator("summary").click()
  await componentDetails.locator('select[name="componentProductId"]').selectOption({ label: "QA-COVER · Couverture de test" })
  await componentDetails.locator('input[name="quantity"]').fill("1")
  await componentDetails.getByRole("button", { name: "Ajouter le composant" }).click()
  await expect(page.getByText("Nomenclature mise à jour.")).toBeVisible()

  await page.goto("/dashboard/devis/new")
  await page.getByLabel("Produit à configurer").click()
  await page.getByRole("option", { name: "QA-CONFIG · Gamme configurable QA" }).click()
  await page.getByLabel("Coloris").click()
  await page.getByRole("option", { name: /Anthracite/ }).click()
  await page.getByLabel("Remise (%)").fill("10")
  await expect(page.getByText("Net HT").locator("..")).toContainText("9 450,00 €")
  await page.getByRole("button", { name: "Ajouter au devis" }).click()
  await expect(page.getByText("Configuration ajoutée au devis.")).toBeVisible()
  await expect(page.getByLabel("Prix unitaire hors taxes de la ligne 1")).toHaveValue("9450")
  await page.getByLabel("Client du devis").click()
  await page.getByRole("option", { name: "Client QA Piscine" }).click()
  await page.getByLabel("Objet").fill("Configuration catalogue QA")
  await page.getByRole("button", { name: "Enregistrer" }).click()
  await page.waitForURL(/\/dashboard\/devis\//)
  await expect(page.getByText(/Coloris : Anthracite/)).toBeVisible()
  await expect(page.getByText("9 450,00 €").first()).toBeVisible()
})

test("creates a reusable project plan and enforces milestone dependencies", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Le modèle est créé une fois ; les vues projets restent couvertes sur mobile.")
  await assertHealthy(page, "/dashboard/projets", "Projets")
  await page.getByRole("button", { name: "Modèles" }).click()
  const templateDialog = page.getByRole("dialog", { name: "Modèles de chantier" })
  await templateDialog.getByLabel("Nom").fill("Installation QA standard")
  await templateDialog.getByLabel("Type de chantier").fill("INSTALLATION")
  await templateDialog.getByLabel("Budget par défaut (€)").fill("12500")
  await templateDialog.getByLabel("Durée globale (jours)").fill("10")
  await templateDialog.getByLabel("Étape 1", { exact: true }).fill("Préparation du site")
  await templateDialog.getByLabel("Début J+").fill("0")
  await templateDialog.getByRole("button", { name: "Ajouter une étape" }).click()
  await templateDialog.getByLabel("Étape 2", { exact: true }).fill("Pose et contrôle")
  await templateDialog.getByLabel("Début J+").nth(1).fill("3")
  await templateDialog.getByLabel("Prérequis de l’étape 2").selectOption({ label: "Préparation du site" })
  await templateDialog.getByRole("button", { name: "Créer le modèle" }).click()
  await expect(page.getByText("Modèle de chantier créé.")).toBeVisible()
  await expect(templateDialog.getByText("Installation QA standard")).toBeVisible()
  await templateDialog.getByRole("button", { name: "Fermer" }).click()

  await page.getByRole("button", { name: "Nouveau Projet" }).click()
  const projectDialog = page.getByRole("dialog", { name: "Nouveau projet" })
  await projectDialog.getByLabel("Client du projet").click()
  await page.getByRole("option", { name: "Client QA Piscine" }).click()
  await projectDialog.getByLabel("Modèle de chantier").selectOption({ label: "Installation QA standard · 2 étapes" })
  await projectDialog.getByLabel("Nom *").fill("Chantier planifié QA")
  await projectDialog.getByLabel("Début prévu").fill("2026-09-01")
  await projectDialog.getByRole("button", { name: "Créer", exact: true }).click()
  await expect(page.getByText("Projet créé.")).toBeVisible()

  const projectCard = page.locator("[data-slot=card]").filter({ hasText: "Chantier planifié QA" })
  await expect(projectCard).toContainText("12 500,00 €")
  await projectCard.getByRole("link", { name: /Chantier planifié QA/ }).click()
  await expect(page.getByText("Préparation du site", { exact: true })).toBeVisible()
  await expect(page.getByText("Pose et contrôle", { exact: true })).toBeVisible()
  await expect(page.getByText("après Préparation du site")).toBeVisible()

  await page.getByRole("combobox", { name: "Statut de Pose et contrôle" }).click()
  await page.getByRole("option", { name: "En cours" }).click()
  await expect(page.getByText("Terminez d’abord « Préparation du site »")).toBeVisible()
  await page.getByRole("combobox", { name: "Statut de Préparation du site" }).click()
  await page.getByRole("option", { name: "Terminé" }).click()
  await expect(page.getByText("Jalon mis à jour.")).toBeVisible()
  await page.getByRole("combobox", { name: "Statut de Pose et contrôle" }).click()
  await page.getByRole("option", { name: "En cours" }).click()
  await expect(page.getByText("Jalon mis à jour.")).toBeVisible()
})

test("runs the supplier approval, receipt issue and return workflow", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Le workflow fournisseur est muté une seule fois ; ses surfaces restent chargées sur mobile.")
  test.setTimeout(180_000)
  await assertHealthy(page, "/dashboard/operations", "Opérations")
  const operationType = page.getByRole("combobox", { name: "Type d’opération" })
  await operationType.click()
  await page.getByRole("option", { name: "Fournisseur" }).click()
  await page.getByLabel("Nom *", { exact: true }).fill("Fournisseur QA")
  await page.getByLabel("Code").fill("SUP-QA")
  await page.getByRole("button", { name: "Enregistrer", exact: true }).click()
  await expect(page.getByText("Fournisseur enregistré.")).toBeVisible()

  await page.getByRole("tab", { name: "Stock & achats" }).click()
  await page.getByRole("button", { name: "Nouvelle commande" }).click()
  await page.getByLabel("Fournisseur de la commande").selectOption({ label: "Fournisseur QA" })
  await page.getByLabel("Chantier de la commande").selectOption({ label: "Chantier QA existant" })
  await page.getByLabel("Produit fournisseur 1").selectOption({ label: "QA-COVER · Couverture de test" })
  await page.getByLabel("Quantité fournisseur 1").fill("2")
  await page.getByLabel("Prix fournisseur 1").fill("50")
  await page.getByRole("button", { name: "Ajouter une ligne" }).click()
  await page.getByLabel("Libellé fournisseur 2").fill("Transport usine")
  await page.getByLabel("Quantité fournisseur 2").fill("1")
  await page.getByLabel("Prix fournisseur 2").fill("20")
  await page.getByRole("button", { name: "Créer le brouillon" }).click()
  await expect(page.getByText(/Commande ACH-2026-.* créée en brouillon/)).toBeVisible()

  const order = page.locator("article").filter({ hasText: "Fournisseur QA" })
  await expect(order).toContainText("120,00 € HT")
  await order.getByRole("button", { name: "Soumettre" }).click()
  await expect(page.getByText("Commande soumise pour approbation.")).toBeVisible()
  await order.getByRole("button", { name: "Approuver" }).click()
  await expect(page.getByText("Commande approuvée.")).toBeVisible()
  const purchasePdfHref = await order.getByRole("link", { name: "PDF" }).getAttribute("href")
  expect(purchasePdfHref).toBeTruthy()
  const purchasePdf = await page.request.get(purchasePdfHref!)
  expect(purchasePdf.ok()).toBeTruthy()
  expect((await purchasePdf.body()).subarray(0, 4).toString("ascii")).toBe("%PDF")
  await order.getByRole("button", { name: "Marquer envoyée" }).click()
  await expect(page.getByText("Commande marquée comme envoyée.")).toBeVisible()
  await order.getByRole("button", { name: "Accusé fournisseur" }).click()
  await page.getByLabel("Référence fournisseur").fill("ARC-QA-001")
  await page.getByLabel("Date confirmée").fill("2026-09-15")
  await page.getByRole("button", { name: "Enregistrer", exact: true }).click()
  await expect(page.getByText("Accusé fournisseur enregistré.")).toBeVisible()

  await order.getByRole("button", { name: "Réceptionner" }).click()
  const receiptDialog = page.getByRole("dialog", { name: "Réception fournisseur" })
  await receiptDialog.getByLabel("Ligne").selectOption({ label: "Couverture de test · reste 2" })
  await receiptDialog.getByLabel("Dépôt").selectOption({ label: "Dépôt QA" })
  await receiptDialog.getByLabel("Quantité livrée").fill("2")
  await receiptDialog.getByLabel("Dont rejetée").fill("1")
  await receiptDialog.getByLabel("Type d’anomalie").selectOption("QUALITY")
  await receiptDialog.getByLabel("Détail de l’anomalie").fill("Finition non conforme")
  await receiptDialog.getByRole("button", { name: "Enregistrer la réception" }).click()
  await expect(page.getByText("Réception et stock enregistrés.")).toBeVisible()
  await expect(order.getByText(/Non-conforme.*1 × Couverture de test/)).toBeVisible()

  await order.getByRole("button", { name: "Traiter" }).click()
  const issueDialog = page.getByRole("dialog", { name: "Traiter l’anomalie fournisseur" })
  await issueDialog.getByLabel("Décision").selectOption("CREDIT")
  await issueDialog.getByLabel("Détail / preuve").fill("Avoir accepté par le fournisseur")
  await issueDialog.getByRole("button", { name: "Valider" }).click()
  await expect(page.getByText("Anomalie fournisseur mise à jour.")).toBeVisible()
  await expect(order.getByText("Réception partielle")).toBeVisible()
  await expect(order.getByText("1 unité en reliquat")).toBeVisible()

  await order.getByRole("button", { name: "Réceptionner" }).click()
  const finalReceiptDialog = page.getByRole("dialog", { name: "Réception fournisseur" })
  await finalReceiptDialog.getByLabel("Ligne").selectOption({ label: "Transport usine · reste 1" })
  await finalReceiptDialog.getByLabel("Dépôt").selectOption({ label: "Dépôt QA" })
  await finalReceiptDialog.getByLabel("Quantité livrée").fill("1")
  await finalReceiptDialog.getByRole("button", { name: "Enregistrer la réception" }).click()
  await expect(page.getByText("Réception et stock enregistrés.")).toBeVisible()
  await expect(order.getByText("Réceptionnée")).toBeVisible()

  await order.getByRole("button", { name: "Retour fournisseur" }).click()
  const returnDialog = page.getByRole("dialog", { name: "Retour fournisseur" })
  await returnDialog.getByLabel("Ligne reçue").selectOption({ label: "Couverture de test · retournable 1" })
  await returnDialog.getByLabel("Dépôt").selectOption({ label: "Dépôt QA" })
  await returnDialog.getByLabel("Quantité").fill("1")
  await returnDialog.getByLabel("Motif").fill("Retour après contrôle complémentaire")
  await returnDialog.getByRole("button", { name: "Expédier le retour" }).click()
  await expect(page.getByText("Retour fournisseur expédié et stock décrémenté.")).toBeVisible()
  await order.getByRole("button", { name: "Enregistrer l’avoir" }).click()
  await page.getByLabel("Référence de l’avoir").fill("AVF-QA-001")
  await page.getByRole("button", { name: "Enregistrer l’avoir" }).click()
  await expect(page.getByText("Avoir fournisseur rattaché au retour.")).toBeVisible()
  await expect(order.getByText("Crédité", { exact: true })).toBeVisible()
  await order.getByRole("link", { name: "Dossier" }).click()
  await expect(page.getByText("Cycle d’approbation")).toBeVisible()
  await expect(page.getByText("Anomalies qualité")).toBeVisible()
  await page.getByRole("link", { name: "Fournisseur QA", exact: true }).first().click()
  await expect(page.getByRole("heading", { name: "Fournisseur QA" })).toBeVisible()
  await expect(page.getByText("Ponctualité")).toBeVisible()
})

test("field workspace installs and reloads from its bounded offline cache", async ({ page, context }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop" || process.env.E2E_USE_PRODUCTION_SERVER !== "true", "La coupure réseau est validée sur le serveur de production ; le rendu terrain reste couvert ailleurs.")
  await assertHealthy(page, "/dashboard/terrain", "Terrain hors ligne")
  const manifest = await page.request.get("/manifest.webmanifest")
  expect(manifest.ok()).toBeTruthy()
  await expect(manifest.json()).resolves.toMatchObject({ name: "CRM & opérations", start_url: "/dashboard/terrain", display: "standalone" })
  expect((await page.request.get("/sw.js")).ok()).toBeTruthy()

  await page.getByRole("button", { name: "Activer hors ligne" }).click()
  await expect(page.getByText("Interventions et écran terrain disponibles hors connexion pendant 24 h.")).toBeVisible()
  await expect.poll(() => page.evaluate(async () => (await caches.keys()).includes("crm-field-v1-field"))).toBe(true)

  await context.setOffline(true)
  try {
    await page.reload({ waitUntil: "domcontentloaded" })
    await expect(page.getByRole("heading", { name: "Terrain hors ligne" })).toBeVisible()
    await expect(page.getByText("Mode hors ligne", { exact: true })).toBeVisible()
    await expect(page.getByText("Intervention QA terrain")).toBeVisible()
  } finally {
    await context.setOffline(false)
  }
  const expectedOfflineErrors = (page as Page & { consoleErrors?: string[] }).consoleErrors ?? []
  expect(expectedOfflineErrors.every((message) => message.includes("ERR_INTERNET_DISCONNECTED"))).toBe(true)
  expectedOfflineErrors.length = 0
})

test("configures an email sequence and a lead automation", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "La configuration est créée une fois ; la page reste couverte sur mobile par les tests de surfaces.")
  await assertHealthy(page, "/dashboard/automatisations", "Automatisations & e-mails")

  await page.getByRole("tab", { name: "Modèles" }).click()
  const templatePanel = page.getByRole("tabpanel", { name: "Modèles" })
  await templatePanel.locator('input[name="name"]').fill("Suivi projet QA")
  await templatePanel.locator('input[name="subject"]').fill("Votre projet {{lead.projectType}}")
  await templatePanel.locator('textarea[name="bodyHtml"]').fill("<p>Bonjour {{contact.firstName}},</p><p>Nous restons disponibles pour votre projet.</p>")
  await templatePanel.getByRole("button", { name: "Enregistrer" }).click()
  await expect(page.getByText("Modèle enregistré.")).toBeVisible()

  await page.getByRole("tab", { name: "Séquences" }).click()
  const sequencePanel = page.getByRole("tabpanel", { name: "Séquences" })
  const createSequenceForm = sequencePanel.locator("form").first()
  await createSequenceForm.locator('input[name="name"]').fill("Nurturing QA")
  await createSequenceForm.locator('input[name="description"]').fill("Séquence de recette")
  await createSequenceForm.getByRole("button", { name: "Créer" }).click()
  await expect(page.getByText("Séquence créée.")).toBeVisible()
  const sequenceCard = page.locator("[data-slot=card]").filter({ hasText: "Nurturing QA" }).last()
  await sequenceCard.locator('select[name="templateId"]').selectOption({ label: "Suivi projet QA" })
  await sequenceCard.locator('input[name="delayHours"]').fill("24")
  await sequenceCard.getByRole("button", { name: "Ajouter l’étape" }).click()
  await expect(page.getByText("Étape ajoutée.")).toBeVisible()
  await sequenceCard.getByRole("button", { name: "Activer" }).click()
  await expect(page.getByText("Séquence activée.")).toBeVisible()

  await page.getByRole("tab", { name: "Règles" }).click()
  const workflowPanel = page.getByRole("tabpanel", { name: "Règles" })
  const workflowForm = workflowPanel.locator("form").first()
  await workflowForm.locator('input[name="name"]').fill("Inscription nouveaux leads QA")
  await workflowForm.locator('input[name="source"]').fill("E2E")
  await workflowForm.locator('select[name="actionType"]').selectOption("ENROLL_SEQUENCE")
  await workflowForm.locator('select[name="sequenceId"]').selectOption({ label: "Nurturing QA" })
  await workflowForm.getByRole("button", { name: "Créer la règle" }).click()
  await expect(page.getByText("Règle créée en brouillon.")).toBeVisible()
  const workflowCard = page.locator("[data-slot=card]").filter({ hasText: "Inscription nouveaux leads QA" }).last()
  await workflowCard.getByRole("button", { name: "Activer" }).click()
  await expect(page.getByText("Règle activée.")).toBeVisible()
})

test("plans a multichannel marketing campaign and links its sequence", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "La campagne est créée une seule fois ; sa vue reste couverte au build mobile.")
  await assertHealthy(page, "/dashboard/campagnes", "Campagnes")
  const creation = page.locator("details").filter({ hasText: "Créer une campagne" })
  await creation.locator("summary").click()
  await creation.locator('input[name="name"]').fill("Campagne QA printemps")
  await creation.locator('input[name="objective"]').fill("Obtenir des demandes de visite technique")
  await creation.locator('input[name="startAt"]').fill("2026-09-01")
  await creation.locator('input[name="endAt"]').fill("2026-10-15")
  await creation.locator('input[name="budget"]').fill("1500")
  await creation.locator('input[name="utmCampaign"]').fill("qa-printemps")
  await creation.getByRole("button", { name: "Créer la campagne" }).click()
  await expect(page.getByText("Campagne créée.")).toBeVisible()
  const campaign = page.locator('[data-slot="card"]').filter({ hasText: "Campagne QA printemps" }).last()
  await expect(campaign).toContainText("Obtenir des demandes de visite technique")
  await campaign.getByLabel("Statut de la campagne Campagne QA printemps").selectOption("PLANNED")
  await expect(page.getByText("Statut de campagne mis à jour.")).toBeVisible()
  await campaign.getByLabel("Nom du livrable pour Campagne QA printemps").fill("E-mail d’annonce QA")
  await campaign.getByLabel("Échéance du livrable pour Campagne QA printemps").fill("2026-09-01")
  await campaign.getByRole("button", { name: "Ajouter" }).click()
  await expect(page.getByText("Livrable ajouté.")).toBeVisible()
  await campaign.getByLabel("Séquence à rattacher à Campagne QA printemps").selectOption({ label: "Nurturing QA · ACTIVE" })
  await campaign.getByRole("button", { name: "Rattacher la séquence" }).click()
  await expect(page.getByText("Séquence rattachée.")).toBeVisible()
})

test("lead, consent withdrawal, order, billing and reserved stock flow", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Les mutations destructives sont validées une fois ; les surfaces restent testées sur mobile.")
  test.setTimeout(180_000)
  const leadResponse = await page.request.post("/api/public/leads", {
    headers: { Origin: "https://example.test" },
    data: {
      firstName: "Alex",
      lastName: "Bassin QA",
      email: "alex.bassin.qa@example.com",
      phone: "+33601020304",
      postalCode: "44000",
      city: "Nantes",
      projectType: "Couverture de piscine",
      message: "Demande E2E CRM",
      privacyAccepted: true,
      marketingOptIn: true,
      source: "E2E",
    },
  })
  expect(leadResponse.status()).toBe(201)

  await assertHealthy(page, "/dashboard/leads", "Prospects entrants")
  const leadCard = page.locator("article").filter({ hasText: "Alex Bassin QA" })
  await expect(leadCard).toBeVisible()
  await expect(leadCard.getByText("Marketing accepté")).toBeVisible()
  await assertHealthy(page, "/dashboard/automatisations", "Automatisations & e-mails")
  await expect(page.locator("p").filter({ hasText: /^Alex Bassin QA$/ }).first()).toBeVisible()
  await assertHealthy(page, "/dashboard/leads", "Prospects entrants")
  const refreshedLeadCard = page.locator("article").filter({ hasText: "Alex Bassin QA" })
  await page.context().grantPermissions(["clipboard-read", "clipboard-write"])
  await refreshedLeadCard.getByRole("button", { name: "Copier le lien de désinscription" }).click()
  await expect(page.getByText("Lien de désinscription copié.")).toBeVisible()
  const withdrawalUrl = await page.evaluate(() => navigator.clipboard.readText())
  expect(withdrawalUrl).toContain("/consent/withdraw/")
  const token = withdrawalUrl.split("/").at(-1)
  expect(token).toBeTruthy()
  await page.goto(withdrawalUrl)
  await page.getByRole("button", { name: "Confirmer ma désinscription" }).click()
  await expect(page.getByText("Préférence enregistrée", { exact: true })).toBeVisible()
  const replay = await page.request.post("/api/public/consent/withdraw", { data: { token } })
  expect(replay.ok()).toBeTruthy()
  await expect(replay.json()).resolves.toMatchObject({ success: true, alreadyWithdrawn: true })
  await assertHealthy(page, "/dashboard/leads", "Prospects entrants")
  await expect(page.locator("article").filter({ hasText: "Alex Bassin QA" }).getByText("Service uniquement")).toBeVisible()

  await page.goto("/dashboard/devis")
  await page.getByRole("link", { name: "DEV-2026-900" }).click()
  await page.getByRole("button", { name: "Créer la commande" }).click()
  await page.waitForURL(/\/dashboard\/operations\?tab=orders/)
  const ordersPanel = page.getByRole("tabpanel", { name: "Commandes" })
  await expect(ordersPanel.getByText("Client QA Piscine")).toBeVisible()
  await expect(ordersPanel.getByText(/CMD-2026-/).first()).toBeVisible()

  await page.getByRole("button", { name: "Facturer le solde" }).first().click()
  await page.waitForURL(/\/dashboard\/factures\//)
  await expect(page.getByText(/Solde de la commande CMD-2026-/).first()).toBeVisible()

  await page.goto("/dashboard/operations?tab=orders")
  const operationType = page.getByRole("combobox", { name: "Type d’opération" })
  await operationType.click()
  await page.getByRole("option", { name: "Réservation de stock" }).focus()
  await page.keyboard.press("Enter")
  await expect(operationType).toContainText("Réservation de stock")
  await page.getByLabel("Dépôt").selectOption({ label: "Dépôt QA" })
  await page.getByLabel("Produit").selectOption({ label: "QA-COVER · Couverture de test" })
  await page.getByLabel("Commande client").selectOption({ index: 1 })
  await page.getByLabel("Quantité").fill("1")
  await page.getByRole("button", { name: "Enregistrer" }).click()
  await expect(page.getByText("Réservation de stock enregistré.")).toBeVisible()
  await expect(page.getByText("Couverture de test").last()).toBeVisible()

  await page.getByRole("button", { name: "Consommer" }).click()
  await expect(page.getByText("Stock consommé pour le dossier.")).toBeVisible()
  await page.getByRole("tab", { name: "Stock & achats" }).click()
  await expect(page.getByText("4 disponibles")).toBeVisible()

  await operationType.click()
  await page.getByRole("option", { name: "Bon de livraison" }).click()
  await page.getByLabel("Commande client").selectOption({ index: 1 })
  await page.getByLabel("Ligne livrée").selectOption({ index: 1 })
  await page.getByLabel("Quantité").fill("1")
  await page.getByLabel("Réceptionnaire").fill("Camille Piscine")
  await page.getByRole("button", { name: "Enregistrer" }).click()
  await expect(page.getByText("Bon de livraison enregistré.")).toBeVisible()
  await page.getByRole("tab", { name: "Commandes" }).click()
  const deliverySection = page.getByText("Derniers bons de livraison").locator("..").locator("..")
  await deliverySection.getByRole("button", { name: "Faire signer" }).click()
  await page.getByLabel("Nom du réceptionnaire").fill("Camille Piscine")
  await page.getByText("Le réceptionnaire confirme les quantités indiquées").click()
  await page.getByRole("button", { name: "Signer et sceller" }).click()
  await expect(page.getByText("Bon de livraison signé et scellé.")).toBeVisible()
  const deliveryPdfHref = await deliverySection.getByRole("link", { name: "PDF" }).getAttribute("href")
  expect(deliveryPdfHref).toBeTruthy()
  const deliveryPdf = await page.request.get(deliveryPdfHref!)
  expect(deliveryPdf.ok()).toBeTruthy()
  expect((await deliveryPdf.body()).subarray(0, 4).toString("ascii")).toBe("%PDF")
})

test("field report and maintenance contract flow", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Les mutations destructives sont validées une fois ; les surfaces restent testées sur mobile.")
  test.setTimeout(180_000)
  await assertHealthy(page, "/dashboard/equipe", "Équipe")
  await page.getByLabel("Coût horaire interne en euros").fill("40")
  await page.getByTitle("Enregistrer capacité et coût").click()
  await expect(page.getByText("Capacité et coût horaire mis à jour.")).toBeVisible()
  await assertHealthy(page, "/dashboard/operations", "Opérations")

  await page.getByRole("tab", { name: "Planning" }).click()
  await expect(page.getByText("Capacité de la semaine")).toBeVisible()
  const planningPanel = page.getByRole("tabpanel", { name: "Planning" })
  await expect(planningPanel.getByText("Utilisateur QA", { exact: true }).first()).toBeVisible()
  const intervention = planningPanel.locator("[data-field-intervention]").filter({ hasText: "Intervention QA terrain" })
  await expect(intervention).toBeVisible()
  await intervention.getByRole("button", { name: "Replanifier" }).click()
  const planningDialog = page.getByRole("dialog", { name: "Replanifier l’intervention" })
  await planningDialog.getByLabel("Début").fill("2026-09-20T10:00")
  await planningDialog.getByLabel("Fin").fill("2026-09-20T11:30")
  await planningDialog.getByRole("button", { name: "Enregistrer" }).click()
  await expect(page.getByText("Intervention replanifiée.")).toBeVisible()
  await expect(planningPanel.getByText("Tournées à venir")).toBeVisible()

  const operationTypeForConflict = page.getByRole("combobox", { name: "Type d’opération" })
  await operationTypeForConflict.click()
  await page.getByRole("option", { name: "Intervention", exact: true }).click()
  await page.getByLabel("Site").selectOption({ label: "Client QA Piscine · Bassin QA" })
  await page.getByLabel("Intervenant").selectOption({ label: "Utilisateur QA" })
  await page.getByLabel("Objet").fill("Intervention QA en conflit")
  await page.getByLabel("Début").fill("2026-09-20T10:30")
  await page.getByLabel("Fin prévue").fill("2026-09-20T11:00")
  await page.getByRole("button", { name: "Enregistrer", exact: true }).click()
  await expect(page.getByText(/Conflit de planning avec « Intervention QA terrain »/)).toBeVisible()
  await assertHealthy(page, "/dashboard/terrain", "Terrain hors ligne")
  const fieldIntervention = page.locator("article").filter({ hasText: "Intervention QA terrain" })
  await expect(fieldIntervention).toBeVisible()
  await fieldIntervention.getByLabel("Compte rendu terrain").fill("Pose contrôlée, essais fonctionnels conformes et zone nettoyée.")
  await fieldIntervention.getByLabel("Temps passé (minutes)").fill("75")
  await fieldIntervention.getByLabel("Client présent", { exact: true }).fill("Camille Piscine")
  await fieldIntervention.getByText("Ajouter des photos").locator("input").setInputFiles({
    name: "photo-fin-qa.png",
    mimeType: "image/png",
    buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZQMcAAAAASUVORK5CYII=", "base64"),
  })
  await expect(page.getByText("Brouillon conservé sur cet appareil.")).toBeVisible()

  const materialSection = fieldIntervention.locator("div.rounded-xl.border").filter({ hasText: "Matériel consommé" })
  await materialSection.getByRole("button", { name: "Ajouter" }).click()
  await materialSection.getByLabel("Dépôt du matériel").selectOption({ label: "Dépôt QA" })
  const materialProductValue = await materialSection.getByLabel("Produit consommé").locator("option").filter({ hasText: "QA-COVER · Couverture de test" }).getAttribute("value")
  expect(materialProductValue).toBeTruthy()
  await materialSection.getByLabel("Produit consommé").selectOption(materialProductValue!)
  await materialSection.getByLabel("Quantité de matériel").fill("1")

  const expenseSection = fieldIntervention.locator("div.rounded-xl.border").filter({ hasText: "Frais terrain" })
  await expenseSection.getByRole("button", { name: "Ajouter" }).click()
  await expenseSection.getByLabel("Libellé du frais").fill("Péage QA")
  await expenseSection.getByLabel("Catégorie du frais").selectOption("TOLL")
  await expenseSection.getByLabel("Montant TTC du frais").fill("12.50")
  await expenseSection.getByLabel("TVA du frais").fill("0")
  await expenseSection.getByText("Ajouter un justificatif").locator("input").setInputFiles({
    name: "justificatif-peage-qa.png",
    mimeType: "image/png",
    buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZQMcAAAAASUVORK5CYII=", "base64"),
  })

  const reservationSection = fieldIntervention.locator("div.rounded-xl.border").filter({ hasText: "Réserves et reprises" })
  await reservationSection.getByRole("button", { name: "Ajouter" }).click()
  await reservationSection.getByLabel("Titre de la réserve").fill("Réglage fin QA")
  await reservationSection.getByLabel("Sévérité de la réserve").selectOption("MAJOR")
  await reservationSection.getByLabel("Détail de la réserve").fill("Contrôler le réglage après sept jours d’utilisation.")

  const signatureCanvas = fieldIntervention.locator("canvas")
  await signatureCanvas.scrollIntoViewIfNeeded()
  const signatureBox = await signatureCanvas.boundingBox()
  expect(signatureBox).toBeTruthy()
  await page.mouse.move(signatureBox!.x + 25, signatureBox!.y + 95)
  await page.mouse.down()
  await page.mouse.move(signatureBox!.x + 70, signatureBox!.y + 45, { steps: 4 })
  await page.mouse.move(signatureBox!.x + 120, signatureBox!.y + 110, { steps: 4 })
  await page.mouse.up()
  await expect.poll(() => signatureCanvas.evaluate((canvas) => {
    const context = (canvas as HTMLCanvasElement).getContext("2d")
    return Boolean(context && Array.from(context.getImageData(0, 0, (canvas as HTMLCanvasElement).width, (canvas as HTMLCanvasElement).height).data).some((value, index) => index % 4 === 3 && value > 0))
  })).toBe(true)
  await fieldIntervention.getByRole("button", { name: "Confirmer la signature" }).click()
  await expect(fieldIntervention.getByText("Signature capturée")).toBeVisible()
  await fieldIntervention.getByText("Accord du client présent").click()
  await fieldIntervention.getByRole("button", { name: "Clôturer et synchroniser" }).click()
  await expect(page.getByText("Rapport, stock, frais, réserves et signature synchronisés.")).toBeVisible()
  await expect(page.getByRole("heading", { name: "Clôturées récemment" })).toBeVisible()

  await assertHealthy(page, "/dashboard/operations", "Opérations")
  await page.getByRole("tab", { name: "Planning" }).click()
  const completedIntervention = page.getByRole("tabpanel", { name: "Planning" }).locator("[data-field-intervention]").filter({ hasText: "Intervention QA terrain" })
  await expect(completedIntervention.getByText(/Compte rendu : Pose contrôlée/)).toBeVisible()
  await expect(completedIntervention.getByText("Matériel 50,00 € · Main-d’œuvre 50,00 € · Frais 12,50 €")).toBeVisible()
  await expect(completedIntervention.getByText("112,50 €", { exact: true })).toBeVisible()
  await expect(completedIntervention.getByText("Péage QA · 12,50 € · justifié")).toBeVisible()
  await expect(completedIntervention.getByText("Réglage fin QA")).toBeVisible()
  await expect(completedIntervention.getByText("Majeure", { exact: true })).toBeVisible()
  await completedIntervention.getByRole("button", { name: "Marquer résolue" }).click()
  await expect(page.getByText("Réserve résolue.")).toBeVisible()
  await expect(completedIntervention.getByText("Résolue", { exact: true })).toBeVisible()

  const evidenceLink = completedIntervention.getByRole("link", { name: "photo-fin-qa.png" })
  await expect(evidenceLink).toBeVisible()
  const evidenceHref = await evidenceLink.getAttribute("href")
  expect(evidenceHref).toBeTruthy()
  const evidenceResponse = await page.request.get(evidenceHref!)
  expect(evidenceResponse.ok()).toBeTruthy()
  expect(evidenceResponse.headers()["content-type"]).toContain("image/png")
  const reportHref = await completedIntervention.getByRole("link", { name: "Rapport PDF" }).getAttribute("href")
  expect(reportHref).toBeTruthy()
  const reportResponse = await page.request.get(reportHref!)
  expect(reportResponse.ok()).toBeTruthy()
  expect((await reportResponse.body()).subarray(0, 4).toString("ascii")).toBe("%PDF")
  const reportPreview = await page.request.get(`${reportHref}?screen=1`)
  expect(reportPreview.ok()).toBeTruthy()
  const reportHtml = await reportPreview.text()
  expect(reportHtml).toContain("Couverture de test")
  expect(reportHtml).toContain("Péage QA")
  expect(reportHtml).toContain("Réglage fin QA")
  expect(reportHtml).toContain("Signature manuscrite du client")

  const operationType = page.getByRole("combobox", { name: "Type d’opération" })
  await operationType.click()
  await page.getByRole("option", { name: "Contrat d’entretien" }).click()
  await page.getByLabel("Client").selectOption({ label: "Client QA Piscine" })
  await page.locator("select#siteId").selectOption({ label: "Client QA Piscine · Bassin QA" })
  await page.getByLabel("Libellé du contrat").fill("Entretien annuel couverture QA")
  await page.getByLabel("Équipement couvert").selectOption({ label: "Client QA Piscine · Couverture QA installée" })
  await page.getByLabel("Début").fill("2026-08-20")
  await page.getByLabel("Prochaine visite").fill("2026-08-20")
  await page.getByLabel("Prix HT (€)").fill("240")
  await page.getByText("Facturation automatique").click()
  await page.getByRole("button", { name: "Enregistrer" }).click()
  await expect(page.getByText("Contrat d’entretien enregistré.")).toBeVisible()
  await page.getByRole("tab", { name: "Entretien" }).click()
  await expect(page.getByText("Entretien annuel couverture QA")).toBeVisible()
  await expect(page.getByText(/ENT-2026-/)).toBeVisible()
  const schedulerSecret = process.env.SCHEDULER_CRON_SECRET
  if (schedulerSecret) {
    const firstRun = await page.request.post("/api/scheduling/process", { headers: { authorization: `Bearer ${schedulerSecret}` } })
    expect(firstRun.ok()).toBeTruthy()
    await expect(firstRun.json()).resolves.toMatchObject({ recurringInvoices: { generated: 1 }, maintenanceVisits: { scheduled: 1 } })
    const replay = await page.request.post("/api/scheduling/process", { headers: { authorization: `Bearer ${schedulerSecret}` } })
    expect(replay.ok()).toBeTruthy()
    await expect(replay.json()).resolves.toMatchObject({ recurringInvoices: { generated: 0 }, maintenanceVisits: { scheduled: 0 } })
    await page.goto("/dashboard/operations")
    await page.getByRole("tab", { name: "Planning" }).click()
    await expect(page.getByText("Entretien · Entretien annuel couverture QA")).toBeVisible()
    await page.goto("/dashboard/factures")
    const maintenanceInvoiceRow = page.getByRole("row").filter({ hasText: "288,00 €" })
    await expect(maintenanceInvoiceRow).toBeVisible()
    await maintenanceInvoiceRow.getByRole("link", { name: /FACT-2026-/ }).click()
    await expect(page.getByText(/Contrat d’entretien ENT-2026-/)).toBeVisible()
  }
})

test("scores prospects and exposes the communication center", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Le scoring est recalculé une seule fois ; les pages restent vérifiées au build responsive.")
  await assertHealthy(page, "/dashboard/marketing", "Scoring & segments")
  await page.getByRole("button", { name: "Tout recalculer" }).click()
  await expect(page.getByText("Scoring et segments actualisés.")).toBeVisible()
  await page.getByRole("tab", { name: "Règles de score" }).click()
  await expect(page.getByText("Ajouter une règle")).toBeVisible()

  await assertHealthy(page, "/dashboard/communications", "Communications")
  await page.getByRole("tab", { name: "Nouvel e-mail" }).click()
  await expect(page.getByText("Aperçu sécurisé", { exact: true })).toBeVisible()
  await expect(page.locator('iframe[title="Aperçu du nouvel e-mail"]')).toHaveCount(1)
  await page.getByRole("tab", { name: "Intégrations" }).click()
  await expect(page.locator('[data-slot="card-title"]').filter({ hasText: /^Google Workspace$/ })).toBeVisible()
  await expect(page.locator('[data-slot="card-title"]').filter({ hasText: /^Microsoft 365$/ })).toBeVisible()
})

test("shares a revocable client portal with messages and appointments", async ({ page, browser }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Le portail est muté une seule fois ; sa route publique est responsive par construction et build.")
  await assertHealthy(page, "/dashboard/clients", "Clients")
  await page.getByRole("link", { name: /Client QA Piscine/ }).click()
  await expect(page.getByRole("heading", { name: "Client QA Piscine" })).toBeVisible()
  await page.getByLabel("Contact destinataire").selectOption({ index: 1 })
  await page.getByLabel("Libellé interne").fill("Accès recette QA")
  await page.getByRole("button", { name: "Créer un accès portail" }).click()
  await expect(page.getByText("Accès créé. Le lien a été copié.")).toBeVisible()
  const portalUrl = await page.getByLabel("Lien d’accès à copier").inputValue()
  expect(portalUrl).toContain("/portal/access/")

  const portalContext = await browser.newContext()
  const portalPage = await portalContext.newPage()
  await portalPage.goto(portalUrl)
  await expect(portalPage.getByRole("heading", { name: "Votre dossier en un coup d’œil" })).toBeVisible()
  await expect(portalPage.getByText("Chantier QA existant")).toBeVisible()
  await expect(portalPage.getByRole("link", { name: /DEV-2026-900/ })).toBeVisible()
  await portalPage.getByLabel("Votre message").fill("Bonjour, pouvez-vous confirmer la prochaine étape du dossier QA ?")
  await portalPage.getByRole("button", { name: "Envoyer le message" }).click()
  await expect(portalPage.getByText("Message envoyé.")).toBeVisible()
  await portalPage.getByLabel("Objet du rendez-vous").fill("Point de suivi QA")
  await portalPage.getByLabel("Créneau souhaité").fill("2026-10-10T10:00")
  await portalPage.getByLabel("Autre créneau").fill("2026-10-12T14:00")
  await portalPage.getByRole("button", { name: "Envoyer la demande" }).click()
  await expect(portalPage.getByText("Demande transmise.")).toBeVisible()
  await portalContext.close()

  await page.reload()
  await expect(page.getByText(/confirmer la prochaine étape/)).toBeVisible()
  await expect(page.getByText("Point de suivi QA")).toBeVisible()
  await page.getByLabel("Répondre au client").fill("La prochaine étape est confirmée. Nous revenons vers vous avec le créneau final.")
  await page.getByRole("button", { name: "Envoyer la réponse" }).click()
  await expect(page.getByText("Réponse envoyée.")).toBeVisible()
  await page.getByRole("button", { name: "Révoquer l’accès" }).first().click()
  await expect(page.getByText("Accès révoqué.")).toBeVisible()

  const revokedContext = await browser.newContext()
  const revokedPage = await revokedContext.newPage()
  await revokedPage.goto(portalUrl)
  await expect(revokedPage.getByText("Ce lien a expiré, a été révoqué ou n’est plus valide.")).toBeVisible()
  await revokedContext.close()
})

test("creates and signs in a production account with a password", async ({ browser }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "La création de compte est exécutée une seule fois.")
  const context = await browser.newContext()
  const page = await context.newPage()
  await page.goto("/auth/register")
  await page.getByLabel("Nom complet").fill("Nouveau Propriétaire QA")
  await page.getByLabel("Adresse e-mail professionnelle").fill("nouveau-proprietaire-qa@example.com")
  await page.getByLabel("Mot de passe", { exact: true }).fill("CompteSolide2026")
  await page.getByLabel("Confirmation").fill("CompteSolide2026")
  await page.getByText(/J’accepte les/).click()
  await page.getByRole("button", { name: "Créer mon espace" }).click()
  await page.waitForURL(/\/onboarding/)
  await expect(page.getByRole("heading", { name: "Un espace prêt pour vos ventes et vos chantiers." })).toBeVisible()
  await context.close()
})
