import { expect, test } from "@playwright/test"

test("administers marketing rules and static lists on desktop and mobile", async ({ page }, testInfo) => {
  const suffix = `${testInfo.project.name}-${Date.now()}`
  const ruleName = `Règle ${suffix}`, editedRule = `Modifiée ${suffix}`, copyRule = `Copie ${suffix}`
  const listName = `Liste ${suffix}`, editedList = `Liste modifiée ${suffix}`, copyList = `Liste copie ${suffix}`
  await page.goto("/dashboard/marketing")
  await page.getByRole("tab", { name: "Règles de score" }).click()
  const ruleForm = page.locator("form").filter({ has: page.locator('input[name="points"]') })
  await ruleForm.getByLabel("Nom", { exact: true }).fill(ruleName)
  await ruleForm.getByLabel("Points").fill("5")
  await ruleForm.getByRole("button", { name: "Ajouter", exact: true }).click()
  await expect(page.getByText("Règle créée.", { exact: true })).toBeVisible()
  let commands = page.getByRole("group", { name: `Commandes pour ${ruleName}`, exact: true })
  await commands.getByRole("button", { name: "Modifier" }).click()
  await ruleForm.getByLabel("Nom", { exact: true }).fill(editedRule)
  await ruleForm.getByRole("button", { name: "Enregistrer", exact: true }).click()
  commands = page.getByRole("group", { name: `Commandes pour ${editedRule}`, exact: true })
  await expect(commands).toBeVisible()
  await commands.getByRole("button", { name: "Dupliquer" }).click()
  let dialog = page.getByRole("dialog")
  await dialog.getByLabel("Nom de la copie").fill(copyRule)
  await dialog.getByRole("button", { name: "Dupliquer", exact: true }).click()
  await expect(page.getByRole("group", { name: `Commandes pour ${copyRule}`, exact: true })).toBeVisible()
  await commands.getByRole("button", { name: "Archiver" }).click()
  await page.getByRole("dialog").getByRole("button", { name: "Archiver", exact: true }).click()
  await expect(commands.getByRole("button", { name: "Modifier" })).toBeDisabled()

  await page.getByRole("tab", { name: "Segments", exact: true }).click()
  const segmentForm = page.locator("form").filter({ has: page.locator('select[name="kind"]') })
  await segmentForm.getByLabel("Nom", { exact: true }).fill(listName)
  await segmentForm.getByLabel("Type", { exact: true }).selectOption("STATIC")
  await segmentForm.getByRole("button", { name: "Aperçu d’éligibilité" }).click()
  await expect(page.getByRole("status").filter({ hasText: "correspondent aux critères" })).toBeVisible()
  await segmentForm.getByRole("button", { name: "Créer le segment" }).click()
  let card = page.locator('[data-slot="card"]').filter({ has: page.locator('[data-slot="card-title"]').filter({ hasText: new RegExp(`^${listName}$`) }) })
  await card.getByRole("button", { name: "Modifier" }).click()
  await expect(segmentForm.getByLabel("Type", { exact: true })).toBeDisabled()
  await segmentForm.getByLabel("Nom", { exact: true }).fill(editedList)
  await segmentForm.getByRole("button", { name: "Enregistrer", exact: true }).click()
  card = page.locator('[data-slot="card"]').filter({ has: page.locator('[data-slot="card-title"]').filter({ hasText: new RegExp(`^${editedList}$`) }) })
  await card.getByRole("button", { name: "Voir les membres" }).click()
  dialog = page.getByRole("dialog")
  await expect(dialog.getByText("Aucun prospect trouvé.")).toBeVisible()
  await dialog.getByRole("button", { name: "Ajouter des prospects" }).click()
  await dialog.getByLabel("Rechercher un prospect").fill("camille@example.com")
  await dialog.getByRole("button", { name: "Rechercher", exact: true }).click()
  await dialog.getByRole("checkbox", { name: "Sélectionner Camille Piscine" }).check()
  await dialog.getByRole("button", { name: /^Ajouter la sélection/ }).click()
  await expect(page.getByText(/Prospects ajoutés\./)).toBeVisible()
  await dialog.getByRole("button", { name: "Membres actuels" }).click()
  await dialog.getByRole("checkbox", { name: "Sélectionner Camille Piscine" }).check()
  await dialog.getByRole("button", { name: /^Retirer la sélection/ }).click()
  await expect(dialog.getByText("Aucun prospect trouvé.")).toBeVisible()
  await dialog.getByRole("button", { name: "Fermer la fenêtre" }).click()
  await card.getByRole("button", { name: "Dupliquer", exact: true }).click()
  dialog = page.getByRole("dialog")
  await dialog.getByLabel("Nom de la copie").fill(copyList)
  await dialog.getByRole("button", { name: "Dupliquer", exact: true }).click()
  await expect(page.getByRole("group", { name: `Commandes pour ${copyList}`, exact: true })).toBeVisible()
  await card.getByRole("button", { name: "Archiver", exact: true }).click()
  await page.getByRole("dialog").getByRole("button", { name: "Archiver", exact: true }).click()
  await expect(card.getByRole("button", { name: "Modifier" })).toBeDisabled()
  await page.getByRole("tab", { name: "Priorités", exact: true }).click()
  await expect(page.getByRole("navigation", { name: "Pagination des prospects" })).toBeVisible()
  const main = page.locator("#dashboard-main")
  expect(await main.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
})
