import { expect, test } from "@playwright/test"

for (const role of ["owner", "accounting", "viewer", "sales"]) {
  test(`recurring invoices and selectors respect scope for ${role}`, async ({ page }, info) => {
    await page.context().clearCookies()
    await page.goto("/auth/login")
    await page.getByLabel("Adresse e-mail professionnelle").fill(`recurring-readers-${role}-${info.project.name}@example.test`)
    await page.getByLabel("Mot de passe", { exact: true }).fill(process.env.E2E_USER_PASSWORD || "RecetteSolide2026")
    await page.getByRole("button", { name: "Se connecter", exact: true }).click()
    await page.waitForURL(url => url.pathname === "/dashboard", { timeout: 60_000 })
    await page.goto("/dashboard/factures/recurrentes")
    if (role === "sales") {
      await expect(page.getByText("Accès Finance requis", { exact: true })).toBeVisible()
      await expect(page.getByRole("table")).toHaveCount(0)
      await expect(page.getByRole("button", { name: "Nouvelle récurrence", exact: true })).toHaveCount(0)
      return
    }
    await expect(page.getByRole("heading", { name: "Facturation récurrente", exact: true })).toBeVisible()
    await expect(page.getByRole("status")).toHaveText(role === "owner" ? "532 résultats" : "530 résultats")
    const table = page.getByRole("table")
    await expect(table.locator("tbody tr")).toHaveCount(25)
    await page.getByRole("button", { name: "Page suivante", exact: true }).click()
    await expect(page.getByText("Page 2 sur 22", { exact: true })).toBeVisible()
    await expect(table.getByText("Fictional recurrence 025", { exact: true })).toBeVisible()
    const search = page.getByRole("textbox", { name: "Rechercher une récurrence", exact: true })
    await search.fill("Fictional recurrence 529")
    await expect(page.getByRole("status")).toHaveText("1 résultat")
    await expect(table.getByText("Fictional recurrence 529", { exact: true })).toBeVisible()
    await search.fill("Fictional unassigned recurrence")
    await expect(page.getByRole("status")).toHaveText(role === "owner" ? "1 résultat" : "0 résultats")
    await search.fill("Fictional recurrence 000")
    await expect(page.getByRole("status")).toHaveText("1 résultat")
    const create = page.getByRole("button", { name: "Nouvelle récurrence", exact: true })
    if (role === "viewer") {
      await expect(create).toBeDisabled()
      await expect(table.getByRole("switch")).toBeDisabled()
      await expect(table.getByTitle("Supprimer", { exact: true })).toBeDisabled()
      return
    }
    await create.click()
    const dialog = page.getByRole("dialog")
    await dialog.getByLabel("Libellé *", { exact: true }).fill("Fictional unsaved recurrence")
    await dialog.getByLabel("Objet de la facture *", { exact: true }).fill("Fictional unsaved service")
    const clients = dialog.getByRole("group", { name: "Choix client", exact: true })
    const projects = dialog.getByRole("group", { name: "Choix chantier", exact: true })
    await clients.getByRole("textbox").fill("Fictional lookup client")
    await expect(clients.getByRole("status")).toHaveText("530 résultats")
    await clients.getByRole("button", { name: "Page suivante", exact: true }).click()
    await expect(clients.getByText("Page 2 sur 22", { exact: true })).toBeVisible()
    await clients.getByRole("textbox").fill("Fictional recurring client")
    await expect(clients.getByRole("status")).toHaveText("1 résultat")
    await clients.getByRole("combobox", { name: "Client", exact: true }).click()
    await page.getByRole("option", { name: "Fictional recurring client", exact: true }).click()
    await projects.getByRole("textbox").fill("Fictional recurring project")
    await expect(projects.getByRole("status")).toHaveText("1 résultat")
    await projects.getByRole("combobox", { name: "Chantier", exact: true }).click()
    await page.getByRole("option", { name: "Fictional recurring project", exact: true }).click()
    await projects.getByRole("textbox").fill("Fictional lookup project")
    await expect(projects.getByRole("status")).toHaveText("530 résultats")
    await projects.getByRole("button", { name: "Page suivante", exact: true }).click()
    await expect(projects.getByText("Page 2 sur 22", { exact: true })).toBeVisible()
    await expect(projects.getByRole("combobox", { name: "Chantier", exact: true })).toContainText("Fictional recurring project")
    await clients.getByRole("textbox").fill("Fictional lookup client 529")
    await expect(clients.getByRole("status")).toHaveText("1 résultat")
    await clients.getByRole("combobox", { name: "Client", exact: true }).click()
    await page.getByRole("option", { name: "Fictional lookup client 529", exact: true }).click()
    await expect(projects.getByRole("status")).toHaveText("0 résultats")
    await expect(projects.getByRole("combobox", { name: "Chantier", exact: true })).not.toContainText("Fictional recurring project")
    if (role === "accounting") await expect(dialog.getByRole("button", { name: "Créer", exact: true })).toBeDisabled()
    await expect(dialog.getByLabel("Libellé *", { exact: true })).toHaveValue("Fictional unsaved recurrence")
    await expect(dialog.getByLabel("Objet de la facture *", { exact: true })).toHaveValue("Fictional unsaved service")
    await dialog.getByRole("button", { name: "Annuler", exact: true }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual((page.viewportSize()?.width ?? 0) + 1)
  })
}
