import { expect, test } from "@playwright/test"

test("closes an unknown sequence result and repairs accepted history while keeping enrollment paused", async ({ page }, info) => {
  const open = async (kind: string) => {
    const subject = `UIQA Sequence recovery ${kind} ${info.project.name}`
    await page.goto("/dashboard/automatisations")
    await page.getByRole("tab", { name: /^Journal/ }).click()
    await page.getByRole("tab", { name: /E-mails/ }).click()
    await page.getByRole("textbox", { name: "Rechercher dans le journal", exact: true }).fill(subject)
    const rows = page.locator("[data-email-delivery]")
    await expect(rows).toHaveCount(1)
    await expect(rows).toContainText(subject)
    await rows.click()
    return page.getByRole("dialog", { name: subject, exact: true })
  }
  let dialog = await open("Unknown")
  await expect(dialog.getByRole("status")).toHaveText("Résultat inconnu")
  await dialog.getByRole("button", { name: "Vérifier le résultat", exact: true }).click()
  await expect(dialog).toContainText("Vérifiée le")
  await expect(dialog.getByRole("button", { name: "Classer sans relance", exact: true })).toBeDisabled()
  await dialog.getByRole("textbox", { name: "Motif du classement", exact: true }).fill("Décision fictive de recette")
  await dialog.getByRole("checkbox").check()
  await dialog.getByRole("button", { name: "Classer sans relance", exact: true }).click()
  await expect(dialog).toContainText("Classée sans relance")
  await expect(dialog).toContainText("Inscription : Arrêtée")
  await expect(dialog.getByRole("status")).toHaveText("Résultat inconnu")
  await expect(dialog.getByRole("button", { name: "Réessayer", exact: true })).toHaveCount(0)
  await page.keyboard.press("Escape")
  dialog = await open("Unknown")
  await expect(dialog).toContainText("Inscription : Arrêtée")
  await expect(dialog.getByRole("status")).toHaveText("Résultat inconnu")
  await page.keyboard.press("Escape")
  dialog = await open("Accepted")
  await expect(dialog.getByRole("status")).toHaveText("Acceptation confirmée")
  await dialog.getByRole("button", { name: "Réparer l’historique", exact: true }).click()
  await expect(page.getByText("Historique réparé ; inscription conservée en pause.", { exact: true })).toBeVisible()
  await expect(dialog).toContainText("Inscription : En pause")
  await expect(dialog.getByRole("button", { name: "Classer sans relance", exact: true })).toHaveCount(0)
  await page.keyboard.press("Escape")
  dialog = await open("Accepted")
  await expect(dialog.getByRole("status")).toHaveText("Acceptation confirmée")
  await expect(dialog).toContainText("Inscription : En pause")
})
