import { execFile } from "node:child_process"
import { promisify } from "node:util"
import { expect, test } from "@playwright/test"
const execute = promisify(execFile)

test("creates and simulates a persistent wait, resumes it, and reads the complete paged action journal", async ({ page }, info) => {
  const name = `UIQA Wait ${info.project.name}`
  await page.goto("/dashboard/automatisations")
  await page.getByRole("tab", { name: "Scénarios" }).click()
  const studio = page.getByRole("tabpanel", { name: "Scénarios" })
  await studio.getByRole("button", { name: "Nouveau scénario", exact: true }).click()
  await studio.getByLabel("Nom du scénario", { exact: true }).fill(name)
  await studio.getByLabel("Type d’action", { exact: true }).selectOption("WAIT")
  await studio.getByLabel("Durée de l’attente (heures)", { exact: true }).fill("1")
  await studio.getByLabel("Action après l’attente", { exact: true }).selectOption("CREATE_TASK")
  await studio.getByLabel("Titre", { exact: true }).fill(`Fictional wait task ${info.project.name}`)
  await studio.getByLabel("Délai", { exact: true }).fill("0")
  await studio.getByRole("button", { name: "Enregistrer le brouillon", exact: true }).click()
  await expect(page.getByText("Scénario créé en brouillon.", { exact: true })).toBeVisible()
  await studio.getByText(name, { exact: true }).first().click()
  const detail = studio.getByRole("heading", { name, exact: true }).locator("xpath=ancestor::section")
  await detail.locator('select[name="subjectId"]').selectOption({ index: 1 })
  await detail.getByRole("button", { name: "Simuler", exact: true }).click()
  await expect(detail).toContainText("Actions prévues : Attendre, Créer une tâche")
  await detail.getByRole("button", { name: "Publier et activer", exact: true }).click()
  await expect(page.getByText("Version publiée et scénario activé.", { exact: true }).last()).toBeVisible()
  const process = async (operation: string) => execute(globalThis.process.execPath, ["--conditions=react-server", "--import", "tsx", "scripts/verify-e2e-workflow-wait.mjs", name, operation], { timeout: 30_000 })
  await process("START")
  const openJournal = async () => {
    await page.reload()
    await page.getByRole("tab", { name: "Journal" }).click()
    await page.getByRole("tab", { name: /Exécutions/ }).click()
    await page.getByLabel("Rechercher une exécution", { exact: true }).fill(name)
    const result = page.getByRole("tabpanel", { name: /Exécutions/ }).locator("[data-workflow-run]")
    await expect(result).toHaveCount(1)
    await expect(result).toContainText(name)
  }
  await openJournal()
  const runs = page.getByRole("tabpanel", { name: /Exécutions/ }), row = runs.locator("[data-workflow-run]")
  await expect(row).toHaveCount(1)
  await expect(row.getByText("En attente", { exact: true })).toBeVisible()
  await expect(row).toContainText("Reprise :")
  await row.getByRole("button", { name: "Détails", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "Détails de l’exécution", exact: true })
  await expect(dialog).toContainText("Attente de 1 heure(s)")
  await expect(dialog).not.toContainText("Tâche enregistrée")
  await page.keyboard.press("Escape")
  await process("FINISH")
  await openJournal()
  await expect(row.getByText("Terminée", { exact: true })).toBeVisible()
  await row.getByRole("button", { name: "Détails", exact: true }).click()
  await expect(dialog).toContainText("Tâche enregistrée")
  await page.keyboard.press("Escape")
  await page.getByLabel("Rechercher une exécution", { exact: true }).fill(`UIQA Journal ${info.project.name}`)
  await expect(runs).toContainText("101 exécution(s) · Page 1 sur 5")
  await runs.getByRole("button", { name: "Page suivante : exécutions", exact: true }).click()
  await expect(runs).toContainText("Page 2 sur 5")
  await page.getByLabel("Rechercher une exécution", { exact: true }).fill(`UIQA_LAST_${info.project.name}`)
  await expect(row).toHaveCount(1)
  await row.getByRole("button", { name: "Détails", exact: true }).click()
  await expect(dialog).toContainText("Historique détaillé indisponible")
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => innerWidth))
})
