"use client"

import * as React from "react"
import { AlertTriangle, Check, Clock3, FileText, PackageCheck, Plus, RotateCcw, Send } from "lucide-react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"

import { acknowledgePurchaseOrder, approvePurchaseOrder, createSupplierReturn, creditSupplierReturn, receivePurchaseOrder, resolvePurchaseIssue, sendPurchaseOrder, submitPurchaseOrder } from "@/actions/operations"
import { Badge } from "@/components/ui/badge"
import { Button, buttonVariants } from "@/components/ui/button"
import { Dialog, DialogClose, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { PurchaseOrderDialog } from "./purchase-order-dialog"

type OperationsData = Awaited<ReturnType<typeof import("@/actions/operations").getOperationsDashboard>>
type PurchaseOrder = OperationsData["purchaseOrders"][number]
type PurchaseIssue = PurchaseOrder["issues"][number]
type SupplierReturn = PurchaseOrder["supplierReturns"][number]

const STATUS_LABELS: Record<string, string> = { DRAFT: "Brouillon", PENDING_APPROVAL: "À approuver", APPROVED: "Approuvée", SENT: "Envoyée", ACKNOWLEDGED: "Accusée", PARTIALLY_RECEIVED: "Réception partielle", RECEIVED: "Réceptionnée", RECEIVED_WITH_ISSUES: "Reçue avec anomalies", CANCELED: "Annulée" }
const ISSUE_LABELS: Record<string, string> = { DAMAGED: "Endommagé", MISSING: "Manquant", WRONG_ITEM: "Mauvaise référence", QUALITY: "Non-conforme", OTHER: "Autre" }

function money(cents: number) {
  return new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(cents / 100)
}

function date(value: Date | string | null) {
  return value ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(value)) : "—"
}

export function PurchaseWorkflow({ data }: { data: Pick<OperationsData, "purchaseOrders" | "suppliers" | "projects" | "products" | "warehouses" | "canApprovePurchases"> }) {
  const router = useRouter()
  const [pending, startTransition] = React.useTransition()
  const [createOpen, setCreateOpen] = React.useState(false)
  const [ackTarget, setAckTarget] = React.useState<PurchaseOrder | null>(null)
  const [receiptTarget, setReceiptTarget] = React.useState<PurchaseOrder | null>(null)
  const [issueTarget, setIssueTarget] = React.useState<PurchaseIssue | null>(null)
  const [returnTarget, setReturnTarget] = React.useState<PurchaseOrder | null>(null)
  const [creditTarget, setCreditTarget] = React.useState<SupplierReturn | null>(null)

  function mutate(operation: () => Promise<unknown>, success: string, close?: () => void) {
    startTransition(async () => {
      try {
        await operation()
        toast.success(success)
        close?.()
        router.refresh()
      } catch (error) {
        toast.error(error instanceof Error ? error.message : "Mise à jour impossible.")
      }
    })
  }

  return <section className="overflow-hidden rounded-xl border bg-card"><div className="flex flex-col gap-3 border-b px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold">Commandes fournisseur</h2><p className="mt-1 text-xs text-muted-foreground">Approbation, accusé, reliquats, anomalies et retours.</p></div><Button size="sm" onClick={() => setCreateOpen(true)}><Plus />Nouvelle commande</Button></div>
    <PurchaseOrderDialog open={createOpen} onOpenChange={setCreateOpen} suppliers={data.suppliers} projects={data.projects} products={data.products.map((product) => ({ id: product.id, sku: product.sku, label: product.label, purchasePriceCents: product.purchasePriceCents }))} />
    {data.purchaseOrders.length ? <div className="divide-y">{data.purchaseOrders.map((order) => {
      const expectedAt = order.confirmedExpectedAt || order.expectedAt
      const overdue = expectedAt && new Date(expectedAt) < new Date() && !["RECEIVED", "CANCELED"].includes(order.status)
      const remaining = order.lines.reduce((sum, line) => sum + Math.max(0, line.quantity - line.receivedQuantity - line.creditedQuantity), 0)
      return <article key={order.id} className="px-5 py-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><code className="text-xs font-semibold">{order.number}</code><Badge variant={order.status === "RECEIVED" ? "secondary" : order.status === "RECEIVED_WITH_ISSUES" || overdue ? "destructive" : "outline"}>{STATUS_LABELS[order.status] || order.status}</Badge>{overdue ? <Badge variant="destructive"><Clock3 />En retard</Badge> : null}</div><p className="mt-2 text-sm font-semibold">{order.supplier.name}</p><p className="mt-1 text-xs text-muted-foreground">{order.project?.name || "Approvisionnement général"} · Livraison {date(expectedAt)}{order.supplierReference ? ` · Réf. ${order.supplierReference}` : ""}</p>{order.approvedByMembership ? <p className="mt-1 text-xs text-muted-foreground">Approuvée par {order.approvedByMembership.user.name || order.approvedByMembership.user.email}</p> : null}</div><div className="text-left lg:text-right"><p className="font-semibold tabular-nums">{money(order.totalHtCents)} HT</p><p className="mt-1 text-xs text-muted-foreground">{remaining} unité{remaining > 1 ? "s" : ""} en reliquat</p></div></div>
        <div className="mt-4 overflow-hidden rounded-lg border"><div className="divide-y">{order.lines.map((line) => <div key={line.id} className="grid gap-2 px-3 py-2.5 text-xs sm:grid-cols-[minmax(0,1fr)_120px_120px]"><div><span className="font-medium">{line.product?.sku ? `${line.product.sku} · ` : ""}{line.label}</span></div><span className="tabular-nums text-muted-foreground">{line.receivedQuantity} reçue · {line.creditedQuantity} créditée / {line.quantity}</span><span className="tabular-nums sm:text-right">{money(line.quantity * line.unitPriceCents)}</span></div>)}</div></div>
        <div className="mt-3 flex flex-wrap gap-2"><a href={`/api/pdf/achat/${order.id}`} target="_blank" rel="noreferrer" className={buttonVariants({ variant: "outline", size: "sm" })}><FileText />PDF</a>{order.status === "DRAFT" ? <Button size="sm" variant="outline" disabled={pending} onClick={() => mutate(() => submitPurchaseOrder(order.id), "Commande soumise pour approbation.")}><Send />Soumettre</Button> : null}{order.status === "PENDING_APPROVAL" && data.canApprovePurchases ? <Button size="sm" disabled={pending} onClick={() => mutate(() => approvePurchaseOrder(order.id), "Commande approuvée.")}><Check />Approuver</Button> : null}{order.status === "APPROVED" ? <Button size="sm" disabled={pending} onClick={() => mutate(() => sendPurchaseOrder(order.id), "Commande marquée comme envoyée.")}><Send />Marquer envoyée</Button> : null}{["SENT", "ACKNOWLEDGED"].includes(order.status) ? <Button size="sm" variant="outline" disabled={pending} onClick={() => setAckTarget(order)}>Accusé fournisseur</Button> : null}{["SENT", "ACKNOWLEDGED", "PARTIALLY_RECEIVED", "RECEIVED_WITH_ISSUES"].includes(order.status) && remaining ? <Button size="sm" variant="outline" disabled={pending} onClick={() => setReceiptTarget(order)}><PackageCheck />Réceptionner</Button> : null}{order.lines.some((line) => line.receivedQuantity > line.supplierReturns.reduce((sum, item) => sum + item.quantity, 0)) ? <Button size="sm" variant="outline" disabled={pending} onClick={() => setReturnTarget(order)}><RotateCcw />Retour fournisseur</Button> : null}</div>
        {order.issues.length ? <div className="mt-4 space-y-2 border-t pt-3"><p className="text-xs font-semibold">Anomalies de réception</p>{order.issues.map((issue) => <div key={issue.id} className="flex flex-col gap-2 rounded-lg bg-warning/5 px-3 py-2.5 text-xs sm:flex-row sm:items-center"><AlertTriangle className="size-4 shrink-0 text-warning" /><span className="min-w-0 flex-1"><strong>{ISSUE_LABELS[issue.type] || issue.type}</strong> · {issue.quantity} × {issue.product?.label || issue.purchaseOrderLine.label}{issue.notes ? ` · ${issue.notes}` : ""}</span><Badge variant="outline">{issue.status === "WAITING_REPLACEMENT" ? "Remplacement attendu" : issue.status === "RESOLVED" ? "Résolue" : "Ouverte"}</Badge>{issue.status !== "RESOLVED" ? <Button size="sm" variant="outline" onClick={() => setIssueTarget(issue)}>Traiter</Button> : null}</div>)}</div> : null}
        {order.supplierReturns.length ? <div className="mt-4 space-y-2 border-t pt-3"><p className="text-xs font-semibold">Retours expédiés</p>{order.supplierReturns.map((item) => <div key={item.id} className="flex flex-col gap-2 rounded-lg bg-muted/50 px-3 py-2.5 text-xs sm:flex-row sm:items-center"><RotateCcw className="size-4 shrink-0" /><span className="min-w-0 flex-1"><strong>{item.number}</strong> · {item.quantity} × {item.product.label} · {item.warehouse.name} · {item.reason}</span><Badge variant="outline">{item.status === "CREDITED" ? "Crédité" : "Expédié"}</Badge>{item.status === "SHIPPED" ? <Button size="sm" variant="outline" onClick={() => setCreditTarget(item)}>Enregistrer l’avoir</Button> : null}</div>)}</div> : null}
      </article>
    })}</div> : <p className="px-5 py-10 text-sm text-muted-foreground">Aucune commande fournisseur.</p>}

    <Dialog open={Boolean(ackTarget)} onOpenChange={(open) => { if (!open) setAckTarget(null) }}><DialogContent><DialogHeader><DialogTitle>Accusé fournisseur</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (!ackTarget) return; const form = new FormData(event.currentTarget); mutate(() => acknowledgePurchaseOrder({ purchaseOrderId: ackTarget.id, supplierReference: String(form.get("supplierReference")), confirmedExpectedAt: String(form.get("confirmedExpectedAt")) }), "Accusé fournisseur enregistré.", () => setAckTarget(null)) }}><div className="space-y-1.5"><Label htmlFor="supplierReference">Référence fournisseur</Label><Input id="supplierReference" name="supplierReference" required defaultValue={ackTarget?.supplierReference || ""} /></div><div className="space-y-1.5"><Label htmlFor="confirmedExpectedAt">Date confirmée</Label><Input id="confirmedExpectedAt" name="confirmedExpectedAt" type="date" required defaultValue={ackTarget?.confirmedExpectedAt ? new Date(ackTarget.confirmedExpectedAt).toISOString().slice(0, 10) : ""} /></div><DialogFooter><DialogClose render={<Button type="button" variant="outline" />}>Annuler</DialogClose><Button type="submit" disabled={pending}>Enregistrer</Button></DialogFooter></form></DialogContent></Dialog>

    <Dialog open={Boolean(receiptTarget)} onOpenChange={(open) => { if (!open) setReceiptTarget(null) }}><DialogContent><DialogHeader><DialogTitle>Réception fournisseur</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (!receiptTarget) return; const form = new FormData(event.currentTarget); mutate(() => receivePurchaseOrder({ purchaseOrderId: receiptTarget.id, purchaseOrderLineId: String(form.get("purchaseOrderLineId")), warehouseId: String(form.get("warehouseId")), quantity: Number(form.get("quantity")), rejectedQuantity: Number(form.get("rejectedQuantity") || 0), issueType: String(form.get("issueType") || "") || null, issueNotes: String(form.get("issueNotes") || ""), supplierReference: String(form.get("supplierReference") || ""), notes: String(form.get("notes") || "") }), "Réception et stock enregistrés.", () => setReceiptTarget(null)) }}><label className="space-y-1.5 text-sm font-medium">Ligne<select name="purchaseOrderLineId" required className="mt-1 h-10 w-full rounded-[10px] border bg-background px-3 text-sm"><option value="">Sélectionner…</option>{receiptTarget?.lines.filter((line) => line.receivedQuantity + line.creditedQuantity < line.quantity).map((line) => <option key={line.id} value={line.id}>{line.label} · reste {line.quantity - line.receivedQuantity - line.creditedQuantity}</option>)}</select></label><label className="space-y-1.5 text-sm font-medium">Dépôt<select name="warehouseId" required className="mt-1 h-10 w-full rounded-[10px] border bg-background px-3 text-sm"><option value="">Sélectionner…</option>{data.warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><div className="space-y-1.5"><Label htmlFor="receiptQuantity">Quantité livrée</Label><Input id="receiptQuantity" name="quantity" type="number" min="1" required /></div><div className="space-y-1.5"><Label htmlFor="rejectedQuantity">Dont rejetée</Label><Input id="rejectedQuantity" name="rejectedQuantity" type="number" min="0" defaultValue="0" /></div></div><label className="space-y-1.5 text-sm font-medium">Type d’anomalie<select name="issueType" className="mt-1 h-10 w-full rounded-[10px] border bg-background px-3 text-sm"><option value="">Aucune</option>{Object.entries(ISSUE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="space-y-1.5"><Label htmlFor="issueNotes">Détail de l’anomalie</Label><Input id="issueNotes" name="issueNotes" /></div><div className="space-y-1.5"><Label htmlFor="receiptSupplierReference">Bon fournisseur</Label><Input id="receiptSupplierReference" name="supplierReference" /></div><DialogFooter><DialogClose render={<Button type="button" variant="outline" />}>Annuler</DialogClose><Button type="submit" disabled={pending}>Enregistrer la réception</Button></DialogFooter></form></DialogContent></Dialog>

    <Dialog open={Boolean(issueTarget)} onOpenChange={(open) => { if (!open) setIssueTarget(null) }}><DialogContent><DialogHeader><DialogTitle>Traiter l’anomalie fournisseur</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (!issueTarget) return; const form = new FormData(event.currentTarget); mutate(() => resolvePurchaseIssue({ issueId: issueTarget.id, resolution: String(form.get("resolution")), notes: String(form.get("notes")) }), "Anomalie fournisseur mise à jour.", () => setIssueTarget(null)) }}><label className="space-y-1.5 text-sm font-medium">Décision<select name="resolution" required className="mt-1 h-10 w-full rounded-[10px] border bg-background px-3 text-sm"><option value="REPLACEMENT">Remplacement attendu</option><option value="CREDIT">Avoir fournisseur</option><option value="ACCEPTED">Accepté après contrôle</option><option value="OTHER">Autre résolution</option></select></label><div className="space-y-1.5"><Label htmlFor="issueResolutionNotes">Détail / preuve</Label><Input id="issueResolutionNotes" name="notes" required /></div><DialogFooter><DialogClose render={<Button type="button" variant="outline" />}>Annuler</DialogClose><Button type="submit" disabled={pending}>Valider</Button></DialogFooter></form></DialogContent></Dialog>

    <Dialog open={Boolean(returnTarget)} onOpenChange={(open) => { if (!open) setReturnTarget(null) }}><DialogContent><DialogHeader><DialogTitle>Retour fournisseur</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (!returnTarget) return; const form = new FormData(event.currentTarget); mutate(() => createSupplierReturn({ purchaseOrderId: returnTarget.id, purchaseOrderLineId: String(form.get("purchaseOrderLineId")), warehouseId: String(form.get("warehouseId")), quantity: Number(form.get("quantity")), reason: String(form.get("reason")), notes: String(form.get("notes") || "") }), "Retour fournisseur expédié et stock décrémenté.", () => setReturnTarget(null)) }}><label className="space-y-1.5 text-sm font-medium">Ligne reçue<select name="purchaseOrderLineId" required className="mt-1 h-10 w-full rounded-[10px] border bg-background px-3 text-sm"><option value="">Sélectionner…</option>{returnTarget?.lines.filter((line) => line.productId && line.receivedQuantity > line.supplierReturns.reduce((sum, item) => sum + item.quantity, 0)).map((line) => <option key={line.id} value={line.id}>{line.label} · retournable {line.receivedQuantity - line.supplierReturns.reduce((sum, item) => sum + item.quantity, 0)}</option>)}</select></label><label className="space-y-1.5 text-sm font-medium">Dépôt<select name="warehouseId" required className="mt-1 h-10 w-full rounded-[10px] border bg-background px-3 text-sm"><option value="">Sélectionner…</option>{data.warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><div className="space-y-1.5"><Label htmlFor="returnQuantity">Quantité</Label><Input id="returnQuantity" name="quantity" type="number" min="1" required /></div><div className="space-y-1.5"><Label htmlFor="returnReason">Motif</Label><Input id="returnReason" name="reason" required /></div><div className="space-y-1.5"><Label htmlFor="returnNotes">Notes</Label><Input id="returnNotes" name="notes" /></div><DialogFooter><DialogClose render={<Button type="button" variant="outline" />}>Annuler</DialogClose><Button type="submit" disabled={pending}>Expédier le retour</Button></DialogFooter></form></DialogContent></Dialog>

    <Dialog open={Boolean(creditTarget)} onOpenChange={(open) => { if (!open) setCreditTarget(null) }}><DialogContent><DialogHeader><DialogTitle>Avoir du retour {creditTarget?.number}</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (!creditTarget) return; const form = new FormData(event.currentTarget); mutate(() => creditSupplierReturn(creditTarget.id, String(form.get("creditReference"))), "Avoir fournisseur rattaché au retour.", () => setCreditTarget(null)) }}><div className="space-y-1.5"><Label htmlFor="returnCreditReference">Référence de l’avoir</Label><Input id="returnCreditReference" name="creditReference" required /></div><DialogFooter><DialogClose render={<Button type="button" variant="outline" />}>Annuler</DialogClose><Button type="submit" disabled={pending}>Enregistrer l’avoir</Button></DialogFooter></form></DialogContent></Dialog>
  </section>
}
