import { BarChart3, Calculator, ChartNoAxesCombined, CircleDollarSign, HardHat, Headphones, Target } from "lucide-react"
import { getWorkspaceOverview } from "@/actions/workspaces"
import { OnboardingRequired } from "@/components/shared/onboarding-required"
import { WorkspaceHub, formatWorkspaceEuro } from "@/app/dashboard/_components/workspace-hub"

export default async function ReportsWorkspacePage() {
  const data = await getWorkspaceOverview()
  if (!data) return <OnboardingRequired title="Configurez votre espace" description="Créez le profil entreprise avant de consulter les rapports." />
  return <WorkspaceHub eyebrow="Espace reporting" title="Piloter l’entreprise" description="Une lecture transversale des ventes, opérations, revenus et objectifs à approfondir avec les rapports personnalisés." metrics={[{ label: "Pipeline", value: formatWorkspaceEuro(data.openDealValueCents), detail: `${data.openDeals} affaire(s) ouverte(s)` }, { label: "À encaisser", value: formatWorkspaceEuro(data.outstandingCents), detail: `${data.overdueInvoices} facture(s) en retard`, alert: data.overdueInvoices > 0 }, { label: "Chantiers actifs", value: data.activeProjects, detail: `${data.scheduledInterventions} intervention(s)` }, { label: "Actions proches", value: data.dueTasks, detail: "À réaliser sous 48 heures", alert: data.dueTasks > 0 }]} sections={[{ title: "Performance commerciale", description: "Comprendre le volume, la valeur et la conversion.", links: [{ name: "Vue d'ensemble", href: "/dashboard", icon: BarChart3, description: "Indicateurs opérationnels du jour." }, { name: "Pipeline et forecast", href: "/dashboard/pipeline", icon: ChartNoAxesCombined, description: "Valeur pondérée, responsables et clôtures." }, { name: "Objectifs", href: "/dashboard/organisation", icon: Target, description: "Progression et priorités partagées." }] }, { title: "Rentabilité", description: "Relier le vendu, le réalisé et l'encaissé.", links: [{ name: "Revenus", href: "/dashboard/revenue", icon: CircleDollarSign, description: "Facturation, paiements et trésorerie." }, { name: "Chantiers", href: "/dashboard/projets", icon: HardHat, description: "Budgets, temps et coûts terrain." }, { name: "Exports comptables", href: "/dashboard/comptabilite", icon: Calculator, description: "Journaux et contrôle des écritures." }] }, { title: "Qualité de service", description: "Mesurer délais, charge, diagnostics et fidélisation.", links: [{ name: "Analyses Service", href: "/dashboard/service/analytics", icon: Headphones, description: "SLA, équipe, satisfaction et santé client." }] }]} />
}
