import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowLeft, Building2, Inbox, Mail, Phone, Send, ShieldCheck, UserRoundSearch } from "lucide-react"

import { getContactDetail } from "@/actions/contacts"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

function formatDate(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) }

export default async function ContactDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const contact = await getContactDetail((await params).id)
  if (!contact) notFound()
  const sent = contact.sequenceEnrollments.flatMap((item) => item.deliveries).filter((item) => item.status !== "SCHEDULED").length
  const activeSequences = contact.sequenceEnrollments.filter((item) => item.status === "ACTIVE").length
  const latestConsent = contact.marketingConsents[0]

  return <div className="space-y-7">
    <header className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="flex items-start gap-3"><Button nativeButton={false} variant="ghost" size="icon" render={<Link href="/dashboard/contacts" />} aria-label="Retour aux contacts"><ArrowLeft /></Button><div><div className="flex flex-wrap items-center gap-2"><h1>{contact.firstName} {contact.lastName}</h1>{contact.isPrimary && <Badge variant="secondary">Contact principal</Badge>}{contact.lifecycleStage && <Badge variant="outline">{contact.lifecycleStage}</Badge>}</div><p className="mt-2 text-sm text-muted-foreground">{contact.role || "Fonction non renseignée"} · <Link href={`/dashboard/clients/${contact.client.id}`} className="font-medium text-foreground hover:text-primary hover:underline">{contact.client.name}</Link></p></div></div><div className="flex flex-wrap gap-2">{contact.phone && <Button nativeButton={false} variant="outline" render={<a href={`tel:${contact.phone}`} />}><Phone />Appeler</Button>}{contact.email && <Button nativeButton={false} render={<a href={`mailto:${contact.email}`} />}><Mail />Écrire</Button>}</div></header>

    <section className="grid overflow-hidden rounded-xl border bg-card sm:grid-cols-2 xl:grid-cols-4"><Metric label="Conversations" value={contact.emailThreads.length} detail="Fils rattachés" /><Metric label="E-mails envoyés" value={sent} detail="Via les séquences" /><Metric label="Séquences actives" value={activeSequences} detail="Suivis en cours" /><Metric label="Accès portail" value={contact.portalAccesses.length} detail="Liens actifs" /></section>

    <div className="grid gap-6 xl:grid-cols-[0.82fr_1.18fr]">
      <div className="space-y-6">
        <Card><CardHeader><CardTitle className="text-base">Coordonnées et client</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Info icon={Building2} label="Client"><Link href={`/dashboard/clients/${contact.client.id}`} className="font-medium hover:text-primary hover:underline">{contact.client.name}</Link></Info><Info icon={Mail} label="E-mail">{contact.email || "Non renseigné"}</Info><Info icon={Phone} label="Téléphone">{contact.phone || "Non renseigné"}</Info>{contact.client.address && <p className="rounded-lg bg-muted/45 p-3 text-xs leading-5 text-muted-foreground">{contact.client.address}</p>}{contact.client.nextActionLabel && <div className="rounded-lg border p-3"><p className="text-xs font-semibold">Prochaine action</p><p className="mt-1 text-sm">{contact.client.nextActionLabel}</p>{contact.client.nextActionAt && <p className="mt-1 text-xs text-muted-foreground">{formatDate(contact.client.nextActionAt)}</p>}</div>}</CardContent></Card>
        <Card><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-base">Consentement</CardTitle><ShieldCheck className="size-4 text-primary" /></div><CardDescription>Dernières preuves enregistrées pour cet interlocuteur.</CardDescription></CardHeader><CardContent>{latestConsent ? <div><Badge variant={latestConsent.status === "WITHDRAWN" ? "destructive" : "secondary"}>{latestConsent.status}</Badge><p className="mt-3 text-sm font-medium">{latestConsent.channel} · {latestConsent.purpose}</p><p className="mt-1 text-xs text-muted-foreground">{latestConsent.source} · {formatDate(latestConsent.capturedAt)}</p><p className="mt-3 break-all font-mono text-[10px] text-muted-foreground">Preuve {latestConsent.proofHash.slice(0, 20)}…</p></div> : <p className="text-sm text-muted-foreground">Aucune preuve de consentement rattachée.</p>}</CardContent></Card>
      </div>

      <div className="space-y-6">
        <Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="text-base">Conversations</CardTitle><CardDescription>Derniers fils e-mail associés au contact.</CardDescription></div><Inbox className="size-4 text-primary" /></div></CardHeader><CardContent>{contact.emailThreads.length ? <div className="divide-y rounded-lg border">{contact.emailThreads.map((thread) => <Link key={thread.id} href="/dashboard/communications" className="flex items-center gap-3 p-3 transition-colors hover:bg-muted/35"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><Mail className="size-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{thread.subject}</span><span className="mt-0.5 block text-xs text-muted-foreground">{thread.messages[0]?.subject || "Aucun message"} · {formatDate(thread.lastMessageAt)}</span></span>{thread.unreadCount > 0 && <Badge>{thread.unreadCount}</Badge>}</Link>)}</div> : <p className="rounded-lg border border-dashed p-5 text-sm text-muted-foreground">Aucune conversation rattachée.</p>}</CardContent></Card>
        <Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="text-base">Séquences et campagnes</CardTitle><CardDescription>Inscriptions, progression et derniers envois.</CardDescription></div><Send className="size-4 text-primary" /></div></CardHeader><CardContent>{contact.sequenceEnrollments.length ? <div className="space-y-3">{contact.sequenceEnrollments.map((enrollment) => <div key={enrollment.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold">{enrollment.sequence.name}</p><Badge variant={enrollment.status === "ACTIVE" ? "default" : "outline"}>{enrollment.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">Étape {enrollment.nextStepPosition + 1} · inscrit le {formatDate(enrollment.enrolledAt)}</p>{enrollment.deliveries.at(-1) && <p className="mt-3 rounded-md bg-muted/45 p-2 text-xs">{enrollment.deliveries.at(-1)?.subject} · {enrollment.deliveries.at(-1)?.status}</p>}</div>)}</div> : <p className="rounded-lg border border-dashed p-5 text-sm text-muted-foreground">Aucune séquence rattachée.</p>}</CardContent></Card>
        <Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="text-base">Origine et parcours</CardTitle><CardDescription>Demandes ayant créé ou enrichi ce contact.</CardDescription></div><UserRoundSearch className="size-4 text-primary" /></div></CardHeader><CardContent>{contact.leadCaptures.length ? <div className="divide-y rounded-lg border">{contact.leadCaptures.map((lead) => <div key={lead.id} className="p-3"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{lead.source}</Badge><Badge variant="secondary">{lead.status}</Badge><span className="ml-auto text-xs text-muted-foreground">{formatDate(lead.createdAt)}</span></div><p className="mt-2 text-sm font-medium">{lead.projectType || "Projet non précisé"}</p>{lead.utmCampaign && <p className="mt-1 text-xs text-muted-foreground">Campagne : {lead.utmCampaign}{lead.utmSource ? ` · ${lead.utmSource}` : ""}</p>}</div>)}</div> : <p className="rounded-lg border border-dashed p-5 text-sm text-muted-foreground">Aucune demande source rattachée.</p>}</CardContent></Card>
      </div>
    </div>
  </div>
}

function Metric({ label, value, detail }: { label: string; value: number; detail: string }) { return <div className="border-t p-5 first:border-t-0 sm:border-l sm:border-t-0 sm:first:border-l-0"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div> }
function Info({ icon: Icon, label, children }: { icon: typeof Mail; label: string; children: React.ReactNode }) { return <div className="grid grid-cols-[20px_90px_minmax(0,1fr)] items-start gap-2"><Icon className="mt-0.5 size-4 text-muted-foreground" /><span className="text-xs text-muted-foreground">{label}</span><span className="min-w-0 break-words">{children}</span></div> }
