export type ContractTemplateCategory =
  | "prestation"
  | "maintenance"
  | "conseil"
  | "creation"
  | "data"
  | "juridique"
  | "operation"

export type ContractTemplatePreset = {
  id: string
  name: string
  category: ContractTemplateCategory
  title: string
  description: string
  bestFor: string
  sections: number
  content: string
}

export type ContractClausePreset = {
  id: string
  title: string
  description: string
  content: string
}

export const CONTRACT_TEMPLATE_CATEGORY_LABELS: Record<ContractTemplateCategory, string> = {
  prestation: "Prestation",
  maintenance: "Maintenance",
  conseil: "Conseil",
  creation: "Création",
  data: "Data/RGPD",
  juridique: "Juridique",
  operation: "Opération",
}

const FRENCH_LEGAL_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bAccord de confidentialite\b/g, "Accord de confidentialité"],
  [/\bConfidentialite\b/g, "Confidentialité"],
  [/\bconfidentialite\b/g, "confidentialité"],
  [/\bDonnees personnelles\b/g, "Données personnelles"],
  [/\bdonnees personnelles\b/g, "données personnelles"],
  [/\bdonnees\b/g, "données"],
  [/\bDonnees\b/g, "Données"],
  [/\bPropriete intellectuelle\b/g, "Propriété intellectuelle"],
  [/\bpropriete intellectuelle\b/g, "propriété intellectuelle"],
  [/\bpropriete\b/g, "propriété"],
  [/\bPropriete\b/g, "Propriété"],
  [/\bResponsabilite\b/g, "Responsabilité"],
  [/\bresponsabilite\b/g, "responsabilité"],
  [/\bSecurite\b/g, "Sécurité"],
  [/\bsecurite\b/g, "sécurité"],
  [/\bDuree\b/g, "Durée"],
  [/\bduree\b/g, "durée"],
  [/\bResiliation\b/g, "Résiliation"],
  [/\bresiliation\b/g, "résiliation"],
  [/\bReversibilite\b/g, "Réversibilité"],
  [/\breversibilite\b/g, "réversibilité"],
  [/\bPerimetre\b/g, "Périmètre"],
  [/\bperimetre\b/g, "périmètre"],
  [/\bEcheance\b/g, "Échéance"],
  [/\becheances\b/g, "échéances"],
  [/\becheance\b/g, "échéance"],
  [/\bdelais\b/g, "délais"],
  [/\bdelai\b/g, "délai"],
  [/\betapes\b/g, "étapes"],
  [/\betape\b/g, "étape"],
  [/\bmodalites\b/g, "modalités"],
  [/\bModalites\b/g, "Modalités"],
  [/\bnecessaires\b/g, "nécessaires"],
  [/\bnecessaire\b/g, "nécessaire"],
  [/\bnecessite\b/g, "nécessite"],
  [/\bnecessitent\b/g, "nécessitent"],
  [/\bspecifiques\b/g, "spécifiques"],
  [/\bspecifique\b/g, "spécifique"],
  [/\bgeneriques\b/g, "génériques"],
  [/\bgenerique\b/g, "générique"],
  [/\bpreexistants\b/g, "préexistants"],
  [/\bpreexistant\b/g, "préexistant"],
  [/\bprealable\b/g, "préalable"],
  [/\bprealables\b/g, "préalables"],
  [/\bseparee\b/g, "séparée"],
  [/\bsepare\b/g, "séparé"],
  [/\bcomplementaires\b/g, "complémentaires"],
  [/\bcomplementaire\b/g, "complémentaire"],
  [/\brealisees\b/g, "réalisées"],
  [/\brealises\b/g, "réalisés"],
  [/\brealisee\b/g, "réalisée"],
  [/\brealise\b/g, "réalisé"],
  [/\brealiser\b/g, "réaliser"],
  [/\bcrees\b/g, "créés"],
  [/\bcreee\b/g, "créée"],
  [/\bcree\b/g, "créé"],
  [/\bcedees\b/g, "cédées"],
  [/\bcedes\b/g, "cédés"],
  [/\bcedee\b/g, "cédée"],
  [/\bcede\b/g, "cède"],
  [/\bprotegees\b/g, "protégées"],
  [/\bproteges\b/g, "protégés"],
  [/\bprotegee\b/g, "protégée"],
  [/\bproteger\b/g, "protéger"],
  [/\bprotege\b/g, "protège"],
  [/\bechangees\b/g, "échangées"],
  [/\bechanges\b/g, "échanges"],
  [/\bechange\b/g, "échange"],
  [/\becrit\b/g, "écrit"],
  [/\becrite\b/g, "écrite"],
  [/\becrites\b/g, "écrites"],
  [/\becrits\b/g, "écrits"],
  [/\bexecution\b/g, "exécution"],
  [/\bExecution\b/g, "Exécution"],
  [/\bdebut\b/g, "début"],
  [/\bdeja\b/g, "déjà"],
  [/\bete\b/g, "été"],
  [/\bintégral\b/g, "intégral"],
  [/\bintegral\b/g, "intégral"],
  [/\binterne\b/g, "interne"],
  [/\bexternes\b/g, "externes"],
  [/\bfrancais\b/g, "français"],
  [/\bFrançais\b/g, "Français"],
  [/\bstrategiques\b/g, "stratégiques"],
  [/\bstrategie\b/g, "stratégie"],
  [/\bStrategie\b/g, "Stratégie"],
  [/\bfinancieres\b/g, "financières"],
  [/\beconomiques\b/g, "économiques"],
  [/\bmethodologie\b/g, "méthodologie"],
  [/\bmethodes\b/g, "méthodes"],
  [/\bmethode\b/g, "méthode"],
  [/\bMethodologie\b/g, "Méthodologie"],
  [/\bbibliotheques\b/g, "bibliothèques"],
  [/\bmodeles\b/g, "modèles"],
  [/\bModele\b/g, "Modèle"],
  [/\bmodele\b/g, "modèle"],
  [/\bDeveloppement\b/g, "Développement"],
  [/\bdeveloppement\b/g, "développement"],
  [/\bdevelopper\b/g, "développer"],
  [/\bdeploiement\b/g, "déploiement"],
  [/\bevolutive\b/g, "évolutive"],
  [/\bevolutif\b/g, "évolutif"],
  [/\bevolutions\b/g, "évolutions"],
  [/\bevolution\b/g, "évolution"],
  [/\bhebergement\b/g, "hébergement"],
  [/\bhebergeur\b/g, "hébergeur"],
  [/\bediteurs\b/g, "éditeurs"],
  [/\bediteur\b/g, "éditeur"],
  [/\bequipe\b/g, "équipe"],
  [/\bEquipe\b/g, "Équipe"],
  [/\bidentite\b/g, "identité"],
  [/\bIdentite\b/g, "Identité"],
  [/\bcreation\b/g, "création"],
  [/\bCreation\b/g, "Création"],
  [/\bdeclinaisons\b/g, "déclinaisons"],
  [/\bvisuels\b/g, "visuels"],
  [/\bIterations\b/g, "Itérations"],
  [/\bIteration\b/g, "Itération"],
  [/\biterations\b/g, "itérations"],
  [/\biteration\b/g, "itération"],
  [/\bpreparation\b/g, "préparation"],
  [/\bpresent\b/g, "présent"],
  [/\bPresent\b/g, "Présent"],
  [/\bprevues\b/g, "prévues"],
  [/\bprevus\b/g, "prévus"],
  [/\bprevue\b/g, "prévue"],
  [/\bprevu\b/g, "prévu"],
  [/\bevaluations\b/g, "évaluations"],
  [/\bevaluation\b/g, "évaluation"],
  [/\bintegration\b/g, "intégration"],
  [/\bintegrations\b/g, "intégrations"],
  [/\bmetier\b/g, "métier"],
  [/\bmetiers\b/g, "métiers"],
  [/\brecurrentes\b/g, "récurrentes"],
  [/\brecurrent\b/g, "récurrent"],
  [/\bsystemes\b/g, "systèmes"],
  [/\bsysteme\b/g, "système"],
  [/\bdemarrage\b/g, "démarrage"],
  [/\bdepassements\b/g, "dépassements"],
  [/\bdepassement\b/g, "dépassement"],
  [/\bechues\b/g, "échues"],
  [/\bechue\b/g, "échue"],
  [/\breglementaires\b/g, "réglementaires"],
  [/\breglementaire\b/g, "réglementaire"],
  [/\breglement\b/g, "règlement"],
  [/\butilisees\b/g, "utilisées"],
  [/\butilises\b/g, "utilisés"],
  [/\butilisee\b/g, "utilisée"],
  [/\butilise\b/g, "utilisé"],
  [/\binterpretation\b/g, "interprétation"],
  [/\bdifferend\b/g, "différend"],
  [/\bperiodicite\b/g, "périodicité"],
  [/\bperiode\b/g, "période"],
  [/\bpenalites\b/g, "pénalités"],
  [/\bdisponibilite\b/g, "disponibilité"],
  [/\bactivites\b/g, "activités"],
  [/\bactivite\b/g, "activité"],
  [/\bqualite\b/g, "qualité"],
  [/\bregles\b/g, "règles"],
  [/\breponse\b/g, "réponse"],
  [/\brole\b/g, "rôle"],
  [/\broles\b/g, "rôles"],
  [/\bindependance\b/g, "indépendance"],
  [/\bindependant\b/g, "indépendant"],
  [/\bindependamment\b/g, "indépendamment"],
  [/\bintegre\b/g, "intégré"],
  [/\bcoopere\b/g, "coopère"],
  [/\bcooperer\b/g, "coopérer"],
  [/\bcooperation\b/g, "coopération"],
  [/\bnotifiee\b/g, "notifiée"],
  [/\bdecisions\b/g, "décisions"],
  [/\bdecision\b/g, "décision"],
  [/\bdefinies\b/g, "définies"],
  [/\bdefinis\b/g, "définis"],
  [/\bdefinir\b/g, "définir"],
  [/\bdefaut\b/g, "défaut"],
  [/\bdiscussions\b/g, "discussions"],
  [/\bnegociations\b/g, "négociations"],
  [/\bconformite\b/g, "conformité"],
  [/\blicite\b/g, "licite"],
  [/\brecus\b/g, "reçus"],
  [/\boperationnelles\b/g, "opérationnelles"],
  [/\boperationnel\b/g, "opérationnel"],
  [/\bOperation\b/g, "Opération"],
  [/\boperation\b/g, "opération"],
  [/\btracabilite\b/g, "traçabilité"],
  [/\bopportunites\b/g, "opportunités"],
  [/\bpresentees\b/g, "présentées"],
  [/\bpresente\b/g, "présente"],
  [/\bderoulement\b/g, "déroulement"],
  [/\bmise a jour\b/g, "mise à jour"],
  [/\ba disposition\b/g, "à disposition"],
  [/\ba defaut\b/g, "à défaut"],
  [/\ba compter\b/g, "à compter"],
  [/\ba titre\b/g, "à titre"],
  [/\ba la fin\b/g, "à la fin"],
  [/\ba l'issue\b/g, "à l'issue"],
  [/\bci-apres\b/g, "ci-après"],
  [/\bvis-a-vis\b/g, "vis-à-vis"],
  [/\bimmatriculee\b/g, "immatriculée"],
  [/\bsoussignes\b/g, "soussignés"],
  [/\bnumerisee\b/g, "numérisée"],
  [/\belectronique\b/g, "électronique"],
]

function formatFrenchLegalText(value: string) {
  return FRENCH_LEGAL_REPLACEMENTS.reduce(
    (text, [pattern, replacement]) => text.replace(pattern, replacement),
    value
  )
}

function formatTemplatePreset(template: ContractTemplatePreset): ContractTemplatePreset {
  return {
    ...template,
    name: formatFrenchLegalText(template.name),
    title: formatFrenchLegalText(template.title),
    description: formatFrenchLegalText(template.description),
    bestFor: formatFrenchLegalText(template.bestFor),
    content: formatFrenchLegalText(template.content),
  }
}

function formatClausePreset(clause: ContractClausePreset): ContractClausePreset {
  return {
    ...clause,
    title: formatFrenchLegalText(clause.title),
    description: formatFrenchLegalText(clause.description),
    content: formatFrenchLegalText(clause.content),
  }
}

const parties = `
<p><strong>Entre les soussignés :</strong></p>
<p>{{entreprise.name}}, immatriculee sous le SIRET {{entreprise.siret}}, ci-apres "le Prestataire",</p>
<p>Et {{client.name}}, ci-apres "le Client".</p>
<p>Les Parties conviennent ce qui suit.</p>
`

function list(items: string[]) {
  return `<ul>${items.map((item) => `<li>${item}</li>`).join("")}</ul>`
}

function section(title: string, body: string | string[]) {
  return `<h2>${title}</h2>${Array.isArray(body) ? list(body) : `<p>${body}</p>`}`
}

function contract(sections: Array<[string, string | string[]]>) {
  return formatFrenchLegalText([
    "<h1>{{contract.title}}</h1>",
    parties,
    ...sections.map(([title, body]) => section(title, body)),
    "<h2>Signature electronique</h2>",
    "<p>Les Parties reconnaissent que la signature electronique du present contrat produit les memes effets qu'une signature manuscrite, sous reserve de l'identification du signataire et de la conservation de la preuve de signature.</p>",
  ].join(""))
}

const RAW_CONTRACT_TEMPLATE_PRESETS: ContractTemplatePreset[] = [
  {
    id: "vertical-fourniture-pose",
    name: "Fourniture et pose",
    category: "prestation",
    title: "Contrat de fourniture et pose d’un équipement de piscine",
    description: "Cadre la fourniture, le relevé technique, la préparation et la pose chez le client.",
    bestFor: "Couverture, volet, équipement de sécurité ou accessoire posé par l’entreprise.",
    sections: 9,
    content: contract([
      ["1. Objet", "Le présent contrat définit les conditions de fourniture, de préparation et de pose de l’équipement de piscine décrit au devis accepté par le Client."],
      ["2. Documents contractuels", ["Le devis accepté et ses annexes techniques.", "Le relevé de dimensions validé pour fabrication ou préparation.", "Les présentes conditions et, le cas échéant, les avenants signés."]],
      ["3. Relevé technique", "Le Client garantit l’accès au bassin et signale toute contrainte connue. Les dimensions, obstacles, accès et alimentations relevés sur site conditionnent la solution finale. Toute modification postérieure peut entraîner un avenant."],
      ["4. Préparation du site", ["Le Client libère et sécurise la zone d’intervention.", "Les supports, alimentations et accès doivent être conformes aux prérequis communiqués.", "Les travaux de maçonnerie, électricité ou reprise non prévus au devis restent hors périmètre."]],
      ["5. Livraison et pose", "La date de pose est confirmée lorsque le matériel, le site et les équipes sont disponibles. Les intempéries, contraintes de sécurité ou impossibilités d’accès peuvent justifier un report."],
      ["6. Réception", "À la fin de la pose, les essais et points de contrôle sont consignés. Le compte rendu d’intervention signé mentionne les éventuelles réserves et vaut réception pour les éléments sans réserve."],
      ["7. Prix et paiement", "Le prix, l’acompte, les échéances et les modalités de paiement sont ceux du devis accepté. La commande peut être suspendue tant qu’un acompte exigible n’est pas encaissé."],
      ["8. Garanties", "Les garanties fabricant s’appliquent selon leurs conditions. La garantie de pose couvre les défauts directement imputables à l’intervention de {{entreprise.name}}, hors mauvaise utilisation, intervention d’un tiers, usure ou événement extérieur."],
      ["9. Responsabilité et sécurité", "Le Client respecte les consignes d’utilisation et d’entretien remises. Un équipement de sécurité ne remplace jamais la vigilance d’un adulte responsable autour du bassin."],
    ]),
  },
  {
    id: "vertical-entretien",
    name: "Entretien d’équipement",
    category: "maintenance",
    title: "Contrat d’entretien d’un équipement de piscine",
    description: "Définit la fréquence, le parc couvert et le contenu des visites d’entretien.",
    bestFor: "Couvertures, volets et équipements installés suivis dans le parc client.",
    sections: 8,
    content: contract([
      ["1. Objet", "{{entreprise.name}} réalise les visites d’entretien préventif des équipements identifiés au contrat selon la fréquence convenue."],
      ["2. Prestations incluses", ["Contrôle visuel et fonctionnel.", "Nettoyage et réglages courants accessibles.", "Signalement des pièces usées, anomalies et risques constatés.", "Compte rendu après chaque visite."]],
      ["3. Exclusions", "Les pièces, réparations, travaux électriques ou de maçonnerie et interventions consécutives à une mauvaise utilisation font l’objet d’un devis séparé."],
      ["4. Accès", "Le Client garantit l’accès au site et à l’équipement à la date convenue. Une visite empêchée sans préavis suffisant peut être considérée comme due."],
      ["5. Planification", "Les visites sont planifiées autour de la date indicative enregistrée. {{entreprise.name}} peut proposer un ajustement pour tenir compte de la saison, de la météo ou de la disponibilité des pièces."],
      ["6. Prix", "Le prix et les modalités de révision figurent au contrat ou au devis. Toute prestation non incluse nécessite l’accord préalable du Client."],
      ["7. Durée et résiliation", "Le contrat s’applique pendant la période indiquée. Les conditions de renouvellement et de résiliation suivent les mentions particulières acceptées par les Parties."],
      ["8. Traçabilité", "Chaque visite donne lieu à un rapport horodaté. L’accord du Client présent peut être recueilli électroniquement et conservé avec son empreinte de preuve."],
    ]),
  },
  {
    id: "vertical-sav",
    name: "Intervention SAV",
    category: "maintenance",
    title: "Conditions d’intervention de service après-vente",
    description: "Cadre diagnostic, réparation, pièces et réception d’une intervention SAV.",
    bestFor: "Dépannage ponctuel, garantie, diagnostic ou remise en service.",
    sections: 7,
    content: contract([
      ["1. Objet", "{{entreprise.name}} intervient sur le site du Client afin de diagnostiquer ou traiter l’anomalie déclarée sur l’équipement identifié."],
      ["2. Diagnostic", "Le diagnostic initial repose sur les informations fournies et les contrôles réalisables sur place. Une investigation ou un démontage complémentaire peut nécessiter un accord et un devis distincts."],
      ["3. Garantie", "Lorsque l’intervention relève d’une garantie applicable, sa prise en charge reste subordonnée aux conditions du fabricant et à l’absence d’exclusion."],
      ["4. Pièces et travaux complémentaires", "Aucune pièce ou réparation non prévue n’est facturée sans information et accord du Client, sauf mesure conservatoire indispensable à la sécurité."],
      ["5. Accès et sécurité", "Le Client assure un accès sûr au site, coupe les équipements lorsque cela est demandé et signale tout danger particulier."],
      ["6. Compte rendu", "Les opérations, le temps passé et les réserves sont consignés dans le rapport d’intervention. L’accord électronique du Client présent scelle le rapport horodaté."],
      ["7. Paiement", "Les frais de déplacement, diagnostic, main-d’œuvre et pièces sont facturés selon le devis, le tarif accepté ou les conditions de garantie applicables."],
    ]),
  },
  {
    id: "prestation-web-app",
    name: "Prestation web ou application",
    category: "prestation",
    title: "Contrat de prestation web et applicative",
    description: "Cadrage complet pour site, app, refonte, integration ou developpement sur mesure.",
    bestFor: "Sites vitrine, apps internes, SaaS MVP, refontes techniques.",
    sections: 10,
    content: contract([
      ["1. Objet", "Le present contrat a pour objet de definir les conditions dans lesquelles le Prestataire realise pour le Client une prestation de conception, developpement, integration, optimisation ou mise en production d'une solution web ou applicative."],
      ["2. Perimetre de la mission", [
        "Le perimetre fonctionnel est limite aux livrables valides par les Parties avant le demarrage.",
        "Toute demande non prevue au perimetre initial fait l'objet d'une estimation complementaire avant execution.",
        "Le Prestataire peut proposer des ajustements techniques lorsqu'ils ameliorent la securite, la maintenabilite ou la performance du projet.",
      ]],
      ["3. Livrables", [
        "Code source, composants, pages, integrations ou configurations explicitement prevus.",
        "Documentation d'utilisation ou de passation lorsque celle-ci est mentionnee au devis ou au cahier de cadrage.",
        "Acces ou elements de deploiement necessaires a la mise en exploitation.",
      ]],
      ["4. Planning et jalons", "Le planning est communique a titre indicatif et depend de la disponibilite des contenus, validations, acces techniques et retours du Client. Les retards imputables au Client decalent les echeances a due concurrence."],
      ["5. Obligations du Client", [
        "Fournir les contenus, acces, identifiants, decisions et validations dans des delais compatibles avec le planning.",
        "Designer un interlocuteur habilite a valider les choix fonctionnels, graphiques et techniques.",
        "Verifier les livrables en recette et signaler toute anomalie reproductible avec les informations utiles.",
      ]],
      ["6. Recette et validation", "Chaque livrable est soumis a validation. A defaut de retour motive dans un delai de sept jours ouvrables suivant sa mise a disposition, le livrable est repute accepte."],
      ["7. Prix et facturation", "Les conditions financieres, echeanciers et modalites de paiement sont ceux convenus entre les Parties. Les prestations hors perimetre, urgentes ou realisees en dehors des horaires habituels peuvent donner lieu a une facturation complementaire."],
      ["8. Propriete intellectuelle", "Sous reserve du paiement integral des sommes dues, le Prestataire cede au Client les droits d'exploitation sur les livrables specifiquement crees pour le Client, dans la limite des usages prevus au contrat. Les outils, bibliotheques, methodes, savoir-faire et composants preexistants restent la propriete de leur titulaire."],
      ["9. Garantie et maintenance", "Sauf stipulation contraire, la correction des anomalies bloquantes signalees pendant la periode de recette est incluse. Toute evolution, support recurrent, surveillance ou maintenance corrective apres validation fait l'objet d'un accord separe."],
      ["10. Responsabilite", "La responsabilite du Prestataire est limitee aux dommages directs, certains et prouves, a l'exclusion des pertes de chiffre d'affaires, pertes de donnees indirectes, perte d'exploitation ou prejudice commercial indirect."],
    ]),
  },
  {
    id: "maintenance-evolutive",
    name: "Maintenance evolutive",
    category: "maintenance",
    title: "Contrat de maintenance et support evolutif",
    description: "Support, correctifs, petites evolutions, priorisation et cadre d'intervention.",
    bestFor: "Sites en production, apps clients, backoffices, automatisations.",
    sections: 11,
    content: contract([
      ["1. Objet", "Le present contrat encadre les prestations de maintenance corrective, preventive et evolutive fournies par le Prestataire sur l'environnement du Client."],
      ["2. Environnement couvert", "Sont couverts les applications, sites, services, depots, hebergements, connecteurs ou automatisations expressement identifies par les Parties. Tout nouvel environnement doit etre valide avant prise en charge."],
      ["3. Nature des interventions", [
        "Correction d'anomalies reproductibles.",
        "Mises a jour raisonnables de dependances, correctifs de securite et ajustements de configuration.",
        "Petites evolutions fonctionnelles compatibles avec le volume d'heures prevu.",
        "Conseil technique lie a la stabilite et a l'exploitation.",
      ]],
      ["4. Exclusions", [
        "Refonte majeure, creation de nouveau module complexe ou changement d'architecture.",
        "Incidents causes par un tiers, un hebergeur, une modification non autorisee ou une mauvaise utilisation.",
        "Astreinte permanente ou garantie de temps de retablissement sauf accord specifique.",
      ]],
      ["5. Priorisation", "Les demandes sont classees selon leur criticite, leur impact utilisateur et leur urgence commerciale. Le Prestataire peut recommander de differer une demande si elle menace la stabilite ou la securite de l'environnement."],
      ["6. Delais d'intervention", "Les delais annonces sont des objectifs de prise en charge et non des garanties de resolution, sauf engagement specifique ecrit. Les delais dependent des acces, informations et validations fournis par le Client."],
      ["7. Reporting", "Le Prestataire communique un suivi des interventions realisees, du temps consomme et des recommandations prioritaires lorsque la mission le justifie."],
      ["8. Sauvegardes et securite", "Le Client demeure responsable de la politique de sauvegarde et de la gestion des acces. Le Prestataire applique des pratiques raisonnables de securite et signale les risques identifies dans le cadre de sa mission."],
      ["9. Facturation", "La maintenance est facturee selon le forfait, l'abonnement ou le temps passe convenu. Les heures non consommees, depassements et reports sont traites selon les conditions commerciales acceptees par les Parties."],
      ["10. Reversibilite", "A la fin du contrat, le Prestataire restitue les elements utiles en sa possession et facilite la transition vers le Client ou un nouveau prestataire, sous reserve du paiement des sommes dues."],
      ["11. Suspension", "Le Prestataire peut suspendre ses interventions en cas d'impayes, d'acces insuffisants, de risque de securite non traite ou de demande manifestement illicite."],
    ]),
  },
  {
    id: "retainer-mensuel",
    name: "Abonnement / regie mensuelle",
    category: "operation",
    title: "Contrat d'accompagnement mensuel",
    description: "Cadre clair pour un volume recurrent d'heures, de jours ou de credits.",
    bestFor: "Accompagnement produit, growth, ops, no-code, support dirigeant.",
    sections: 10,
    content: contract([
      ["1. Objet", "Le present contrat organise un accompagnement recurrent du Client par le Prestataire, selon un volume mensuel convenu et des priorites ajustees au fil de la mission."],
      ["2. Volume reserve", "Le Client reserve un volume de disponibilite mensuel. Ce volume couvre les travaux, reunions, preparation, coordination, tests, documentation et suivi directement lies a la mission."],
      ["3. Priorites", "Les priorites sont decidees conjointement. Le Prestataire peut refuser ou reporter une demande qui excede le volume reserve, necessite une expertise externe ou presente un risque disproportionne."],
      ["4. Modalites de collaboration", [
        "Un canal de communication principal est defini entre les Parties.",
        "Les demandes sont formalisees de maniere exploitable avant execution.",
        "Les arbitrages importants sont confirmes par ecrit.",
      ]],
      ["5. Report du temps non consomme", "Sauf accord contraire, le temps non consomme sur une periode n'est pas automatiquement reporte. Les reports acceptes doivent etre utilises dans le delai convenu entre les Parties."],
      ["6. Depassements", "Tout depassement du volume reserve necessite une validation prealable du Client et peut faire l'objet d'une facturation complementaire."],
      ["7. Resultats attendus", "Le Prestataire est tenu a une obligation de moyens. Les resultats commerciaux, financiers, de trafic, de conversion ou de croissance dependent egalement de facteurs externes et des decisions du Client."],
      ["8. Facturation et paiement", "La facturation intervient selon la periodicite convenue. Tout retard de paiement peut suspendre la disponibilite reservee et les travaux en cours."],
      ["9. Duree et resiliation", "Le contrat prend effet a compter de {{contract.validFrom}}. Chaque Partie peut y mettre fin dans les conditions de preavis convenues, sans prejudice des sommes dues pour les periodes engagees."],
      ["10. Confidentialite", "Les informations strategiques, commerciales, techniques et financieres echangees dans le cadre de l'accompagnement sont strictement confidentielles."],
    ]),
  },
  {
    id: "mission-conseil",
    name: "Mission de conseil",
    category: "conseil",
    title: "Contrat de mission de conseil",
    description: "Structure professionnelle pour audit, strategie, cadrage, accompagnement de decision.",
    bestFor: "Conseil digital, organisation, produit, acquisition, finance, ops.",
    sections: 9,
    content: contract([
      ["1. Objet", "Le present contrat a pour objet de confier au Prestataire une mission de conseil, d'analyse, de recommandation et d'accompagnement sur le sujet defini entre les Parties."],
      ["2. Methodologie", "Le Prestataire determine librement sa methodologie, dans le respect des objectifs valides, et peut s'appuyer sur des entretiens, ateliers, analyses documentaires, benchmarks, tests ou modelisations."],
      ["3. Livrables de conseil", [
        "Notes de cadrage, diagnostics, recommandations ou plans d'action.",
        "Supports d'atelier, syntheses de decision ou feuilles de route.",
        "Restitutions orales ou ecrites selon les modalites convenues.",
      ]],
      ["4. Cooperation du Client", "Le Client s'engage a fournir les informations utiles, a faciliter l'acces aux interlocuteurs pertinents et a signaler toute contrainte susceptible d'influer sur les recommandations."],
      ["5. Limites des recommandations", "Les recommandations reposent sur les informations disponibles au moment de la mission. Le Client demeure seul responsable des decisions de mise en oeuvre et de leurs consequences operationnelles."],
      ["6. Independance", "Le Prestataire intervient en toute independance et n'est pas integre a l'organisation du Client. Il ne dispose d'aucun pouvoir de representation du Client sauf mandat expres."],
      ["7. Confidentialite", "Les documents, donnees, hypotheses, modeles economiques et informations sensibles communiques au Prestataire sont confidentiels et ne peuvent etre divulgues sans autorisation prealable."],
      ["8. Propriete des livrables", "Apres paiement integral, le Client peut utiliser les livrables de conseil pour ses besoins internes. Les methodes, matrices, modeles generiques et savoir-faire preexistants du Prestataire restent sa propriete."],
      ["9. Responsabilite", "La mission de conseil est une obligation de moyens. La responsabilite du Prestataire ne peut etre engagee au titre de decisions prises par le Client ou de resultats dependants de facteurs externes."],
    ]),
  },
  {
    id: "audit-technique",
    name: "Audit technique",
    category: "conseil",
    title: "Contrat d'audit technique et recommandations",
    description: "Audit applicatif, performance, securite, SEO technique ou architecture.",
    bestFor: "Avant refonte, due diligence, dette technique, incident recurrent.",
    sections: 10,
    content: contract([
      ["1. Objet", "Le present contrat confie au Prestataire une mission d'audit technique portant sur les elements mis a disposition par le Client."],
      ["2. Perimetre audite", "L'audit porte uniquement sur les environnements, depots, pages, donnees, configurations et documents explicitement ouverts au Prestataire."],
      ["3. Acces et donnees", "Le Client fournit des acces adaptes, temporaires et proportionnes. Le Prestataire peut refuser d'utiliser des comptes non securises, partages de maniere excessive ou incompatibles avec de bonnes pratiques de securite."],
      ["4. Travaux realises", [
        "Analyse de l'architecture, du code, des performances ou de la configuration.",
        "Identification des risques, anomalies, dettes et opportunites d'amelioration.",
        "Priorisation des recommandations selon impact, effort et urgence.",
      ]],
      ["5. Limites de l'audit", "L'audit est realise sur un echantillon ou une periode donnee. Il ne constitue pas une certification exhaustive, une garantie d'absence de faille ni une validation juridique ou reglementaire."],
      ["6. Livrable d'audit", "Le Prestataire remet un rapport ou une restitution synthese comprenant les constats, risques, recommandations prioritaires et pistes de mise en oeuvre."],
      ["7. Correctifs", "La correction des constats identifies n'est pas incluse sauf accord distinct. Le Prestataire peut proposer une mission complementaire de remediation ou d'accompagnement."],
      ["8. Confidentialite et securite", "Les informations techniques et vulnerabilites identifiees sont strictement confidentielles. Le Client s'engage a les traiter avec diligence."],
      ["9. Responsabilite", "La responsabilite du Prestataire est limitee aux travaux effectivement realises dans le perimetre convenu. Les decisions de correction, d'arbitrage ou d'exploitation appartiennent au Client."],
      ["10. Conservation", "Sauf obligation contraire, le Prestataire supprime ou restitue les acces et informations sensibles a l'issue de la mission."],
    ]),
  },
  {
    id: "formation-equipe",
    name: "Formation equipe",
    category: "conseil",
    title: "Convention de formation et transfert de competences",
    description: "Programme de formation, ateliers pratiques, supports et obligations de presence.",
    bestFor: "Formation outil, IA, no-code, vente, produit, process internes.",
    sections: 10,
    content: contract([
      ["1. Objet", "Le present contrat encadre une action de formation, d'atelier ou de transfert de competences realisee par le Prestataire au benefice du Client."],
      ["2. Public vise", "Le Client identifie les participants concernes et s'assure que leur niveau, leurs disponibilites et leurs equipements sont compatibles avec les objectifs pedagogiques."],
      ["3. Objectifs pedagogiques", "Les objectifs, modules, duree et modalites de formation sont definis avant le demarrage. Les exercices peuvent etre adaptes au contexte operationnel du Client."],
      ["4. Modalites", [
        "Formation en presentiel, distanciel ou format hybride selon accord.",
        "Supports, exercices, demonstrations ou cas pratiques fournis selon le programme.",
        "Feuille de presence, evaluation ou attestation lorsque prevu.",
      ]],
      ["5. Obligations du Client", "Le Client assure la convocation des participants, la mise a disposition des salles, outils, acces et documents necessaires, ainsi que le respect des horaires convenus."],
      ["6. Report ou annulation", "Toute demande de report ou d'annulation doit etre notifiee par ecrit. Des frais peuvent etre dus lorsque la demande intervient tardivement ou apres preparation significative."],
      ["7. Supports", "Les supports fournis restent proteges par les droits de propriete intellectuelle du Prestataire. Le Client peut les utiliser pour ses besoins internes, sans diffusion publique ni revente."],
      ["8. Resultats", "Le Prestataire est tenu a une obligation de moyens pedagogiques. L'acquisition effective des competences depend de la participation, de la pratique et du contexte de chaque participant."],
      ["9. Confidentialite", "Les exemples, donnees et cas internes partages pendant la formation demeurent confidentiels."],
      ["10. Facturation", "Les prix, frais, acomptes et echeances sont ceux acceptes par les Parties. Les frais de deplacement ou de preparation specifique peuvent etre factures separement s'ils ont ete valides."],
    ]),
  },
  {
    id: "identite-visuelle",
    name: "Identite visuelle",
    category: "creation",
    title: "Contrat de creation d'identite visuelle",
    description: "Logo, charte graphique, direction artistique, declinaisons et cession de droits.",
    bestFor: "Branding freelance, refonte marque, kits social media, charte.",
    sections: 11,
    content: contract([
      ["1. Objet", "Le present contrat encadre la creation d'une identite visuelle, d'elements graphiques, d'une charte ou de supports de communication pour le Client."],
      ["2. Brief creatif", "Le Client transmet un brief comprenant objectifs, cible, contraintes, references, supports attendus et elements existants. Les retours doivent etre consolides par un interlocuteur unique."],
      ["3. Livrables", [
        "Pistes creatives, logo, declinaisons ou elements graphiques prevus.",
        "Fichiers exportes dans les formats convenus.",
        "Charte, guide d'usage ou recommandations lorsque prevus.",
      ]],
      ["4. Iterations", "Le nombre de pistes et d'allers-retours inclus est limite aux conditions convenues. Toute iteration supplementaire, changement de brief ou nouvelle direction artistique peut etre facturee."],
      ["5. Validation", "La validation d'une piste ou d'un livrable vaut accord sur sa direction artistique. Les corrections ulterieures sont limitees aux ajustements mineurs sauf accord contraire."],
      ["6. Droits cedes", "Apres paiement integral, le Prestataire cede au Client les droits d'utilisation des creations finales retenues pour les supports, territoires et durees convenus. Les propositions non retenues restent la propriete du Prestataire."],
      ["7. Elements tiers", "Les polices, banques d'images, illustrations, plugins, templates ou ressources tiers peuvent etre soumis a des licences distinctes. Le Client est informe lorsqu'une licence doit etre acquise ou conservee."],
      ["8. Portfolio", "Sauf opposition ecrite du Client pour raison de confidentialite, le Prestataire peut mentionner la mission et presenter les creations dans son portfolio apres publication par le Client."],
      ["9. Fichiers sources", "Les fichiers sources ne sont transmis que si cela est prevu. Leur transmission n'emporte pas cession des methodes, gabarits, bibliotheques ou elements generiques du Prestataire."],
      ["10. Responsabilite de validation", "Le Client est responsable de verifier la disponibilite juridique du nom, du signe, de la marque ou du domaine exploite, sauf mission specifique de recherche ou depot confiee au Prestataire."],
      ["11. Confidentialite", "Les projets non publies, lancements, positionnements et informations strategiques communiques pendant la mission demeurent confidentiels."],
    ]),
  },
  {
    id: "ux-ui-produit",
    name: "UX/UI produit",
    category: "creation",
    title: "Contrat de conception UX/UI",
    description: "Recherche, parcours, wireframes, maquettes, design system et passation developpement.",
    bestFor: "Apps SaaS, dashboards, tunnels de conversion, produits internes.",
    sections: 10,
    content: contract([
      ["1. Objet", "Le present contrat porte sur une mission de conception UX/UI, de structuration de parcours, de prototypage, de design system ou d'amelioration d'interface."],
      ["2. Perimetre", "Le perimetre est defini par les ecrans, parcours, composants, hypotheses utilisateurs et niveaux de fidelite attendus."],
      ["3. Inputs necessaires", [
        "Objectifs business et utilisateurs.",
        "Contraintes techniques, analytics, contenus et identite existante.",
        "Acces aux utilisateurs, experts metier ou parties prenantes lorsque prevu.",
      ]],
      ["4. Livrables", [
        "Parcours, arborescences, wireframes, maquettes ou prototypes.",
        "Composants, tokens, specifications ou documentation de passation.",
        "Synthese des decisions UX et recommandations de mise en oeuvre.",
      ]],
      ["5. Tests et hypotheses", "Les maquettes et recommandations peuvent reposer sur des hypotheses. Les tests utilisateurs, analyses quantitatives ou experimentations ne sont inclus que s'ils sont prevus au perimetre."],
      ["6. Iterations", "Les retours sont regroupes par cycle de validation. Les changements d'objectif, de cible ou de positionnement apres validation d'une etape peuvent entrainer un ajustement de planning et de prix."],
      ["7. Passation developpement", "Le Prestataire fournit les elements utiles a l'integration. Il ne garantit pas la fidelite finale de l'implementation si le developpement est realise par un tiers sans accompagnement specifique."],
      ["8. Propriete intellectuelle", "Les creations finales sont cedees au Client apres paiement integral. Les methodes, frameworks, composants generiques et savoir-faire preexistants restent la propriete du Prestataire."],
      ["9. Accessibilite", "Les recommandations d'accessibilite sont formulees selon le niveau convenu. La certification ou conformite exhaustive necessite une mission specialisee distincte."],
      ["10. Confidentialite", "Les informations produit, parcours, donnees utilisateurs, metrics et hypotheses de strategie sont confidentielles."],
    ]),
  },
  {
    id: "marketing-contenu",
    name: "Marketing & contenu",
    category: "prestation",
    title: "Contrat d'accompagnement marketing et contenu",
    description: "Cadre pour strategie editoriale, campagnes, SEO, newsletters, social media.",
    bestFor: "Freelance marketing, growth content, acquisition organique.",
    sections: 10,
    content: contract([
      ["1. Objet", "Le present contrat encadre les prestations de strategie marketing, creation de contenus, optimisation SEO, campagnes editoriales ou accompagnement acquisition realisees pour le Client."],
      ["2. Perimetre", "Le perimetre precise les canaux, formats, volumes, calendriers, audiences, objectifs et indicateurs suivis."],
      ["3. Contribution du Client", "Le Client fournit les informations metier, validations, acces outils, elements de marque, offres, contraintes legales et preuves necessaires a la production des contenus."],
      ["4. Livrables", [
        "Calendriers editoriaux, briefs, articles, pages, emails, scripts, posts ou assets prevus.",
        "Recommandations SEO, tracking ou optimisation lorsque prevues.",
        "Reporting synthetique sur les actions realisees.",
      ]],
      ["5. Validation des contenus", "Le Client est responsable de valider l'exactitude, la conformite, les promesses commerciales, prix, mentions et elements reglementaires avant publication."],
      ["6. Performances", "Les resultats marketing dependent de facteurs externes tels que marche, offre, budget, algorithmes, concurrence et execution commerciale. Le Prestataire est tenu a une obligation de moyens."],
      ["7. Droits et reutilisation", "Apres paiement, le Client peut exploiter les contenus finals pour ses besoins propres. Les frameworks, prompts, methodes, templates et contenus non retenus restent la propriete du Prestataire."],
      ["8. Outils tiers", "Les outils publicitaires, analytics, SEO, email ou IA restent soumis a leurs propres conditions. Le Client supporte les couts tiers sauf accord contraire."],
      ["9. Confidentialite", "Les donnees de performance, budgets, audiences, fichiers clients, positionnement et plans de lancement sont confidentiels."],
      ["10. Suspension", "Le Prestataire peut suspendre une publication ou une action si elle lui parait trompeuse, illicite, non conforme a une plateforme ou insuffisamment validee."],
    ]),
  },
  {
    id: "sous-traitance",
    name: "Sous-traitance agence",
    category: "operation",
    title: "Contrat de sous-traitance de prestations",
    description: "Cadre agence/freelance avec confidentialite, non-contournement et passation.",
    bestFor: "Missions realisees pour le client final d'une agence ou d'un integrateur.",
    sections: 11,
    content: contract([
      ["1. Objet", "Le present contrat definit les conditions dans lesquelles le Prestataire intervient en sous-traitance pour le compte du Client sur une mission destinee a un client final."],
      ["2. Relation avec le client final", "Sauf autorisation expresse, le Prestataire n'agit pas au nom du Client aupres du client final et ne prend aucun engagement contractuel pour son compte."],
      ["3. Perimetre", "Les travaux confies, livrables, niveaux d'intervention, interlocuteurs, outils et contraintes du client final sont definis avant demarrage."],
      ["4. Confidentialite renforcee", "Le Prestataire s'engage a ne pas divulguer les informations relatives au Client, au client final, a la tarification, aux methodes commerciales et aux documents internes."],
      ["5. Non-contournement", "Pendant la mission et pendant une duree raisonnable apres son terme, le Prestataire s'interdit de demarcher directement le client final pour une prestation similaire, sauf accord ecrit du Client."],
      ["6. Qualite et validation", "Le Client conserve la responsabilite de validation finale vis-a-vis du client final. Le Prestataire corrige les anomalies imputables a ses travaux dans le cadre du perimetre accepte."],
      ["7. Propriete intellectuelle", "Sous reserve du paiement integral, les droits sur les livrables specifiques sont transmis selon la chaine contractuelle convenue entre les Parties et compatible avec les engagements du Client envers son client final."],
      ["8. Planning", "Le Prestataire depend des informations, acces et validations transmis par le Client. Tout retard dans ces elements decale les obligations du Prestataire."],
      ["9. Facturation", "Le Prestataire facture le Client, independamment des paiements recus par le Client de la part du client final, sauf stipulation contraire expresse."],
      ["10. Responsabilite", "Le Prestataire n'est responsable que des travaux qui lui sont directement imputables et dans la limite du perimetre confie."],
      ["11. Fin de mission", "A la fin de la mission, le Prestataire restitue ou supprime les acces, documents et informations confidentielles selon les instructions raisonnables du Client."],
    ]),
  },
  {
    id: "nda-mutuel",
    name: "NDA mutuel",
    category: "juridique",
    title: "Accord de confidentialite mutuel",
    description: "Confidentialite avant mission, partenariat, negociation ou acces sensible.",
    bestFor: "Avant-projet, appel d'offres, discussion investisseur, partenariat.",
    sections: 10,
    content: contract([
      ["1. Objet", "Le present accord a pour objet de proteger les informations confidentielles echangees entre les Parties dans le cadre de leurs discussions, evaluations, negociations ou collaborations potentielles."],
      ["2. Informations confidentielles", "Sont confidentielles toutes informations non publiques, techniques, commerciales, financieres, strategiques, juridiques, organisationnelles, clients, produits, donnees, codes, documents ou savoir-faire communiques par une Partie."],
      ["3. Obligations", [
        "Utiliser les informations confidentielles uniquement pour l'objet de la relation.",
        "Limiter l'acces aux personnes ayant besoin d'en connaitre.",
        "Proteger les informations avec un niveau de diligence au moins equivalent a celui applique a ses propres informations sensibles.",
      ]],
      ["4. Exclusions", "Ne sont pas confidentielles les informations deja publiques, connues licitement avant leur communication, recues d'un tiers autorise ou developpees independamment sans utilisation des informations protegees."],
      ["5. Divulgation obligatoire", "Si une Partie est tenue de divulguer une information par decision judiciaire, administrative ou obligation legale, elle en informe l'autre Partie lorsque cela est legalement possible."],
      ["6. Duree", "Les obligations de confidentialite s'appliquent pendant la duree des discussions et pendant une duree raisonnable apres leur fin, sauf accord specifique plus long pour les secrets d'affaires."],
      ["7. Restitution", "Sur demande, chaque Partie restitue ou supprime les supports contenant des informations confidentielles, sous reserve des copies imposees par obligations legales, sauvegardes ou archivage probatoire."],
      ["8. Absence de licence", "La communication d'informations confidentielles ne transfere aucun droit de propriete, licence, cession ou autorisation d'exploitation."],
      ["9. Responsabilite", "Toute violation de confidentialite peut causer un prejudice difficilement reparable et ouvre droit aux mesures utiles pour faire cesser la violation et reparer le dommage prouve."],
      ["10. Droit applicable", "Le present accord est soumis au droit francais, sauf stipulation contraire convenue par les Parties."],
    ]),
  },
  {
    id: "cession-droits",
    name: "Cession de droits",
    category: "juridique",
    title: "Contrat de cession et licence de droits",
    description: "Cession encadree de contenus, design, textes, photos, videos, code ou supports.",
    bestFor: "Livrables creatifs, contenus, design, templates, composants.",
    sections: 10,
    content: contract([
      ["1. Objet", "Le present contrat definit les conditions de cession ou de licence des droits portant sur les livrables crees par le Prestataire pour le Client."],
      ["2. Oeuvres concernees", "Les oeuvres, contenus, fichiers, visuels, textes, videos, codes, supports ou elements graphiques concernes sont ceux expressement identifies comme livrables finals."],
      ["3. Droits cedes", "Sous reserve du paiement integral, le Prestataire cede au Client les droits de reproduction, representation, adaptation et exploitation necessaires aux usages convenus."],
      ["4. Etendue", "La cession est limitee aux supports, territoires, langues, durees, volumes et usages convenus. Tout usage non prevu necessite une autorisation complementaire."],
      ["5. Elements exclus", "Les recherches, pistes refusees, fichiers de travail, methodes, savoir-faire, composants generiques, librairies, prompts, gabarits et outils preexistants ne sont pas cedes sauf mention expresse."],
      ["6. Elements tiers", "Les elements tiers restent soumis a leurs licences propres. Le Client doit respecter les conditions applicables aux polices, images, musiques, plugins, bibliotheques ou banques de ressources."],
      ["7. Credit", "Sauf accord contraire, le Prestataire peut etre credite de maniere raisonnable lorsque l'usage du support s'y prete."],
      ["8. Portfolio", "Le Prestataire peut presenter les livrables dans son portfolio apres publication par le Client, sauf confidentialite ou opposition ecrite motivee."],
      ["9. Garanties", "Le Prestataire garantit ne pas ceder sciemment des droits qu'il ne detient pas. Le Client est responsable des elements, marques, textes, donnees ou images qu'il fournit."],
      ["10. Prix de cession", "Le prix de cession ou licence est integre au prix de la mission uniquement pour les usages prevus. Les extensions d'usage peuvent donner lieu a une remuneration complementaire."],
    ]),
  },
  {
    id: "rgpd-sous-traitance",
    name: "Annexe RGPD",
    category: "data",
    title: "Accord de sous-traitance de donnees personnelles",
    description: "Annexe operationnelle pour missions manipulant des donnees personnelles.",
    bestFor: "CRM, marketing, analytics, support, hebergement, automatisation.",
    sections: 11,
    content: contract([
      ["1. Objet", "Le present accord encadre les traitements de donnees personnelles realises par le Prestataire pour le compte du Client dans le cadre de la mission."],
      ["2. Roles des Parties", "Le Client agit en qualite de responsable de traitement. Le Prestataire agit en qualite de sous-traitant pour les traitements effectues selon les instructions documentees du Client."],
      ["3. Donnees traitees", "Les categories de donnees, personnes concernees, finalites, durees et operations de traitement sont celles necessaires a l'execution de la mission et documentees par le Client."],
      ["4. Instructions", "Le Prestataire ne traite les donnees personnelles que sur instruction du Client. Il informe le Client si une instruction lui parait contraire au droit applicable."],
      ["5. Confidentialite", "Le Prestataire veille a ce que les personnes autorisees a traiter les donnees soient soumises a une obligation de confidentialite appropriee."],
      ["6. Securite", "Le Prestataire met en oeuvre des mesures techniques et organisationnelles raisonnables au regard de la nature des donnees, des risques et du perimetre de la mission."],
      ["7. Sous-traitants ulterieurs", "Le recours a des outils ou prestataires tiers necessaires a la mission est informe au Client lorsque cela est pertinent. Le Prestataire veille a ce que les obligations utiles soient repercutees."],
      ["8. Assistance", "Dans la limite de la mission, le Prestataire assiste raisonnablement le Client pour repondre aux demandes d'exercice de droits, incidents et obligations de documentation."],
      ["9. Violation de donnees", "Le Prestataire informe le Client dans les meilleurs delais apres avoir pris connaissance d'une violation de donnees personnelles affectant les traitements couverts."],
      ["10. Fin de mission", "A l'issue de la mission, le Prestataire supprime ou restitue les donnees personnelles selon les instructions du Client, sauf obligation legale ou archivage probatoire."],
      ["11. Audit", "Le Client peut demander les informations raisonnablement necessaires pour verifier le respect du present accord, dans des conditions qui ne compromettent pas la securite ni les secrets d'affaires du Prestataire."],
    ]),
  },
  {
    id: "implementation-saas",
    name: "Implementation SaaS / no-code",
    category: "prestation",
    title: "Contrat d'implementation SaaS et automatisations",
    description: "Parametrage d'outils, workflows, CRM, no-code, connecteurs et formation.",
    bestFor: "Notion, Airtable, Make, HubSpot, CRM, outils internes.",
    sections: 10,
    content: contract([
      ["1. Objet", "Le present contrat encadre l'implementation, le parametrage, l'automatisation ou l'optimisation d'outils SaaS, no-code ou low-code pour le Client."],
      ["2. Perimetre", "Le perimetre couvre les outils, workflows, integrations, formulaires, tableaux de bord, roles, droits et donnees explicitement prevus."],
      ["3. Comptes et licences", "Le Client reste responsable de la souscription, du paiement, de la disponibilite et des conditions d'utilisation des outils tiers. Le Prestataire n'est pas responsable des changements imposes par ces fournisseurs."],
      ["4. Donnees et migration", "Toute migration est realisee sur les donnees fournies par le Client. Le Client valide la qualite, l'exactitude et la licite des donnees avant import."],
      ["5. Recette", "Le Client teste les workflows, automatisations et droits d'acces avant mise en production. Les anomalies signalees pendant la recette sont traitees selon leur criticite et leur perimetre."],
      ["6. Securite", "Le Prestataire recommande des roles, droits et pratiques de securite raisonnables. Le Client demeure responsable de l'administration finale des comptes, mots de passe et acces internes."],
      ["7. Documentation et formation", "Une documentation ou session de passation peut etre fournie lorsque prevue, afin de permettre au Client d'exploiter les workflows mis en place."],
      ["8. Limites", "Le Prestataire ne garantit pas la disponibilite, la continuite, les performances ou les evolutions tarifaires des outils tiers. Les bugs ou limitations propres a ces outils relevent de leurs editeurs."],
      ["9. Propriete", "Les configurations specifiques et livrables crees pour le Client lui sont transmis apres paiement. Les methodes, schemas generiques et bibliotheques du Prestataire restent sa propriete."],
      ["10. Support", "Le support apres mise en production, les evolutions et les ajustements lies aux changements d'outils tiers sont exclus sauf accord de maintenance ou forfait complementaire."],
    ]),
  },
  {
    id: "intervention-urgence",
    name: "Intervention urgence",
    category: "operation",
    title: "Contrat d'intervention urgente",
    description: "Cadre express pour depannage, incident production, reprise de service.",
    bestFor: "Site casse, incident paiement, bug bloquant, reprise de prod.",
    sections: 9,
    content: contract([
      ["1. Objet", "Le present contrat encadre une intervention urgente du Prestataire visant a diagnostiquer, stabiliser ou corriger un incident affectant l'activite du Client."],
      ["2. Priorite", "Le Prestataire mobilise ses moyens raisonnables selon la disponibilite convenue. L'urgence ne constitue pas une garantie de resolution immediate."],
      ["3. Acces", "Le Client fournit sans delai les acces, historiques, journaux, contacts techniques, sauvegardes et informations necessaires. Tout acces manquant peut empecher ou retarder l'intervention."],
      ["4. Stabilisation", "Le Prestataire peut recommander une solution temporaire, un retour arriere, une desactivation de fonctionnalite ou une mesure conservatoire afin de reduire l'impact de l'incident."],
      ["5. Risques", "Le Client reconnait qu'une intervention sur un systeme degrade peut comporter des risques. Les actions significatives sont validees autant que possible avant execution."],
      ["6. Exclusions", "Sont exclus les incidents relevant exclusivement d'un hebergeur, fournisseur tiers, piratage non lie aux travaux du Prestataire, erreur interne du Client ou absence de sauvegarde exploitable."],
      ["7. Rapport", "Lorsque l'intervention le justifie, le Prestataire fournit une synthese des constats, actions realisees et recommandations pour prevenir la repetition de l'incident."],
      ["8. Facturation", "L'intervention urgente peut etre facturee selon un tarif majore, au temps passe, au forfait ou selon les conditions acceptees par les Parties avant demarrage."],
      ["9. Suite de mission", "Les travaux de durcissement, refonte, monitoring, documentation ou correction definitive non indispensables a la stabilisation immediate font l'objet d'un accord separe."],
    ]),
  },
  {
    id: "avenant-changement",
    name: "Avenant de changement",
    category: "operation",
    title: "Avenant de modification de perimetre",
    description: "Document court pour cadrer une evolution, un report, un supplement ou une baisse de scope.",
    bestFor: "Changement de besoin, extension de mission, nouveau jalon.",
    sections: 8,
    content: contract([
      ["1. Objet de l'avenant", "Le present avenant modifie ou complete le contrat initial conclu entre les Parties. Les stipulations non modifiees demeurent pleinement applicables."],
      ["2. Contexte", "Les Parties constatent l'evolution du besoin, du planning, des contraintes ou du perimetre initial et souhaitent formaliser les ajustements convenus."],
      ["3. Modifications de perimetre", [
        "Travaux ajoutes, retires ou modifies par rapport au contrat initial.",
        "Livrables concernes et impacts attendus.",
        "Dependances ou validations necessaires.",
      ]],
      ["4. Impact planning", "Les echeances initiales sont ajustees en fonction des modifications convenues. Les nouveaux jalons remplacent les jalons incompatibles du contrat initial."],
      ["5. Impact financier", "Les changements de prix, acomptes, echeances ou modalites de facturation sont ceux acceptes par les Parties dans le cadre du present avenant."],
      ["6. Conditions d'execution", "Les obligations de cooperation, validation, confidentialite, propriete intellectuelle, responsabilite et paiement du contrat initial s'appliquent au present avenant."],
      ["7. Priorite", "En cas de contradiction, les stipulations du present avenant prevalent sur celles du contrat initial uniquement pour les points qu'il modifie expressement."],
      ["8. Entree en vigueur", "Le present avenant prend effet a compter de sa signature par les Parties ou de la date convenue par ecrit."],
    ]),
  },
  {
    id: "conditions-cadre",
    name: "Conditions cadre",
    category: "juridique",
    title: "Conditions cadre de prestations",
    description: "Socle contractuel general reutilisable pour devis, bons de commande et missions recurrentes.",
    bestFor: "Freelance avec plusieurs missions pour le meme client.",
    sections: 12,
    content: contract([
      ["1. Objet", "Les presentes conditions cadre definissent les regles generales applicables aux prestations commandees par le Client au Prestataire."],
      ["2. Commandes", "Chaque mission fait l'objet d'un devis, bon de commande, email de validation ou document equivalent precisant le perimetre, le prix, les delais et les livrables."],
      ["3. Execution", "Le Prestataire execute les prestations avec diligence, selon les regles de l'art applicables a son domaine et dans la limite des informations, acces et validations fournis par le Client."],
      ["4. Collaboration", "Le Client s'engage a cooperer activement, fournir des informations exactes, valider les etapes dans les delais et signaler toute contrainte importante."],
      ["5. Modifications", "Toute modification de perimetre, priorite, livrable ou planning peut entrainer un ajustement de prix et de delai."],
      ["6. Recette", "Les livrables sont valides ou contestes de maniere motivee dans un delai raisonnable. A defaut de retour, ils sont reputes acceptes."],
      ["7. Prix et paiement", "Les prix sont exprimes hors taxes sauf indication contraire. Les retards de paiement peuvent entrainer penalites, suspension des travaux et exigibilite des sommes dues."],
      ["8. Propriete intellectuelle", "Les droits sur les livrables specifiques sont cedes apres paiement integral, dans la limite des usages convenus. Les elements preexistants et generiques restent exclus de la cession."],
      ["9. Confidentialite", "Chaque Partie conserve confidentielles les informations non publiques recues de l'autre Partie."],
      ["10. Responsabilite", "La responsabilite du Prestataire est limitee aux dommages directs et au montant paye pour la mission concernee, sauf faute lourde ou disposition imperatives contraires."],
      ["11. Force majeure", "Aucune Partie n'est responsable d'un retard ou manquement cause par un evenement imprevisible, irresistible et exterieur au sens du droit applicable."],
      ["12. Droit applicable", "Les presentes conditions sont soumises au droit francais. Les Parties recherchent une solution amiable avant toute action contentieuse."],
    ]),
  },
  {
    id: "apport-affaires",
    name: "Apport d'affaires",
    category: "operation",
    title: "Contrat d'apport d'affaires",
    description: "Commissionnement, conditions de mise en relation et tracabilite des opportunites.",
    bestFor: "Partenaires, recommandations commerciales, reseaux freelances.",
    sections: 10,
    content: contract([
      ["1. Objet", "Le present contrat definit les conditions dans lesquelles l'Apporteur presente au Beneficiaire des prospects ou opportunites commerciales susceptibles de donner lieu a une relation d'affaires."],
      ["2. Role de l'Apporteur", "L'Apporteur met en relation les parties ou transmet des opportunites qualifiees. Il ne represente pas le Beneficiaire et ne peut prendre aucun engagement en son nom."],
      ["3. Opportunite qualifiee", "Une opportunite est qualifiee lorsqu'elle est identifiee, documentee, non deja connue du Beneficiaire et acceptee par celui-ci comme entrant dans le perimetre du contrat."],
      ["4. Commission", "La commission, son assiette, son taux, son plafond, sa duree et son fait generateur sont ceux convenus par les Parties avant la mise en relation."],
      ["5. Paiement", "La commission devient exigible uniquement apres encaissement effectif par le Beneficiaire des sommes dues par le client apporte, sauf accord contraire."],
      ["6. Exclusions", "Aucune commission n'est due pour un prospect deja en discussion, une opportunite refusee, une relation preexistante ou une affaire non encaissee."],
      ["7. Confidentialite", "Les informations commerciales, listes de prospects, tarifs, marges, strategies et documents echanges sont confidentiels."],
      ["8. Non-exclusivite", "Sauf stipulation contraire, le contrat n'est pas exclusif et chaque Partie reste libre de travailler avec d'autres partenaires."],
      ["9. Conformite", "L'Apporteur s'engage a ne pas utiliser de methode trompeuse, illicite, agressive ou contraire a l'image du Beneficiaire."],
      ["10. Duree", "Le contrat prend effet a compter de {{contract.validFrom}} et s'applique aux opportunites presentees pendant sa duree."],
    ]),
  },
  {
    id: "reversibilite-passation",
    name: "Passation / reversibilite",
    category: "operation",
    title: "Contrat de passation et reversibilite",
    description: "Organise transfert de connaissances, documentation, acces et sortie propre.",
    bestFor: "Fin de mission, changement prestataire, internalisation.",
    sections: 9,
    content: contract([
      ["1. Objet", "Le present contrat encadre une mission de passation, documentation et reversibilite afin de permettre au Client ou a un tiers de reprendre l'exploitation des elements concernes."],
      ["2. Perimetre", "Le perimetre couvre les informations, acces, depots, configurations, documentations, procedures et connaissances explicitement identifiees par les Parties."],
      ["3. Livrables", [
        "Inventaire des acces, services, environnements ou ressources.",
        "Documentation d'exploitation ou de maintenance selon le niveau convenu.",
        "Session de transfert de connaissances ou support de passation.",
      ]],
      ["4. Obligations du Client", "Le Client designe les personnes recevant la passation, fournit les acces necessaires et valide les elements remis dans les delais convenus."],
      ["5. Limites", "La passation ne comprend pas la correction de dette technique, refonte, creation de nouvelles fonctionnalites ou garantie de competence du repreneur sauf accord distinct."],
      ["6. Confidentialite et securite", "Les acces transmis doivent etre remplaces, revoques ou securises par le Client a l'issue de la passation. Les informations sensibles demeurent confidentielles."],
      ["7. Paiement prealable", "Le Prestataire peut subordonner la remise de certains elements non encore dus au paiement des factures echues, dans les limites permises par le contrat initial et le droit applicable."],
      ["8. Validation", "La passation est reputee realisee lorsque les livrables prevus sont remis et que la session de transfert convenue a eu lieu ou a ete proposee dans les delais."],
      ["9. Responsabilite ulterieure", "Apres la passation, le Prestataire n'est plus responsable des modifications, exploitations, erreurs ou incidents causes par le Client ou un tiers."],
    ]),
  },
]

export const CONTRACT_TEMPLATE_PRESETS: ContractTemplatePreset[] =
  RAW_CONTRACT_TEMPLATE_PRESETS
    .filter((template) => template.id.startsWith("vertical-"))
    .map(formatTemplatePreset)

const RAW_CONTRACT_CLAUSE_LIBRARY: ContractClausePreset[] = [
  {
    id: "propriete-intellectuelle",
    title: "Propriete intellectuelle",
    description: "Cession apres paiement, exclusions des outils et savoir-faire preexistants.",
    content: "Sous reserve du paiement integral des sommes dues, les droits d'exploitation sur les livrables specifiquement crees pour le Client sont cedes dans la limite des usages convenus. Les methodes, outils, composants generiques, savoir-faire et elements preexistants du Prestataire restent sa propriete exclusive.",
  },
  {
    id: "confidentialite",
    title: "Confidentialite",
    description: "Protection mutuelle des informations sensibles echangees pendant la mission.",
    content: "Chaque Partie s'engage a conserver strictement confidentielles les informations non publiques recues de l'autre Partie et a ne les utiliser que pour l'execution de la mission. Cette obligation survit a la fin du contrat pendant une duree raisonnable.",
  },
  {
    id: "rgpd",
    title: "Donnees personnelles",
    description: "Base RGPD pour mission impliquant des donnees personnelles.",
    content: "Lorsque le Prestataire traite des donnees personnelles pour le compte du Client, il agit sur instruction documentee du Client, applique des mesures de securite raisonnables et informe le Client de tout incident connu affectant les donnees traitees dans le cadre de la mission.",
  },
  {
    id: "hors-perimetre",
    title: "Hors perimetre",
    description: "Evite les derives de scope et impose une validation des changements.",
    content: "Toute demande non prevue au perimetre initial, tout changement de brief ou toute evolution significative fait l'objet d'une estimation complementaire et d'une validation ecrite avant execution.",
  },
  {
    id: "recette",
    title: "Recette et validation",
    description: "Cadre les retours client et l'acceptation des livrables.",
    content: "Les livrables sont soumis a validation du Client. A defaut de retour motive dans un delai de sept jours ouvrables apres mise a disposition, ils sont reputes acceptes.",
  },
  {
    id: "obligations-client",
    title: "Obligations du Client",
    description: "Rappelle que contenus, acces et validations conditionnent les delais.",
    content: "Le Client s'engage a fournir dans les delais utiles les informations, contenus, acces, validations et arbitrages necessaires. Les retards ou insuffisances imputables au Client reportent les delais d'execution a due concurrence.",
  },
  {
    id: "retard-paiement",
    title: "Retard de paiement",
    description: "Suspension possible en cas d'impaye.",
    content: "En cas de retard de paiement, le Prestataire peut suspendre les travaux en cours apres information du Client, sans que cette suspension puisse etre consideree comme un manquement contractuel.",
  },
  {
    id: "responsabilite",
    title: "Limitation de responsabilite",
    description: "Limite aux dommages directs, hors pertes indirectes.",
    content: "La responsabilite du Prestataire est limitee aux dommages directs, certains et prouves, a l'exclusion des pertes d'exploitation, pertes de chiffre d'affaires, pertes de donnees indirectes, prejudice commercial indirect ou atteinte a l'image.",
  },
  {
    id: "force-majeure",
    title: "Force majeure",
    description: "Couvre les evenements imprevisibles empechant l'execution.",
    content: "Aucune Partie ne peut etre tenue responsable d'un manquement cause par un evenement de force majeure au sens du droit applicable, pendant la duree ou cet evenement empeche raisonnablement l'execution de ses obligations.",
  },
  {
    id: "reversibilite",
    title: "Reversibilite",
    description: "Sortie propre et restitution des elements utiles.",
    content: "A la fin du contrat, le Prestataire restitue les elements utiles en sa possession et facilite une passation raisonnable, sous reserve du paiement des sommes dues et dans la limite du perimetre convenu.",
  },
  {
    id: "non-sollicitation",
    title: "Non-sollicitation",
    description: "Protege les equipes et partenaires pendant la mission.",
    content: "Sauf accord prealable, chaque Partie s'interdit de solliciter directement les collaborateurs, sous-traitants ou partenaires presentes par l'autre Partie dans le cadre de la mission, pendant la mission et pendant une duree raisonnable apres son terme.",
  },
  {
    id: "signature-electronique",
    title: "Signature electronique",
    description: "Reconnaissance de la signature électronique enregistrée dans le CRM.",
    content: "Les Parties reconnaissent que la signature electronique du present contrat produit les memes effets qu'une signature manuscrite, sous reserve de l'identification du signataire et de la conservation de la preuve de signature.",
  },
]

export const CONTRACT_CLAUSE_LIBRARY: ContractClausePreset[] =
  RAW_CONTRACT_CLAUSE_LIBRARY.map(formatClausePreset)
