import { Building2, Inbox, Kanban, UserRoundSearch, Users } from "lucide-react"
import { getWorkspaceOverview } from "@/actions/workspaces"
import { OnboardingRequired } from "@/components/shared/onboarding-required"
import { WorkspaceHub } from "@/app/dashboard/_components/workspace-hub"

export default async function CrmWorkspacePage() {
  const data = await getWorkspaceOverview()
  if (!data) return <OnboardingRequired title="Configurez votre espace" description="Créez le profil entreprise avant d’utiliser le CRM." />
  return <WorkspaceHub eyebrow="Espace CRM" title="Clients et relations" description="Retrouvez les personnes, entreprises, demandes et conversations qui nécessitent une action." primaryAction={{ name: "Ajouter un client", href: "/dashboard/clients", icon: Building2, description: "Créer une fiche" }} metrics={[{ label: "Clients", value: data.clients, detail: `${data.contacts} contact(s) associé(s)` }, { label: "Prospects actifs", value: data.activeLeads, detail: "Hors spam et archives", alert: data.activeLeads > 0 }, { label: "Affaires ouvertes", value: data.openDeals, detail: "Opportunités non closes" }, { label: "Messages non lus", value: data.unreadEmail, detail: "Dans la boîte partagée", alert: data.unreadEmail > 0 }]} sections={[{ title: "Référentiel", description: "Les dossiers et interlocuteurs de l’entreprise.", links: [{ name: "Clients", href: "/dashboard/clients", icon: Building2, description: "Fiches, documents, projets, portail et données financières." }, { name: "Contacts", href: "/dashboard/contacts", icon: Users, description: "Interlocuteurs, coordonnées, fonction et client associé." }] }, { title: "Relation commerciale", description: "De la première demande à l’affaire gagnée.", links: [{ name: "Prospects", href: "/dashboard/leads", icon: UserRoundSearch, description: "Qualifier les demandes, consentements et prochaines actions." }, { name: "Affaires", href: "/dashboard/pipeline", icon: Kanban, description: "Piloter étapes, valeur, probabilité et date de clôture." }, { name: "Communications", href: "/dashboard/communications", icon: Inbox, description: "Lire les échanges et répondre avec le contexte client." }] }]} />
}
