import fs from "node:fs/promises"
import path from "node:path"
import assert from "node:assert/strict"
import { chromium, expect } from "@playwright/test"
import puppeteer from "puppeteer"
import { PrismaClient } from "@prisma/client"

const directory = process.argv[2] && path.resolve(process.argv[2])
if (!directory) throw new Error("Dossier de démonstration requis")
const access = JSON.parse(await fs.readFile(path.join(directory, "demo-access.json"), "utf8"))
const running = JSON.parse(await fs.readFile(path.join(directory, "demo-running.json"), "utf8"))
if (access.schema !== "freelio.local-demo.v1" || !Number.isInteger(running.port)) throw new Error("Démo locale invalide")
const baseURL = `http://127.0.0.1:${running.port}`
const report = { baseURL, testedAt: new Date().toISOString(), pages: [], checks: [], unexpectedErrors: [], externalRequestsBlocked: 0 }
const evidence = path.join(directory, "verification")
await fs.mkdir(evidence, { recursive: true })
const database = new PrismaClient({ datasources: { db: { url: `file:${path.join(directory, "demo.db").replaceAll("\\", "/")}` } } })
const browser = await chromium.launch({ executablePath: await puppeteer.executablePath(), args: ["--disable-background-networking", "--disable-component-update"] })
try {
  const context = await browser.newContext({ baseURL, viewport: { width: 1440, height: 1000 }, reducedMotion: "reduce" })
  await context.route("**/*", async route => {
    const url = new URL(route.request().url())
    if (url.origin === baseURL || ["data:", "about:", "blob:"].includes(url.protocol)) await route.continue()
    else { report.externalRequestsBlocked++; await route.abort() }
  })
  const page = await context.newPage()
  page.setDefaultTimeout(30_000)
  page.setDefaultNavigationTimeout(180_000)
  page.on("pageerror", error => report.unexpectedErrors.push(error.message))
  await page.goto("/auth/login")
  await page.getByLabel("Adresse e-mail professionnelle").fill(access.email)
  await page.getByRole("button", { name: "Se connecter", exact: true }).click()
  await page.getByText("Identifiants ou code de sécurité incorrects.", { exact: true }).first().waitFor()
  await expect(page.getByRole("button", { name: "Se connecter", exact: true })).toBeEnabled()
  assert.equal(new URL(page.url()).pathname, "/auth/login")
  assert.equal(await page.getByLabel("Adresse e-mail professionnelle").inputValue(), access.email)
  report.checks.push("Demo password bypass denied")
  await page.getByLabel("Mot de passe", { exact: true }).fill(access.password)
  await page.getByRole("button", { name: "Se connecter", exact: true }).click()
  await page.waitForURL(url => url.pathname === "/dashboard", { timeout: 180_000 })
  await page.locator("#dashboard-main").waitFor()
  assert(await page.getByText("Démonstration — données fictives", { exact: true }).isVisible())
  report.checks.push("Password login and demo notice")
  await page.goto("/")
  const marketing = await page.locator("body").innerText()
  assert(!marketing.includes("CONFORME"))
  assert(!/[Pp]rêt à émettre/.test(marketing))
  assert(marketing.includes("Exemple à vérifier"))
  report.checks.push("Demo marketing examples avoid unproved certification claims")
  for (const route of ["/confidentialite", "/conditions"]) {
    await page.goto(route)
    assert(await page.getByText("Cette instance locale contient des données fictives et n’est pas ouverte à un usage commercial. N’y importez pas de données réelles.", { exact: true }).isVisible())
  }
  report.checks.push("Demo-only usage disclosures")
  const company = await database.company.findFirstOrThrow({ where: { email: access.email } })
  const client = await database.client.findFirstOrThrow({ where: { companyId: company.id } })
  const quote = await database.quote.findFirstOrThrow({ where: { companyId: company.id, status: "DRAFT" } })
  const invoice = await database.invoice.findFirstOrThrow({ where: { companyId: company.id, status: "DRAFT" } })
  const paths = ["/dashboard", "/dashboard/clients", `/dashboard/clients/${client.id}`, "/dashboard/devis", `/dashboard/devis/${quote.id}`, "/dashboard/factures", `/dashboard/factures/${invoice.id}`, "/dashboard/projets", "/dashboard/organisation", "/dashboard/service/help-desk", "/dashboard/terrain", "/dashboard/settings", "/dashboard/data", "/dashboard/depenses"]
  for (const route of paths) {
    const start = Date.now()
    const response = await page.goto(route)
    assert(response && response.status() === 200, `Page failed: ${route}`)
    await page.locator("#dashboard-main").waitFor()
    const main = await page.locator("#dashboard-main").innerText()
    assert(!/Erreur de chargement|Runtime Error|Application error/.test(main), `Error boundary: ${route}`)
    report.pages.push({ route, status: response.status(), loadMs: Date.now() - start })
  }
  const quotePdf = await page.request.get(`/api/pdf/devis/${quote.id}`)
  assert.equal(quotePdf.status(), 200, "Draft quote PDF")
  assert.equal((await quotePdf.body()).subarray(0, 4).toString(), "%PDF")
  report.checks.push("Draft quote PDF download")
  const pdfHeaders = await page.request.get(`/api/pdf/facture/${invoice.id}?screen=1`)
  assert.equal(pdfHeaders.headers()["x-frame-options"], "SAMEORIGIN")
  assert(pdfHeaders.headers()["content-security-policy"].includes("frame-ancestors 'self'"))
  report.checks.push("Invoice preview same-origin frame headers")
  const exportResponse = await page.request.get("/api/backup/export")
  assert.equal(exportResponse.status(), 200)
  const payload = await exportResponse.json()
  assert.equal(payload.scope.companyId, company.id)
  assert.equal(payload.manifest.status, "COMPLETE")
  report.checks.push("Company backup HTTP export")
  await page.goto(`/dashboard/devis/new?clientId=${client.id}`)
  const object = `Recette fictive ${Date.now()}`
  await page.getByLabel("Objet *", { exact: true }).fill(object)
  await page.getByLabel("Libellé de la ligne 1", { exact: true }).fill("Prestation fictive de vérification")
  await page.getByLabel("Quantité de la ligne 1", { exact: true }).fill("2")
  await page.getByLabel("Prix unitaire hors taxes de la ligne 1", { exact: true }).fill("123.45")
  await page.getByRole("button", { name: "Créer le brouillon", exact: true }).click()
  await page.waitForURL(url => url.pathname !== "/dashboard/devis/new" && /^\/dashboard\/devis\/[^/]+$/.test(url.pathname), { timeout: 180_000 })
  const createdId = new URL(page.url()).pathname.split("/").pop()
  const created = await database.quote.findUniqueOrThrow({ where: { id: createdId }, include: { versions: { orderBy: { version: "desc" }, take: 1 } } })
  assert.equal(created.companyId, company.id)
  assert.equal(created.clientId, client.id)
  assert.equal(created.status, "DRAFT")
  assert.equal(created.versions[0].totalHtCents, 24690)
  assert.equal(created.versions[0].totalTvaCents, 4938)
  assert.equal(created.versions[0].totalTtcCents, 29628)
  await page.goto(`/dashboard/devis/${created.id}/edit`)
  await page.getByLabel("Quantité de la ligne 1", { exact: true }).fill("3")
  await page.getByRole("button", { name: "Enregistrer les modifications", exact: true }).click()
  await page.waitForURL(url => url.pathname === `/dashboard/devis/${created.id}`, { timeout: 180_000 })
  const edited = await database.quoteVersion.findFirstOrThrow({ where: { quoteId: created.id }, orderBy: { version: "desc" } })
  assert.equal(edited.totalHtCents, 37035)
  assert.equal(edited.totalTvaCents, 7407)
  assert.equal(edited.totalTtcCents, 44442)
  report.checks.push("Create and edit a quote through the UI with database-verified cent totals")
  await page.goto("/dashboard/settings")
  await page.getByRole("tab", { name: "Intégrations", exact: true }).click()
  await page.getByText("État des services externes", { exact: true }).waitFor()
  assert(!(await page.locator("#dashboard-main").innerText()).includes("Gemini"))
  await page.getByRole("tab", { name: "Facturation", exact: true }).click()
  await page.getByText("Relances de factures", { exact: true }).waitFor()
  assert(!(await page.locator("#dashboard-main").innerText()).includes("Assistant IA"))
  report.checks.push("Removed AI integration and usage meter")
  await page.goto("/dashboard/depenses")
  await page.getByRole("button", { name: "Saisie manuelle", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "Enregistrer une dépense", exact: true })
  await dialog.getByText("Joignez votre justificatif", { exact: true }).waitFor()
  const expenseLabel = `Justificatif fictif ${Date.now()}`
  await dialog.getByLabel("Libellé *", { exact: true }).fill(expenseLabel)
  await dialog.getByLabel("Fournisseur", { exact: true }).fill("Fournisseur de recette fictif")
  await dialog.getByLabel("Montant TTC (€) *", { exact: true }).fill("123.45")
  await dialog.getByLabel("TVA (€)", { exact: true }).fill("20.57")
  const receipt = await quotePdf.body()
  await dialog.locator('input[type="file"]').setInputFiles({ name: "justificatif-fictif.pdf", mimeType: "application/pdf", buffer: receipt })
  await dialog.getByText("justificatif-fictif.pdf", { exact: true }).waitFor()
  assert.equal(await dialog.getByLabel("Montant TTC (€) *", { exact: true }).inputValue(), "123.45")
  const upload = page.waitForResponse(response => response.url().includes("/api/files/expense/") && response.request().method() === "POST" && response.request().headers()["content-type"]?.startsWith("multipart/form-data"))
  await dialog.getByRole("button", { name: "Créer", exact: true }).click()
  assert.equal((await upload).status(), 201)
  await dialog.waitFor({ state: "hidden" })
  const expense = await database.expense.findFirstOrThrow({ where: { companyId: company.id, label: expenseLabel }, include: { files: true } })
  assert.equal(expense.amountCents, 12345)
  assert.equal(expense.tvaCents, 2057)
  assert.equal(expense.files.length, 1)
  const downloaded = await page.request.get(`/api/files/expense/${expense.files[0].id}`)
  assert.equal(downloaded.status(), 200)
  assert.deepEqual(await downloaded.body(), receipt)
  report.checks.push("Manual expense and PDF attachment retained without AI or amount replacement")
  const anonymous = await browser.newContext({ baseURL })
  try {
    assert.equal((await anonymous.request.get(`/api/pdf/devis/${quote.id}`)).status(), 401)
    assert.equal((await anonymous.request.get("/api/backup/export")).status(), 401)
    report.checks.push("Anonymous PDF and backup access denied")
  } finally { await anonymous.close() }
  await page.goto("/dashboard/clients")
  await page.keyboard.press("Tab")
  await page.getByRole("link", { name: "Aller au contenu", exact: true }).focus()
  await page.keyboard.press("Enter")
  assert((await page.url()).endsWith("#dashboard-main"))
  report.checks.push("Keyboard skip link")
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/dashboard")
  await page.getByRole("button", { name: "Ouvrir la navigation", exact: true }).click()
  await page.getByRole("button", { name: "Fermer la navigation", exact: true }).click()
  const dimensions = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth }))
  assert(dimensions.scroll <= dimensions.width + 1)
  report.checks.push("Mobile navigation and viewport width")
  await page.screenshot({ path: path.join(evidence, "demo-mobile.png"), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(`/dashboard/factures/${invoice.id}`)
  await page.screenshot({ path: path.join(evidence, "demo-invoice.png"), fullPage: true })
  assert.deepEqual(report.unexpectedErrors, [])
  report.success = true
  console.log(JSON.stringify({ success: true, pages: report.pages.length, checks: report.checks.length, report: path.join(evidence, "browser-report.json") }))
} finally {
  await fs.writeFile(path.join(evidence, "browser-report.json"), JSON.stringify(report, null, 2))
  await browser.close()
  await database.$disconnect()
}
