import NextAuth from "next-auth"
import { NextResponse } from "next/server"
import { authConfig } from "./auth.config"

const { auth } = NextAuth(authConfig)

const NONCE_PROTECTED_PREFIXES = [
  "/dashboard",
  "/onboarding",
  "/portal",
  "/sign",
  "/join",
  "/feedback",
  "/consent",
] as const

function requiresStrictCsp(pathname: string): boolean {
  return NONCE_PROTECTED_PREFIXES.some(
    (prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`),
  )
}

function buildStrictCsp(nonce: string): string {
  const developmentEval = process.env.NODE_ENV === "development" ? " 'unsafe-eval'" : ""
  const upgradeInsecureRequests = process.env.NODE_ENV === "production" ? " upgrade-insecure-requests;" : ""
  // Deterministic bootstrap generated by next-themes 0.4.6 for our fixed provider options.
  // Its hash is deliberately pinned: dependency or option changes must fail E2E until reviewed.
  const themeBootstrapHash = "'sha256-TiyWB4YB4NUrUHDJSqaW0w0OtUb7i0Tddwwo6j0O07c='"

  return `default-src 'self'; base-uri 'self'; object-src 'none'; form-action 'self'; script-src 'self' 'nonce-${nonce}' ${themeBootstrapHash} 'strict-dynamic'${developmentEval} https://va.vercel-scripts.com; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data: https:; font-src 'self' data:; connect-src 'self'; frame-ancestors 'none';${upgradeInsecureRequests}`
}

export default auth((request) => {
  if (!requiresStrictCsp(request.nextUrl.pathname)) {
    return NextResponse.next()
  }

  const nonce = btoa(crypto.randomUUID())
  const contentSecurityPolicy = buildStrictCsp(nonce)
  const requestHeaders = new Headers(request.headers)
  requestHeaders.set("x-nonce", nonce)
  requestHeaders.set("Content-Security-Policy", contentSecurityPolicy)

  const response = NextResponse.next({ request: { headers: requestHeaders } })
  response.headers.set("Content-Security-Policy", contentSecurityPolicy)
  return response
})

export const config = {
  // Use 'proxy' instead of 'middleware' for Next.js 15.2+ / 16
  matcher: [{
    source: "/((?!api|_next/static|_next/image|auth|logo\\.png|favicon.ico|.*\\.png$).*)",
    missing: [
      { type: "header", key: "next-router-prefetch" },
      { type: "header", key: "purpose", value: "prefetch" },
    ],
  }],
}
