import { randomUUID } from "node:crypto"
import { afterAll, afterEach, beforeEach, describe, expect, it, vi } from "vitest"
const session = vi.hoisted(() => ({ userId: "", companyId: "" }))
vi.mock("server-only", () => ({}))
vi.mock("@/auth", () => ({ auth: async () => ({ user: { id: session.userId }, companyId: session.companyId }) }))
vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }))
import prisma from "@/lib/prisma"
import { encrypt } from "@/lib/crypto"
import { withProcessorLease } from "@/lib/processing/lease"
import { checkSequenceEmailResult, repairSequenceEmailHistory, closeSequenceEmailWithoutRetry, getAutomationDeliveryDetails, retryEmailDelivery } from "@/actions/automations"

describe.sequential("human sequence recovery uses real authorization and SQL without another send", () => {
  const companies: string[] = [], users: string[] = []
  const http = vi.fn<(url: string | URL | Request, init?: RequestInit) => Promise<Response>>(async () => { throw new Error("Unexpected fictional provider request") })
  beforeEach(() => { vi.clearAllMocks(); vi.stubGlobal("fetch", http) })
  afterEach(() => { vi.unstubAllGlobals(); vi.unstubAllEnvs() })
  afterAll(async () => {
    await prisma.auditLog.deleteMany({ where: { userId: { in: users } } })
    for (const id of companies) await prisma.company.delete({ where: { id } })
    await prisma.user.deleteMany({ where: { id: { in: users } } })
    await prisma.processorLease.deleteMany({ where: { name: "email-sequences" } })
  })
  async function fixture(provider: "RESEND" | "GOOGLE" | "MICROSOFT" = "RESEND") {
    const company = await prisma.company.create({ data: { name: "Fictional sequence recovery" } }); companies.push(company.id)
    const user = await prisma.user.create({ data: { email: `sequence-recovery-${randomUUID()}@example.test` } }); users.push(user.id)
    const membership = await prisma.membership.create({ data: { companyId: company.id, userId: user.id, role: "OWNER" } })
    const lead = await prisma.leadCapture.create({ data: { companyId: company.id, firstName: "Fiction", lastName: "Recovery", email: "recipient@example.test", privacyAccepted: true, fingerprint: randomUUID() } })
    const channel = await prisma.communicationChannel.create({ data: { companyId: company.id, ownerUserId: user.id, provider, status: "ACTIVE", visibility: "PRIVATE", emailAddress: "sender@example.test",
      credentialsEncrypted: encrypt(JSON.stringify(provider === "RESEND" ? { mode: "BYOK", apiKey: "fiction-resend-key-only", webhookSecret: "fiction-webhook-key-only" } : { mode: "OAUTH", accessToken: "fiction-access-token-only", refreshToken: "fiction-refresh-token-only", expiresAt: "2099-01-01T00:00:00.000Z", scope: provider === "GOOGLE" ? "https://www.googleapis.com/auth/gmail.modify" : "Mail.ReadWrite Mail.Send" })) } })
    const sequence = await prisma.emailSequence.create({ data: { companyId: company.id, senderChannelId: channel.id, name: "Fictional recovery sequence", status: "ARCHIVED", steps: { create: { position: 0, subject: "Fictional frozen mail", bodyHtml: "<p>Fictional original</p>" } } }, include: { steps: true } })
    const enrollment = await prisma.emailSequenceEnrollment.create({ data: { sequenceId: sequence.id, leadCaptureId: lead.id, status: "PAUSED", stopReason: "DELIVERY_RESULT_UNCERTAIN" } })
    const payload = { kind: "SEQUENCE", companyName: company.name, replyTo: null, from: "sender@example.test", to: lead.email!, subject: "Fictional frozen mail", html: "<p>Fictional original</p>", headers: {} }
    const delivery = await prisma.emailDelivery.create({ data: { companyId: company.id, sequenceId: sequence.id, stepId: sequence.steps[0].id, enrollmentId: enrollment.id, leadCaptureId: lead.id, channelId: channel.id, provider,
      payload, subject: payload.subject, recipientEmail: payload.to, purpose: null, status: "DEAD_LETTER", attempts: 2, firstAttemptAt: new Date(Date.now() - 86_400_000), scheduledAt: new Date(), providerMessageId: provider === "RESEND" ? null : "<fiction-sequence@example.test>", providerDraftId: provider === "MICROSOFT" ? "immutable-fiction-draft" : null } })
    const login = () => { session.companyId = company.id; session.userId = user.id }; login()
    const recover = (operation: "CHECK" | "REPAIR" | "CLOSE", extra = {}) => ({ CHECK: checkSequenceEmailResult, REPAIR: repairSequenceEmailHistory, CLOSE: closeSequenceEmailWithoutRetry }[operation])({ id: delivery.id, version: 1, ...extra })
    return { company, user, membership, lead, channel, sequence, enrollment, payload, delivery, login, recover }
  }
  it("keeps an unknown result unknown after reasoned closure and stops only this enrollment", async () => {
    const f = await fixture()
    expect(await f.recover("REPAIR")).toMatchObject({ success: false, error: expect.stringContaining("Aucune preuve") })
    expect(await f.recover("CLOSE")).toMatchObject({ success: false, error: expect.stringContaining("motif") })
    expect(await f.recover("CHECK")).toMatchObject({ success: true, outcome: "UNKNOWN" })
    expect(await f.recover("CLOSE", { version: 2, reason: "Fictional private decision", confirmed: true })).toMatchObject({ success: true, outcome: "UNKNOWN" })
    expect(await prisma.emailDelivery.findUniqueOrThrow({ where: { id: f.delivery.id } })).toMatchObject({ payload: f.payload, status: "DEAD_LETTER", closedAt: expect.any(Date), closedByUserId: f.user.id, closureReason: "Fictional private decision", nextAttemptAt: null })
    expect(await prisma.emailSequenceEnrollment.findUniqueOrThrow({ where: { id: f.enrollment.id } })).toMatchObject({ status: "STOPPED", nextStepPosition: 0, nextSendAt: null, stopReason: "DELIVERY_CLOSED_WITHOUT_RETRY" })
    expect(await retryEmailDelivery(f.delivery.id)).toMatchObject({ success: false })
    const detail = await getAutomationDeliveryDetails(f.delivery.id)
    expect(detail?.recovery).toMatchObject({ outcome: "UNKNOWN", canClose: false, canRepair: false, canCheck: true, enrollmentStatus: "STOPPED" })
    expect(JSON.stringify(detail)).not.toContain("Fictional private decision")
    expect(await prisma.emailMessage.count({ where: { deliveryId: f.delivery.id } })).toBe(0)
    expect(http).not.toHaveBeenCalled()
  })
  it("repairs a known acceptance twice, preserving pause, frozen content, null purpose and a bounce", async () => {
    const f = await fixture()
    await prisma.emailDelivery.update({ where: { id: f.delivery.id }, data: { providerId: "fiction-sequence-accepted", sentAt: new Date(), status: "BOUNCED", lastEventAt: new Date() } })
    expect(await f.recover("CLOSE", { reason: "Must retain acceptance", confirmed: true })).toMatchObject({ success: false, error: expect.stringContaining("acceptation") })
    expect(await f.recover("REPAIR")).toMatchObject({ success: true })
    expect(await f.recover("REPAIR", { version: 2 })).toMatchObject({ success: true })
    expect(await prisma.emailMessage.count({ where: { deliveryId: f.delivery.id } })).toBe(1)
    expect(await prisma.emailMessage.findUniqueOrThrow({ where: { deliveryId: f.delivery.id } })).toMatchObject({ purpose: null, status: "BOUNCED", bodyHtml: f.payload.html, fromAddress: f.payload.from, toAddresses: [f.payload.to] })
    expect(await prisma.emailSequenceEnrollment.findUniqueOrThrow({ where: { id: f.enrollment.id } })).toEqual(f.enrollment)
    expect((await prisma.emailDelivery.findUniqueOrThrow({ where: { id: f.delivery.id } })).status).toBe("BOUNCED")
    expect(http).not.toHaveBeenCalled()
  })
  it("correlates Gmail through GET only and repairs without another HTTP request", async () => {
    const f = await fixture("GOOGLE")
    http.mockImplementation(async (url, init) => {
      expect(init?.method).toBe("GET")
      if (new URL(String(url)).pathname.endsWith("/messages")) return Response.json({ messages: [{ id: "fiction-sequence-sent" }] })
      return Response.json({ id: "fiction-sequence-sent", labelIds: ["SENT"], payload: { headers: [{ name: "Message-ID", value: f.delivery.providerMessageId }, { name: "From", value: f.payload.from }] } })
    })
    expect(await f.recover("CHECK")).toMatchObject({ outcome: "ACCEPTED" })
    expect(await f.recover("REPAIR", { version: 2 })).toMatchObject({ success: true })
    expect(http).toHaveBeenCalledTimes(2)
    expect(await prisma.emailMessage.findUniqueOrThrow({ where: { deliveryId: f.delivery.id } })).toMatchObject({ providerId: `${f.channel.id}:fiction-sequence-sent`, purpose: null })
    expect((await prisma.emailSequenceEnrollment.findUniqueOrThrow({ where: { id: f.enrollment.id } })).status).toBe("PAUSED")
  })
  it("retains a late positive proof after closure without repairing or reactivating the stopped occurrence", async () => {
    const f = await fixture("MICROSOFT")
    expect(await f.recover("CLOSE", { reason: "Fictional uncertainty", confirmed: true })).toMatchObject({ success: true })
    http.mockImplementation(async (_url, init) => { expect(init?.method).toBe("GET"); return Response.json({ id: f.delivery.providerDraftId, isDraft: false, internetMessageId: f.delivery.providerMessageId, from: { emailAddress: { address: f.payload.from } }, sentDateTime: "2026-01-01T12:00:00Z" }) })
    expect(await f.recover("CHECK", { version: 2 })).toMatchObject({ outcome: "ACCEPTED" })
    expect(await f.recover("REPAIR", { version: 3 })).toMatchObject({ success: false, error: expect.stringContaining("classée") })
    expect((await prisma.emailSequenceEnrollment.findUniqueOrThrow({ where: { id: f.enrollment.id } })).status).toBe("STOPPED")
    expect(await prisma.emailMessage.count({ where: { deliveryId: f.delivery.id } })).toBe(0)
  })
  it("never interprets a Graph draft or ambiguous Google search as acceptance", async () => {
    const f = await fixture("MICROSOFT")
    http.mockResolvedValue(Response.json({ id: f.delivery.providerDraftId, isDraft: true, internetMessageId: f.delivery.providerMessageId, from: { emailAddress: { address: f.payload.from } } }))
    expect(await f.recover("CHECK")).toMatchObject({ outcome: "DRAFT" })
    expect(await f.recover("REPAIR", { version: 2 })).toMatchObject({ success: false })
    const g = await fixture("GOOGLE")
    http.mockResolvedValue(Response.json({ messages: [{ id: "one" }, { id: "two" }] }))
    expect(await g.recover("CHECK")).toMatchObject({ outcome: "UNKNOWN" })
  })
  it.each([403, 404, 429])("keeps HTTP %i unavailable without storing or exposing its body", async status => {
    const f = await fixture("GOOGLE")
    http.mockResolvedValue(new Response("fictional-private-address@example.test secret-body", { status }))
    const result = await f.recover("CHECK")
    expect(result).toMatchObject({ outcome: "UNAVAILABLE" })
    expect(JSON.stringify(result)).not.toContain("secret-body")
    expect((await prisma.emailDelivery.findUniqueOrThrow({ where: { id: f.delivery.id } })).recoveryProof).toBeNull()
  })
  it("rereads current membership and mailbox access after provider inspection", async () => {
    const f = await fixture("GOOGLE")
    http.mockImplementation(async () => { await prisma.membership.update({ where: { id: f.membership.id }, data: { status: "SUSPENDED" } }); return Response.json({ messages: [] }) })
    expect(await f.recover("CHECK")).toMatchObject({ success: false, error: expect.stringContaining("inaccessible") })
    expect((await prisma.emailDelivery.findUniqueOrThrow({ where: { id: f.delivery.id } })).recoveryVersion).toBe(1)
    await prisma.membership.update({ where: { id: f.membership.id }, data: { status: "ACTIVE", role: "SALES" } })
    const foreign = await fixture(); f.login()
    await prisma.communicationChannel.update({ where: { id: f.channel.id }, data: { ownerUserId: foreign.user.id } })
    expect(await f.recover("CHECK")).toMatchObject({ success: false })
    expect(await getAutomationDeliveryDetails(f.delivery.id)).toBeNull()
  })
  it("supports a non-admin member repairing the first message in their own mailbox", async () => {
    const f = await fixture()
    await prisma.membership.update({ where: { id: f.membership.id }, data: { role: "SALES" } })
    await prisma.emailDelivery.update({ where: { id: f.delivery.id }, data: { providerId: "fiction-sales-accepted", sentAt: new Date(), status: "SENT" } })
    expect(await f.recover("REPAIR")).toMatchObject({ success: true })
    expect(await prisma.emailMessage.count({ where: { deliveryId: f.delivery.id } })).toBe(1)
  })
  it("refuses foreign commands, read-only roles, stale versions and incomplete historical payloads", async () => {
    const f = await fixture(), foreign = await fixture()
    expect(await f.recover("CHECK")).toMatchObject({ success: false }); foreign.login()
    await prisma.membership.update({ where: { id: foreign.membership.id }, data: { role: "VIEWER" } })
    await expect(foreign.recover("CHECK")).rejects.toThrow("droits")
    f.login()
    expect(await f.recover("CHECK", { version: 2 })).toMatchObject({ success: false, error: expect.stringContaining("changé") })
    await prisma.emailDelivery.update({ where: { id: f.delivery.id }, data: { payload: { kind: "SEQUENCE" } } })
    expect(await f.recover("CLOSE", { reason: "Fictional closure", confirmed: true })).toMatchObject({ success: false, error: expect.stringContaining("historiques") })
  })
  it("refuses while the processor owns its shared lease or the enrollment is active", async () => {
    const f = await fixture()
    await withProcessorLease("email-sequences", async () => { expect(await f.recover("CHECK")).toMatchObject({ success: false, error: expect.stringContaining("occupé") }) })
    expect(http).not.toHaveBeenCalled()
    await prisma.emailSequenceEnrollment.update({ where: { id: f.enrollment.id }, data: { status: "ACTIVE" } })
    expect(await f.recover("CLOSE", { reason: "Fictional closure", confirmed: true })).toMatchObject({ success: false, error: expect.stringContaining("pause") })
  })
  it("does not overwrite an acceptance arriving between provider inspection and commit", async () => {
    const f = await fixture("GOOGLE")
    http.mockImplementation(async () => { await prisma.emailDelivery.update({ where: { id: f.delivery.id }, data: { providerId: `${f.channel.id}:late`, sentAt: new Date(), status: "SENT" } }); return Response.json({ messages: [] }) })
    expect(await f.recover("CHECK")).toMatchObject({ success: false, error: expect.stringContaining("changé") })
    expect(await prisma.emailDelivery.findUniqueOrThrow({ where: { id: f.delivery.id } })).toMatchObject({ recoveryVersion: 1, status: "SENT", recoveryCheckedAt: null })
    expect(await prisma.emailSequenceEnrollment.findUniqueOrThrow({ where: { id: f.enrollment.id } })).toEqual(f.enrollment)
  })
  it("refuses a concurrent resume and mismatched sequence references without saving an observation", async () => {
    const f = await fixture("GOOGLE")
    http.mockImplementation(async () => { await prisma.emailSequenceEnrollment.update({ where: { id: f.enrollment.id }, data: { status: "ACTIVE", nextSendAt: new Date() } }); return Response.json({ messages: [] }) })
    expect(await f.recover("CHECK")).toMatchObject({ success: false, error: expect.stringContaining("changé") })
    expect((await prisma.emailDelivery.findUniqueOrThrow({ where: { id: f.delivery.id } })).recoveryVersion).toBe(1)
    await prisma.emailSequenceEnrollment.update({ where: { id: f.enrollment.id }, data: { status: "PAUSED", nextStepPosition: 1 } })
    expect(await f.recover("CHECK")).toMatchObject({ success: false, error: expect.stringContaining("pause") })
    const other = await fixture(); f.login()
    await prisma.emailDelivery.update({ where: { id: f.delivery.id }, data: { stepId: other.sequence.steps[0].id } })
    expect(await f.recover("CHECK")).toMatchObject({ success: false, error: expect.stringContaining("inaccessible") })
  })
  it("does not repair from a proof belonging to another mailbox or disclose that proof in details", async () => {
    const f = await fixture("GOOGLE")
    await prisma.emailDelivery.update({ where: { id: f.delivery.id }, data: { recoveryOutcome: "ACCEPTED", recoveryProof: { provider: "GOOGLE", channelId: "foreign-box", providerId: "foreign-box:private-id", providerMessageId: f.delivery.providerMessageId, checkedAt: new Date().toISOString() } } })
    expect(await f.recover("REPAIR")).toMatchObject({ success: false, error: expect.stringContaining("Aucune preuve") })
    const detail = await getAutomationDeliveryDetails(f.delivery.id)
    expect(detail?.recovery?.canRepair).toBe(false)
    expect(detail?.recovery?.outcome).toBe("UNKNOWN")
    expect(JSON.stringify(detail)).not.toMatch(/foreign-box|private-id|Fictional original/)
  })
  it.each(["CLOSE", "REPAIR"] as const)("rolls back %s, history and enrollment if the audit cannot commit", async operation => {
    const f = await fixture()
    if (operation === "REPAIR") await prisma.emailDelivery.update({ where: { id: f.delivery.id }, data: { providerId: "fiction-fault-accepted", sentAt: new Date(), status: "SENT" } })
    const before = await prisma.emailDelivery.findUniqueOrThrow({ where: { id: f.delivery.id } })
    const name = `fiction_recovery_fault_${randomUUID().replaceAll("-", "")}`, pg = process.env.DATABASE_URL?.startsWith("postgres")
    const condition = `NEW."resourceId" = '${f.delivery.id}' AND NEW."action" LIKE '%SEQUENCE_EMAIL%'`
    if (pg) {
      await prisma.$executeRawUnsafe(`CREATE FUNCTION "${name}"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF ${condition} THEN RAISE EXCEPTION 'fictional audit fault'; END IF; RETURN NEW; END; $$`)
      await prisma.$executeRawUnsafe(`CREATE TRIGGER "${name}" BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION "${name}"()`)
    } else await prisma.$executeRawUnsafe(`CREATE TRIGGER "${name}" BEFORE INSERT ON "AuditLog" WHEN ${condition} BEGIN SELECT RAISE(ABORT, 'fictional audit fault'); END`)
    try { expect(await f.recover(operation, { reason: "Fictional decision", confirmed: true })).toMatchObject({ success: false }) } finally {
      await prisma.$executeRawUnsafe(`DROP TRIGGER "${name}"${pg ? ' ON "AuditLog"' : ""}`)
      if (pg) await prisma.$executeRawUnsafe(`DROP FUNCTION "${name}"()`)
    }
    expect(await prisma.emailDelivery.findUniqueOrThrow({ where: { id: f.delivery.id } })).toEqual(before)
    expect(await prisma.emailSequenceEnrollment.findUniqueOrThrow({ where: { id: f.enrollment.id } })).toEqual(f.enrollment)
    expect(await prisma.emailMessage.count({ where: { deliveryId: f.delivery.id } })).toBe(0)
    expect(await prisma.auditLog.count({ where: { userId: f.user.id } })).toBe(0)
    expect(await f.recover(operation, { reason: "Fictional decision", confirmed: true })).toMatchObject({ success: true })
  })
  it("blocks provider checks and every decision in the public demo", async () => {
    const f = await fixture(); vi.stubEnv("DEMO_ACCESS_MODE", "readonly")
    for (const operation of ["CHECK", "REPAIR", "CLOSE"] as const) await expect(f.recover(operation)).rejects.toThrow("lecture seule")
    expect(http).not.toHaveBeenCalled()
    expect(await prisma.emailDelivery.findUniqueOrThrow({ where: { id: f.delivery.id } })).toEqual(f.delivery)
  })
})
