import { CalendarDays, FileSignature, FileText, Kanban, Package, Target } from "lucide-react"
import { getWorkspaceOverview } from "@/actions/workspaces"
import { OnboardingRequired } from "@/components/shared/onboarding-required"
import { WorkspaceHub, formatWorkspaceEuro } from "@/app/dashboard/_components/workspace-hub"

export default async function SalesWorkspacePage() {
  const data = await getWorkspaceOverview()
  if (!data) return <OnboardingRequired title="Configurez votre espace" description="Créez le profil entreprise avant de piloter les ventes." />
  return <WorkspaceHub eyebrow="Espace ventes" title="Transformer les projets en commandes" description="Une vue commerciale centrée sur les affaires, les rendez-vous, les offres et la signature." primaryAction={{ name: "Nouveau devis", href: "/dashboard/devis/new", icon: FileText, description: "Préparer une proposition" }} metrics={[{ label: "Pipeline ouvert", value: formatWorkspaceEuro(data.openDealValueCents), detail: `${data.openDeals} affaire(s)` }, { label: "Prospects actifs", value: data.activeLeads, detail: "À qualifier ou relancer" }, { label: "Devis", value: data.quotes, detail: "Tous statuts hors archives" }, { label: "Actions sous 48 h", value: data.dueTasks, detail: "Tâches non terminées", alert: data.dueTasks > 0 }]} sections={[{ title: "Prospection", description: "Organiser l’activité et les prochaines actions.", links: [{ name: "Espace prospects", href: "/dashboard/leads", icon: Target, description: "Demandes entrantes, score et consentements." }, { name: "Pipeline", href: "/dashboard/pipeline", icon: Kanban, description: "Étapes, responsables, probabilités et forecast." }, { name: "Rendez-vous et tâches", href: "/dashboard/organisation", icon: CalendarDays, description: "Agenda opérationnel et file de travail." }] }, { title: "Offre commerciale", description: "Configurer, proposer et contractualiser.", links: [{ name: "Devis", href: "/dashboard/devis", icon: FileText, description: "Versions, configurations, marge et PDF." }, { name: "Contrats", href: "/dashboard/contrats", icon: FileSignature, description: "Modèles, clauses et signature électronique." }, { name: "Catalogue", href: "/dashboard/catalogue", icon: Package, description: "Gammes, variantes, options et tarifs." }] }]} />
}
