import { Activity, Calculator, Receipt, Repeat2, Wallet } from "lucide-react"
import { getWorkspaceOverview } from "@/actions/workspaces"
import { OnboardingRequired } from "@/components/shared/onboarding-required"
import { WorkspaceHub, formatWorkspaceEuro } from "@/app/dashboard/_components/workspace-hub"

export default async function RevenueWorkspacePage() {
  const data = await getWorkspaceOverview()
  if (!data) return <OnboardingRequired title="Configurez votre espace" description="Créez le profil entreprise avant de piloter les revenus." />
  return <WorkspaceHub eyebrow="Espace revenus" title="Facturation et trésorerie" description="Suivez ce qui doit être facturé, encaissé, rapproché ou transmis à la comptabilité." primaryAction={{ name: "Nouvelle facture", href: "/dashboard/factures/new", icon: Receipt, description: "Émettre une facture" }} metrics={[{ label: "Reste à encaisser", value: formatWorkspaceEuro(data.outstandingCents), detail: "Factures émises non soldées", alert: data.outstandingCents > 0 }, { label: "Factures en retard", value: data.overdueInvoices, detail: "Échéance dépassée", alert: data.overdueInvoices > 0 }, { label: "Contrats actifs", value: data.maintenanceContracts, detail: "Entretien et récurrence" }, { label: "Achats à suivre", value: data.pendingPurchases, detail: "Commandes non clôturées" }]} sections={[{ title: "Cycle de facturation", description: "Émettre, récurrer et suivre les règlements.", links: [{ name: "Factures", href: "/dashboard/factures", icon: Receipt, description: "Factures, acomptes, avoirs et paiements." }, { name: "Facturation récurrente", href: "/dashboard/factures/recurrentes", icon: Repeat2, description: "Échéances automatiques et occurrences." }, { name: "Dépenses", href: "/dashboard/depenses", icon: Wallet, description: "Achats, frais et justificatifs." }] }, { title: "Contrôle financier", description: "Rapprocher et exporter sans double saisie.", links: [{ name: "Banque", href: "/dashboard/comptabilite/banque", icon: Activity, description: "Importer et rapprocher les mouvements." }, { name: "Comptabilité", href: "/dashboard/comptabilite", icon: Calculator, description: "Journaux, TVA et exports précomptables." }] }]} />
}
